<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <NoWarn>$(NoWarn);CA1305;CA1815</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\WebUIToolkit.TextResources\WebUIToolkit.TextResources.csproj" />
    <ProjectReference Include="..\..\src\WebUIToolkit.TextResources.Compiler\WebUIToolkit.TextResources.Compiler.csproj" />
    <ProjectReference Include="..\..\src\WebUIToolkit.TextResources.Generator\WebUIToolkit.TextResources.Generator.csproj"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
