using System;
using System.Collections.Generic;

namespace RunicTextResources.Compiler.Generation;

internal static class CppOutputRenderer
{
    internal static IReadOnlyList<TextResourceGeneratedOutput> Render(CompiledTextCatalog catalog)
    {
        ValidateExperimentalCapabilities(catalog);
        string stem = catalog.Id + ".text-resources-v1";
        return new[]
        {
            new TextResourceGeneratedOutput(TextResourceGeneratedOutputKind.CppHeader, stem + ".hpp", "text/x-c++hdr", Header(catalog)),
            new TextResourceGeneratedOutput(TextResourceGeneratedOutputKind.CppSource, stem + ".cpp", "text/x-c++src", Source(catalog, stem + ".hpp")),
        };
    }

    private static void ValidateExperimentalCapabilities(CompiledTextCatalog catalog)
    {
        for (int localeIndex = 0; localeIndex < catalog.Locales.Count; localeIndex++)
            for (int resourceIndex = 0; resourceIndex < catalog.Locales[localeIndex].ResolvedResources.Count; resourceIndex++)
            {
                CompiledMessagePattern message = catalog.Locales[localeIndex].ResolvedResources[resourceIndex].Message;
                if (Unsupported(message.Nodes)) throw UnsupportedFeature();
                for (int variantIndex = 0; variantIndex < message.Variants.Count; variantIndex++)
                    if (Unsupported(message.Variants[variantIndex].Pattern.Nodes)) throw UnsupportedFeature();
            }

        static bool Unsupported(IReadOnlyList<CompiledMessageNode> nodes)
        {
            for (int index = 0; index < nodes.Count; index++)
                if (nodes[index] is CompiledMessageFormat or CompiledMessageMarkup) return true;
            return false;
        }

        static NotSupportedException UnsupportedFeature() => new(
            "The experimental dependency-free C++ backend supports text, inputs, and selectors only; structured formats and markup require the planned ICU4C provider backend.");
    }

    private static string Header(CompiledTextCatalog catalog)
    {
        var writer = new GenerationWriter();
        writer.Line("// <auto-generated />");
        writer.Line("#pragma once");
        writer.Line("#include <cstdint>");
        writer.Line("#include <string>");
        writer.Line("#include <string_view>");
        writer.Blank();
        writer.Line("namespace runic_text_resources::" + Namespace(catalog.Id) + " {");
        writer.Line("inline constexpr int cpp_abi_version = " + TextResourceOutputRenderer.CppAbiVersion + ";");
        writer.Line("inline constexpr std::string_view contract_fingerprint = " + CppString(catalog.Fingerprint) + ";");
        writer.Blank();
        IReadOnlyList<CompiledTextResource> resources = GenerationSupport.OrderedResources(catalog.CanonicalResources);
        for (int index = 0; index < resources.Count; index++)
        {
            CompiledTextResource resource = resources[index];
            IReadOnlyList<CompiledTextPlaceholder> placeholders = GenerationSupport.OrderedPlaceholders(resource.Placeholders);
            if (placeholders.Count != 0)
            {
                writer.Line("struct " + Identifier(resource.Key) + "_args {");
                writer.Indent();
                for (int p = 0; p < placeholders.Count; p++)
                    writer.Line(CppType(placeholders[p].Type) + " " + placeholders[p].Name + ";");
                writer.Unindent();
                writer.Line("};");
            }
            writer.Line("[[nodiscard]] std::string " + Identifier(resource.Key) + "(std::string_view locale" +
                (placeholders.Count == 0 ? string.Empty : ", const " + Identifier(resource.Key) + "_args& args") + ");");
        }
        writer.Line("}");
        return writer.ToString();
    }

    private static string Source(CompiledTextCatalog catalog, string header)
    {
        var writer = new GenerationWriter();
        writer.Line("// <auto-generated />");
        writer.Line("#include " + CppString(header));
        writer.Line("#include <charconv>");
        writer.Line("#include <stdexcept>");
        writer.Blank();
        writer.Line("namespace runic_text_resources::" + Namespace(catalog.Id) + " {");
        writer.Line("namespace {");
        writer.Line("[[maybe_unused]] std::string format(std::string_view value) { return std::string(value); }");
        writer.Line("[[maybe_unused]] std::string format(bool value) { return value ? \"true\" : \"false\"; }");
        writer.Line("template<class T> [[maybe_unused]] std::string format_number(T value) { char buffer[128]; auto result = std::to_chars(buffer, buffer + sizeof(buffer), value); if (result.ec != std::errc{}) throw std::runtime_error(\"number formatting failed\"); return {buffer, result.ptr}; }");
        writer.Line("[[maybe_unused]] std::string format(std::int64_t value) { return format_number(value); }");
        writer.Line("[[maybe_unused]] std::string format(double value) { return format_number(value); }");
        writer.Line("template<class T> [[maybe_unused]] std::string plural(T value, std::string_view locale, bool ordinal) { const auto language = locale.substr(0, 2); const auto integer = static_cast<std::int64_t>(value); if (ordinal && language == \"en\") { const auto mod100 = integer % 100; const auto mod10 = integer % 10; if (mod10 == 1 && mod100 != 11) return \"one\"; if (mod10 == 2 && mod100 != 12) return \"two\"; if (mod10 == 3 && mod100 != 13) return \"few\"; } if (!ordinal && ((language == \"fr\" && (value == 0 || value == 1)) || (language != \"fr\" && value == 1))) return \"one\"; return \"other\"; }");
        writer.Line("}");
        IReadOnlyList<CompiledTextResource> resources = GenerationSupport.OrderedResources(catalog.CanonicalResources);
        IReadOnlyList<CompiledTextLocale> locales = GenerationSupport.OrderedLocales(catalog.Locales);
        for (int index = 0; index < resources.Count; index++)
        {
            CompiledTextResource canonical = resources[index];
            IReadOnlyList<CompiledTextPlaceholder> placeholders = GenerationSupport.OrderedPlaceholders(canonical.Placeholders);
            writer.Blank();
            writer.Line("std::string " + Identifier(canonical.Key) + "(std::string_view locale" +
                (placeholders.Count == 0 ? string.Empty : ", const " + Identifier(canonical.Key) + "_args& args") + ") {");
            writer.Indent();
            for (int localeIndex = 0; localeIndex < locales.Count; localeIndex++)
            {
                CompiledTextResource localized = Find(locales[localeIndex].ResolvedResources, canonical.Key);
                writer.Line((localeIndex == 0 ? "if" : "else if") + " (locale == " + CppString(locales[localeIndex].Tag) + ") return " + Pattern(localized) + ";");
            }
            writer.Line("throw std::invalid_argument(\"unsupported locale\");");
            writer.Unindent();
            writer.Line("}");
        }
        writer.Line("}");
        return writer.ToString();
    }

    private static string Pattern(CompiledTextResource resource)
    {
        if (resource.Message.IsVariant) return VariantPattern(resource.Message);
        return NodesPattern(resource.Message);
    }

    private static string VariantPattern(CompiledMessagePattern message)
    {
        var selectors = new Dictionary<string, string>(StringComparer.Ordinal);
        for (int index = 0; index < message.Selectors.Count; index++)
        {
            CompiledMessageSelector selector = message.Selectors[index];
            selectors[selector.Name] = selector.Function switch
            {
                "plural" => "plural(args." + selector.Input + ", locale, false)",
                "ordinal" => "plural(args." + selector.Input + ", locale, true)",
                _ => "format(args." + selector.Input + ")",
            };
        }
        string fallback = "std::string{}";
        for (int index = message.Variants.Count - 1; index >= 0; index--)
        {
            CompiledMessageVariant variant = message.Variants[index];
            var conditions = new List<string>();
            foreach (KeyValuePair<string, string> match in variant.Matches)
                if (match.Value != "*") conditions.Add(selectors[match.Key] + " == " + CppString(match.Value));
            string value = NodesPattern(variant.Pattern);
            fallback = conditions.Count == 0 ? value : "(" + string.Join(" && ", conditions) + " ? " + value + " : " + fallback + ")";
        }
        return fallback;
    }

    private static string NodesPattern(CompiledMessagePattern message)
    {
        if (message.Nodes.Count == 0) return "std::string{}";
        var parts = new List<string>();
        for (int index = 0; index < message.Nodes.Count; index++)
        {
            if (message.Nodes[index] is CompiledMessageText text) parts.Add("std::string(" + CppString(text.Value) + ")");
            else if (message.Nodes[index] is CompiledMessageInput input) parts.Add("format(args." + input.Name + ")");
        }
        return string.Join(" + ", parts);
    }

    private static CompiledTextResource Find(IReadOnlyList<CompiledTextResource> resources, string key)
    {
        for (int index = 0; index < resources.Count; index++) if (resources[index].Key == key) return resources[index];
        throw new InvalidOperationException("Missing resolved key '" + key + "'.");
    }

    private static string CppType(TextResourceArgumentType type) => type switch
    {
        TextResourceArgumentType.Int => "std::int64_t",
        TextResourceArgumentType.Number => "double",
        TextResourceArgumentType.Boolean => "bool",
        _ => "std::string_view",
    };

    private static string Identifier(string key)
    {
        string[] parts = key.Split('.');
        string result = "m";
        for (int index = 0; index < parts.Length; index++) result += "_" + parts[index].Length + parts[index];
        return result;
    }

    private static string Namespace(string catalog) => "catalog_" + catalog.Replace('.', '_').Replace('-', '_');

    private static string CppString(string value) => GenerationSupport.JsonString(value)
        .Replace("\\u2028", "\\u2028", StringComparison.Ordinal)
        .Replace("\\u2029", "\\u2029", StringComparison.Ordinal);
}
