<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Runic.Translations.Compiler\Runic.Translations.Compiler.csproj" />
    <ProjectReference Include="..\..\src\Runic.Translations.Tooling\Runic.Translations.Tooling.csproj" />
  </ItemGroup>
</Project>
