<Project>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <DebugType>embedded</DebugType>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/ViktorJannicke/WebUIToolkit</RepositoryUrl>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <WebUIToolkitDefaultTargetFramework>net10.0</WebUIToolkitDefaultTargetFramework>
    <WebUIToolkitCompatibilityTargetFramework>net8.0</WebUIToolkitCompatibilityTargetFramework>
    <WebUIToolkitGeneratorTargetFramework>netstandard2.0</WebUIToolkitGeneratorTargetFramework>
  </PropertyGroup>
</Project>
