using System;
using System.Collections.Generic;
using System.Text;

namespace Runic.Translations.Compiler.Generation;

internal static class EsmOutputRenderer
{
    internal static IReadOnlyList<TranslationGeneratedOutput> Render(CompiledTextCatalog catalog)
    {
        string root = catalog.Id + ".esm/";
        IReadOnlyList<CompiledTranslation> canonical = GenerationSupport.OrderedResources(catalog.CanonicalResources);
        var outputs = new List<TranslationGeneratedOutput>(canonical.Count + 10)
        {
            Output(TranslationGeneratedOutputKind.EsmRuntime, root + "runtime.js", "text/javascript", Runtime(catalog)),
            Output(TranslationGeneratedOutputKind.EsmRuntimeTypes, root + "runtime.d.ts", "text/typescript", RuntimeTypes(catalog)),
            Output(TranslationGeneratedOutputKind.EsmTransport, root + "transport.js", "text/javascript", Transport(catalog)),
            Output(TranslationGeneratedOutputKind.EsmTransportTypes, root + "transport.d.ts", "text/typescript", TransportTypes(catalog)),
            Output(TranslationGeneratedOutputKind.EsmDynamic, root + "dynamic.js", "text/javascript", Dynamic(catalog)),
            Output(TranslationGeneratedOutputKind.EsmDynamicTypes, root + "dynamic.d.ts", "text/typescript", DynamicTypes(catalog)),
            Output(TranslationGeneratedOutputKind.EsmServer, root + "server.js", "text/javascript", Server()),
            Output(TranslationGeneratedOutputKind.EsmServerTypes, root + "server.d.ts", "text/typescript", ServerTypes()),
        };

        var modules = new List<MessageModule>(canonical.Count);
        for (int index = 0; index < canonical.Count; index++)
        {
            CompiledTranslation resource = canonical[index];
            string identifier = MessageIdentifier(resource.Key);
            string fileName = MessageFileName(resource.Key);
            modules.Add(new MessageModule(resource, identifier, fileName));
            outputs.Add(Output(
                TranslationGeneratedOutputKind.EsmMessage,
                root + "messages/" + fileName,
                "text/javascript",
                Message(catalog, resource, identifier)));
        }

        outputs.Add(Output(
            TranslationGeneratedOutputKind.EsmMessageNamespace,
            root + "messages/_index.js",
            "text/javascript",
            MessageNamespaceIndex(modules)));
        outputs.Add(Output(
            TranslationGeneratedOutputKind.EsmMessagesIndex,
            root + "messages.js",
            "text/javascript",
            MessagesIndex()));
        outputs.Add(Output(
            TranslationGeneratedOutputKind.EsmMessagesTypes,
            root + "messages.d.ts",
            "text/typescript",
            MessagesTypes(modules)));

        TranslationGeneratedOutput manifest = WebModuleManifest(catalog, outputs);
        outputs.Add(manifest);
        outputs.Sort(static (left, right) => StringComparer.Ordinal.Compare(left.RelativePath, right.RelativePath));
        return outputs.ToArray();
    }

    private static string Runtime(CompiledTextCatalog catalog)
    {
        var writer = new GenerationWriter();
        writer.Line("// <auto-generated />");
        writer.Line("// Runic Translations ESM ABI " + TranslationOutputRenderer.EsmAbiVersion + ".");
        writer.Line("export const esmAbiVersion = " + TranslationOutputRenderer.EsmAbiVersion + ";");
        writer.Line("export const catalog = " + GenerationSupport.JsonString(catalog.Id) + ";");
        writer.Line("export const contractFingerprint = " + GenerationSupport.JsonString(catalog.Fingerprint) + ";");
        writer.Line("export const baseLocale = " + GenerationSupport.JsonString(catalog.DefaultLocale) + ";");
        writer.Line("export const locales = Object.freeze(" + JsonLocales(catalog.Locales) + ");");
        writer.Line("const localeSet = new Set(locales);");
        writer.Line("const generatedLocaleData = " + TranslationCapabilityRegistry.EsmLocaleDataJson + ";");
        writer.Line("let localeResolver = () => typeof document === \"undefined\" ? baseLocale : (document.documentElement.lang || baseLocale);");
        writer.Blank();
        writer.Line("export function configureLocaleResolver(resolver) {");
        writer.Indent();
        writer.Line("if (typeof resolver !== \"function\") throw new TypeError(\"The locale resolver must be a function.\");");
        writer.Line("const previous = localeResolver;");
        writer.Line("localeResolver = resolver;");
        writer.Line("return () => { if (localeResolver === resolver) localeResolver = previous; };");
        writer.Unindent();
        writer.Line("}");
        writer.Blank();
        writer.Line("export function getLocale() { return resolveLocale(localeResolver()); }");
        writer.Blank();
        writer.Line("export function createLocaleSource(options = {}) {");
        writer.Indent();
        writer.Line("if (typeof options !== \"object\" || options === null || Array.isArray(options)) throw new TypeError(\"Locale source options must be an object.\");");
        writer.Line("let current = resolveLocale(options.initialLocale ?? baseLocale);");
        writer.Line("const listeners = new Set();");
        writer.Line("return Object.freeze({");
        writer.Indent();
        writer.Line("getLocale() { return current; },");
        writer.Line("subscribe(listener) {");
        writer.Indent();
        writer.Line("if (typeof listener !== \"function\") throw new TypeError(\"A locale listener must be a function.\");");
        writer.Line("listeners.add(listener);");
        writer.Line("let subscribed = true;");
        writer.Line("return () => { if (subscribed) { subscribed = false; listeners.delete(listener); } };");
        writer.Unindent();
        writer.Line("},");
        writer.Line("setLocale(requested) {");
        writer.Indent();
        writer.Line("const next = resolveLocale(requested);");
        writer.Line("if (next === current) return;");
        writer.Line("current = next;");
        writer.Line("for (const listener of Array.from(listeners)) listener(next);");
        writer.Unindent();
        writer.Line("},");
        writer.Unindent();
        writer.Line("});");
        writer.Unindent();
        writer.Line("}");
        writer.Blank();
        writer.Line("export function resolveLocale(requested) {");
        writer.Indent();
        writer.Line("if (typeof requested !== \"string\" || requested.length === 0) throw new RangeError(\"A non-empty locale is required.\");");
        writer.Line("const canonical = canonicalizeLocale(requested);");
        writer.Line("if (localeSet.has(canonical)) return canonical;");
        if (catalog.UnsupportedLocale == TranslationUnsupportedLocalePolicy.ParentsThenDefault)
        {
            writer.Line("let parent = canonical;");
            writer.Line("while (parent.includes(\"-\")) {");
            writer.Indent();
            writer.Line("parent = parent.slice(0, parent.lastIndexOf(\"-\"));");
            writer.Line("if (localeSet.has(parent)) return parent;");
            writer.Unindent();
            writer.Line("}");
            writer.Line("return baseLocale;");
        }
        else if (catalog.UnsupportedLocale == TranslationUnsupportedLocalePolicy.Default)
        {
            writer.Line("return baseLocale;");
        }
        else
        {
            writer.Line("throw new RangeError(`Unsupported locale '${requested}'.`);");
        }
        writer.Unindent();
        writer.Line("}");
        writer.Blank();
        writer.Line("export function validateInputs(inputs, expected) {");
        writer.Indent();
        writer.Line("if (typeof inputs !== \"object\" || inputs === null || Array.isArray(inputs)) throw new TypeError(\"Message inputs must be an object.\");");
        writer.Line("const actual = Object.keys(inputs).sort();");
        writer.Line("if (actual.length !== expected.length || actual.some((name, index) => name !== expected[index])) {");
        writer.Indent();
        writer.Line("throw new TypeError(`Message inputs must contain exactly: ${expected.join(\", \")}.`);");
        writer.Unindent();
        writer.Line("}");
        writer.Unindent();
        writer.Line("}");
        writer.Blank();
        writer.Line("export function formatInput(inputs, name, type, format, locale) {");
        writer.Indent();
        writer.Line("const value = inputs[name];");
        writer.Line("switch (type) {");
        writer.Indent();
        writer.Line("case \"string\": if (typeof value !== \"string\") return invalidType(name, type); return value;");
        writer.Line("case \"int\": return formatInteger(value, format, locale, name);");
        writer.Line("case \"number\": return formatNumber(value, format, locale, name);");
        writer.Line("case \"bool\": if (typeof value !== \"boolean\") return invalidType(name, type); return value ? \"true\" : \"false\";");
        writer.Line("case \"date\": return formatDate(value, format, locale, name);");
        writer.Line("case \"time\": return formatTime(value, format, locale, name);");
        writer.Line("case \"datetime\": return formatDateTime(value, format, locale, name);");
        writer.Line("case \"guid\": return formatGuid(value, format, name);");
        writer.Line("default: throw new TypeError(`Unsupported portable input type '${type}'.`);");
        writer.Unindent();
        writer.Line("}");
        writer.Unindent();
        writer.Line("}");
        writer.Blank();
        writer.Line("export function localized(value) { return value; }");
        writer.Line("export function localizedContent(nodes) { return Object.freeze({ kind: \"localized-content\", nodes: Object.freeze(nodes) }); }");
        writer.Line("export function selectPlural(value, locale, ordinal = false) {");
        writer.Indent();
        writer.Line("if (typeof value !== \"bigint\" && (typeof value !== \"number\" || !Number.isFinite(value))) throw new TypeError(\"Plural values must be finite numbers or bigint values.\");");
        writer.Line("const language = canonicalizeLocale(locale).split(\"-\")[0].toLowerCase();");
        writer.Line("const rules = generatedLocaleData.plural[language]; if (!rules) throw new RangeError(`Plural selection is not supported for locale '${locale}'.`);");
        writer.Line("const rule = rules[ordinal ? 1 : 0]; const absolute = value < 0 ? -value : value;");
        writer.Line("const integral = typeof absolute === \"bigint\" || Number.isInteger(absolute);");
        writer.Line("const equals = expected => typeof absolute === \"bigint\" ? absolute === BigInt(expected) : absolute === expected;");
        writer.Line("const modulo = divisor => Number(absolute % (typeof absolute === \"bigint\" ? BigInt(divisor) : divisor));");
        writer.Line("if (rule === \"english\" && integral) { const mod100 = modulo(100); const mod10 = modulo(10); if (mod10 === 1 && mod100 !== 11) return \"one\"; if (mod10 === 2 && mod100 !== 12) return \"two\"; if (mod10 === 3 && mod100 !== 13) return \"few\"; }");
        writer.Line("else if (rule === \"italian\") return [8, 11, 80, 800].some(equals) ? \"many\" : \"other\";");
        writer.Line("else if (rule === \"swedish\") { const mod100 = modulo(100); const mod10 = modulo(10); return (mod10 === 1 || mod10 === 2) && mod100 !== 11 && mod100 !== 12 ? \"one\" : \"other\"; }");
        writer.Line("else if (rule === \"one\" || rule === \"integer-one\") return equals(1) ? \"one\" : \"other\";");
        writer.Line("else if (rule === \"danish\") return equals(1) || (typeof absolute === \"number\" && !integral && (Math.trunc(absolute) === 0 || Math.trunc(absolute) === 1)) ? \"one\" : \"other\";");
        writer.Line("else if (rule === \"one-and-million\") { if (equals(1)) return \"one\"; return integral && !equals(0) && modulo(1000000) === 0 ? \"many\" : \"other\"; }");
        writer.Line("else if (rule === \"french\") { if (integral && !equals(0) && modulo(1000000) === 0) return \"many\"; const integer = typeof absolute === \"bigint\" ? absolute : Math.trunc(absolute); return integer === 0 || integer === 0n || integer === 1 || integer === 1n ? \"one\" : \"other\"; }");
        writer.Line("return \"other\";");
        writer.Unindent();
        writer.Line("}");
        writer.Line("export function formatRelativeTime(inputs, name, unit, numeric, locale) {");
        writer.Indent();
        writer.Line("const value = inputs[name]; if (typeof value !== \"bigint\" && (typeof value !== \"number\" || !Number.isFinite(value))) return invalidType(name, \"a finite relative-time number\");");
        writer.Line("if (![\"second\",\"minute\",\"hour\",\"day\",\"week\",\"month\",\"year\"].includes(unit) || ![\"always\",\"auto\"].includes(numeric)) throw new RangeError(\"Invalid relative-time options.\");");
        writer.Line("const language = canonicalizeLocale(locale).split(\"-\")[0].toLowerCase(); const data = generatedLocaleData.relativeTime[language]; if (!data) throw new RangeError(`Relative-time formatting is not supported for locale '${locale}'.`);");
        writer.Line("if (numeric === \"auto\" && unit === \"day\" && (value === -1 || value === -1n || value === 0 || value === 0n || value === 1 || value === 1n)) return data.autoDay[Number(value) + 1];");
        writer.Line("const absolute = value < 0 ? -value : value; const forms = data.units[unit]; const noun = forms[selectPlural(absolute, locale, false) === \"one\" ? 0 : 1];");
        writer.Line("const number = typeof absolute === \"bigint\" ? absolute.toString() : expandExponent(String(absolute));");
        writer.Line("return (value < 0 ? data.past : data.future).replace(\"{0}\", number).replace(\"{unit}\", noun);");
        writer.Unindent();
        writer.Line("}");
        writer.Blank();
        writer.Line("function canonicalizeLocale(locale) {");
        writer.Indent();
        writer.Line("try { return Intl.getCanonicalLocales(locale)[0]; } catch { throw new RangeError(`Invalid locale '${locale}'.`); }");
        writer.Unindent();
        writer.Line("}");
        writer.Line("function invalidType(name, type) { throw new TypeError(`Input '${name}' must be ${type}.`); }");
        writer.Line("function formatInteger(value, format, locale, name) {");
        writer.Indent();
        writer.Line("if (typeof value === \"number\") { if (!Number.isSafeInteger(value)) return invalidType(name, \"a safe integer or bigint\"); }");
        writer.Line("else if (typeof value !== \"bigint\") return invalidType(name, \"a safe integer or bigint\");");
        writer.Line("if (format === \"plain\") return value.toString();");
        writer.Line("if (format === \"grouped\") return new Intl.NumberFormat(locale, { maximumFractionDigits: 0 }).format(value);");
        writer.Line("throw new TypeError(`Unsupported integer format '${format}'.`);");
        writer.Unindent();
        writer.Line("}");
        writer.Line("function formatNumber(value, format, locale, name) {");
        writer.Indent();
        writer.Line("if (typeof value !== \"number\" || !Number.isFinite(value)) return invalidType(name, \"a finite number\");");
        writer.Line("if (format === \"plain\") return expandExponent(String(value));");
        writer.Line("if (format === \"grouped\") return new Intl.NumberFormat(locale, { maximumFractionDigits: 20 }).format(value);");
        writer.Line("const fixed = /^fixed([0-6])$/.exec(format);");
        writer.Line("if (fixed) return new Intl.NumberFormat(locale, { minimumFractionDigits: Number(fixed[1]), maximumFractionDigits: Number(fixed[1]), useGrouping: false }).format(value);");
        writer.Line("const percent = /^percent([0-4])$/.exec(format);");
        writer.Line("if (percent) return new Intl.NumberFormat(locale, { style: \"percent\", minimumFractionDigits: Number(percent[1]), maximumFractionDigits: Number(percent[1]) }).format(value);");
        writer.Line("throw new TypeError(`Unsupported number format '${format}'.`);");
        writer.Unindent();
        writer.Line("}");
        writer.Line("function expandExponent(value) {");
        writer.Indent();
        writer.Line("if (!/[eE]/.test(value)) return value;");
        writer.Line("const [coefficient, exponentText] = value.toLowerCase().split(\"e\");");
        writer.Line("const exponent = Number(exponentText);");
        writer.Line("const negative = coefficient.startsWith(\"-\");");
        writer.Line("const unsigned = negative ? coefficient.slice(1) : coefficient;");
        writer.Line("const point = unsigned.indexOf(\".\");");
        writer.Line("const digits = unsigned.replace(\".\", \"\");");
        writer.Line("const decimal = (point < 0 ? unsigned.length : point) + exponent;");
        writer.Line("const result = decimal <= 0 ? `0.${\"0\".repeat(-decimal)}${digits}` : decimal >= digits.length ? digits + \"0\".repeat(decimal - digits.length) : `${digits.slice(0, decimal)}.${digits.slice(decimal)}`;");
        writer.Line("return negative ? `-${result}` : result;");
        writer.Unindent();
        writer.Line("}");
        writer.Line("function formatDate(value, format, locale, name) {");
        writer.Indent();
        writer.Line("if (typeof value !== \"string\" || !/^\\d{4}-\\d{2}-\\d{2}$/.test(value)) return invalidType(name, \"an ISO date string\");");
        writer.Line("if (format === \"iso\") return value;");
        writer.Line("const date = new Date(`${value}T00:00:00Z`); if (Number.isNaN(date.valueOf()) || date.toISOString().slice(0, 10) !== value) return invalidType(name, \"an ISO date string\");");
        writer.Line("if (![\"short\", \"medium\", \"long\"].includes(format)) throw new TypeError(`Unsupported date format '${format}'.`);");
        writer.Line("return new Intl.DateTimeFormat(locale, { dateStyle: format, timeZone: \"UTC\" }).format(date);");
        writer.Unindent();
        writer.Line("}");
        writer.Line("function formatTime(value, format, locale, name) {");
        writer.Indent();
        writer.Line("if (typeof value !== \"string\" || !/^\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,7})?$/.test(value)) return invalidType(name, \"an ISO time string\");");
        writer.Line("if (format === \"iso\") return value;");
        writer.Line("const date = new Date(`1970-01-01T${value}Z`); if (Number.isNaN(date.valueOf()) || Number(value.slice(0, 2)) > 23 || Number(value.slice(3, 5)) > 59 || Number(value.slice(6, 8)) > 59) return invalidType(name, \"an ISO time string\");");
        writer.Line("if (![\"short\", \"medium\"].includes(format)) throw new TypeError(`Unsupported time format '${format}'.`);");
        writer.Line("return new Intl.DateTimeFormat(locale, { timeStyle: format, timeZone: \"UTC\" }).format(date);");
        writer.Unindent();
        writer.Line("}");
        writer.Line("function formatDateTime(value, format, locale, name) {");
        writer.Indent();
        writer.Line("if (typeof value !== \"string\" || !/^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,7})?(?:Z|[+-]\\d{2}:\\d{2})$/.test(value)) return invalidType(name, \"an ISO instant string\");");
        writer.Line("const date = new Date(value); if (Number.isNaN(date.valueOf())) return invalidType(name, \"an ISO instant string\");");
        writer.Line("if (format === \"iso\") return date.toISOString().replace(/\\.(\\d{3})Z$/, (_, digits) => `.${digits}0000Z`);");
        writer.Line("if (![\"short\", \"medium\", \"long\"].includes(format)) throw new TypeError(`Unsupported datetime format '${format}'.`);");
        writer.Line("const dateStyle = format; const timeStyle = format === \"long\" ? \"long\" : format;");
        writer.Line("return new Intl.DateTimeFormat(locale, { dateStyle, timeStyle, timeZone: \"UTC\" }).format(date);");
        writer.Unindent();
        writer.Line("}");
        writer.Line("function formatGuid(value, format, name) {");
        writer.Indent();
        writer.Line("if (typeof value !== \"string\" || !/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(value)) return invalidType(name, \"a canonical UUID string\");");
        writer.Line("const canonical = value.toLowerCase(); if (format === \"d\") return canonical; if (format === \"n\") return canonical.replaceAll(\"-\", \"\");");
        writer.Line("throw new TypeError(`Unsupported guid format '${format}'.`);");
        writer.Unindent();
        writer.Line("}");
        return writer.ToString();
    }

    private static string RuntimeTypes(CompiledTextCatalog catalog)
    {
        var writer = new GenerationWriter();
        writer.Line("// <auto-generated />");
        writer.Line("export declare const esmAbiVersion: " + TranslationOutputRenderer.EsmAbiVersion + ";");
        writer.Line("export declare const catalog: " + GenerationSupport.JsonString(catalog.Id) + ";");
        writer.Line("export declare const contractFingerprint: " + GenerationSupport.JsonString(catalog.Fingerprint) + ";");
        writer.Line("export type Locale = " + LocaleUnion(catalog.Locales) + ";");
        writer.Line("export declare const baseLocale: Locale;");
        writer.Line("export declare const locales: readonly Locale[];");
        writer.Line("declare const localizedStringBrand: unique symbol;");
        writer.Line("export type LocalizedString = string & { readonly [localizedStringBrand]: true };");
        writer.Line("export type LocalizedContentNode = { readonly kind: \"text\"; readonly value: string } | { readonly kind: \"element\"; readonly name: string; readonly attributes: Readonly<Record<string, string>>; readonly children: readonly LocalizedContentNode[] }; ");
        writer.Line("export interface LocalizedContent { readonly kind: \"localized-content\"; readonly nodes: readonly LocalizedContentNode[]; }");
        writer.Line("export interface MessageOptions { readonly locale?: Locale | string; }");
        writer.Line("export interface LocaleSource { getLocale(): Locale; subscribe(listener: (locale: Locale) => void): () => void; }");
        writer.Line("export interface MutableLocaleSource extends LocaleSource { setLocale(locale: Locale | string): void; }");
        writer.Line("export interface CreateLocaleSourceOptions { readonly initialLocale?: Locale | string; }");
        writer.Line("export declare function configureLocaleResolver(resolver: () => string): () => void;");
        writer.Line("export declare function getLocale(): Locale;");
        writer.Line("export declare function createLocaleSource(options?: CreateLocaleSourceOptions): MutableLocaleSource;");
        writer.Line("export declare function resolveLocale(requested: string): Locale;");
        writer.Line("export declare function validateInputs(inputs: Readonly<Record<string, unknown>>, expected: readonly string[]): void;");
        writer.Line("export declare function formatInput(inputs: Readonly<Record<string, unknown>>, name: string, type: string, format: string, locale: Locale | string): string;");
        writer.Line("export declare function localized(value: string): LocalizedString;");
        writer.Line("export declare function localizedContent(nodes: readonly LocalizedContentNode[]): LocalizedContent;");
        writer.Line("export declare function selectPlural(value: number | bigint, locale: Locale | string, ordinal?: boolean): string;");
        writer.Line("export declare function formatRelativeTime(inputs: Readonly<Record<string, number | bigint>>, name: string, unit: \"second\" | \"minute\" | \"hour\" | \"day\" | \"week\" | \"month\" | \"year\", numeric: \"always\" | \"auto\", locale: Locale | string): string;");
        return writer.ToString();
    }

    private static string Server()
    {
        var writer = new GenerationWriter();
        writer.Line("// <auto-generated />");
        writer.Line("import { AsyncLocalStorage } from \"node:async_hooks\";");
        writer.Line("import { baseLocale, configureLocaleResolver, resolveLocale } from \"./runtime.js\";");
        writer.Line("const localeStorage = new AsyncLocalStorage();");
        writer.Line("configureLocaleResolver(() => localeStorage.getStore() ?? baseLocale);");
        writer.Blank();
        writer.Line("export function runWithLocale(locale, operation) {");
        writer.Indent();
        writer.Line("if (typeof operation !== \"function\") throw new TypeError(\"A request operation is required.\");");
        writer.Line("return localeStorage.run(resolveLocale(locale), operation);");
        writer.Unindent();
        writer.Line("}");
        writer.Line("export function getRequestLocale() { return localeStorage.getStore() ?? baseLocale; }");
        return writer.ToString();
    }

    private static string ServerTypes()
    {
        var writer = new GenerationWriter();
        writer.Line("// <auto-generated />");
        writer.Line("import type { Locale } from \"./runtime.js\";");
        writer.Line("export declare function runWithLocale<T>(locale: Locale | string, operation: () => T): T;");
        writer.Line("export declare function getRequestLocale(): Locale;");
        return writer.ToString();
    }

    private static string Transport(CompiledTextCatalog catalog)
    {
        var writer = new GenerationWriter();
        writer.Line("// <auto-generated />");
        writer.Line("const catalog = " + GenerationSupport.JsonString(catalog.Id) + ";");
        writer.Line("const contractFingerprint = " + GenerationSupport.JsonString(catalog.Fingerprint) + ";");
        writer.Line("const contracts = Object.freeze({");
        writer.Indent();
        IReadOnlyList<CompiledTranslation> resources = GenerationSupport.OrderedResources(catalog.CanonicalResources);
        for (int index = 0; index < resources.Count; index++)
        {
            IReadOnlyList<CompiledTextPlaceholder> placeholders = GenerationSupport.OrderedPlaceholders(resources[index].Placeholders);
            var contract = new StringBuilder("{");
            for (int p = 0; p < placeholders.Count; p++)
            {
                if (p != 0) contract.Append(',');
                contract.Append(GenerationSupport.JsonString(placeholders[p].Name)).Append(':')
                    .Append(GenerationSupport.JsonString(PortableType(placeholders[p].Type)));
            }
            contract.Append('}');
            writer.Line(GenerationSupport.JsonString(resources[index].Key) + ": Object.freeze(" + contract + "),");
        }
        writer.Unindent();
        writer.Line("});");
        writer.Blank();
        writer.Line("export function decodeTextReference(value) {");
        writer.Indent();
        writer.Line("if (!isObject(value) || value.version !== 1) return failure(\"unsupported-version\");");
        writer.Line("if (value.catalog !== catalog) return failure(\"catalog-mismatch\");");
        writer.Line("if (value.contractFingerprint !== contractFingerprint) return failure(\"fingerprint-mismatch\");");
        writer.Line("if (typeof value.key !== \"string\" || value.key.length === 0 || value.key.length > 512 || !(value.key in contracts)) return failure(\"unknown-key\");");
        writer.Line("if (!isObject(value.arguments) || Object.keys(value.arguments).length > 32) return failure(\"invalid-arguments\");");
        writer.Line("const contract = contracts[value.key]; const names = Object.keys(contract).sort(); const actual = Object.keys(value.arguments).sort();");
        writer.Line("if (names.length !== actual.length || names.some((name, index) => name !== actual[index])) return failure(\"invalid-arguments\");");
        writer.Line("const argumentsValue = {};");
        writer.Line("for (const name of names) { const decoded = decodeArgument(value.arguments[name], contract[name]); if (!decoded.ok) return failure(`invalid-argument:${name}`); argumentsValue[name] = decoded.value; }");
        writer.Line("if (value.fallbackText !== undefined && (typeof value.fallbackText !== \"string\" || value.fallbackText.length > 65536)) return failure(\"invalid-fallback\");");
        writer.Line("return { ok: true, value: Object.freeze({ version: 1, catalog, contractFingerprint, key: value.key, arguments: Object.freeze(argumentsValue), fallbackText: value.fallbackText }) };");
        writer.Unindent();
        writer.Line("}");
        writer.Line("export function formatTextReference(reference, handlers, options) { const handler = handlers[reference.key]; if (typeof handler !== \"function\") { if (reference.fallbackText !== undefined) return reference.fallbackText; throw new RangeError(`No text-reference handler for '${reference.key}'.`); } return handler(reference.arguments, options); }");
        writer.Line("function decodeArgument(value, type) { if (type === \"bool\") return typeof value === \"boolean\" ? { ok: true, value } : failure(); if (typeof value !== \"string\" || value.length > 16384) return failure(); if (type === \"int64\") { if (!/^-?(?:0|[1-9]\\d*)$/.test(value)) return failure(); try { return { ok: true, value: BigInt(value) }; } catch { return failure(); } } if (type === \"decimal\") { if (!/^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$/.test(value)) return failure(); const number = Number(value); return Number.isFinite(number) ? { ok: true, value: number } : failure(); } return { ok: true, value }; }");
        writer.Line("function isObject(value) { return typeof value === \"object\" && value !== null && !Array.isArray(value); }");
        writer.Line("function failure(reason) { return { ok: false, reason }; }");
        return writer.ToString();
    }

    private static string TransportTypes(CompiledTextCatalog catalog)
    {
        var writer = new GenerationWriter();
        writer.Line("// <auto-generated />");
        writer.Line("import type { LocalizedContent, LocalizedString, MessageOptions } from \"./runtime.js\";");
        writer.Line("export interface TextReferenceWire { readonly version: 1; readonly catalog: string; readonly contractFingerprint: string; readonly key: string; readonly arguments: Readonly<Record<string, string | boolean>>; readonly fallbackText?: string; }");
        writer.Line("export interface DecodedTextReference { readonly version: 1; readonly catalog: " + GenerationSupport.JsonString(catalog.Id) + "; readonly contractFingerprint: " + GenerationSupport.JsonString(catalog.Fingerprint) + "; readonly key: string; readonly arguments: Readonly<Record<string, unknown>>; readonly fallbackText?: string; }");
        writer.Line("export type DecodeResult = { readonly ok: true; readonly value: DecodedTextReference } | { readonly ok: false; readonly reason?: string };");
        writer.Line("export declare function decodeTextReference(value: unknown): DecodeResult;");
        writer.Line("export declare function formatTextReference(reference: DecodedTextReference, handlers: Readonly<Record<string, (argumentsValue: Readonly<Record<string, unknown>>, options?: MessageOptions) => LocalizedString | LocalizedContent>>, options?: MessageOptions): LocalizedString | LocalizedContent | string;");
        return writer.ToString();
    }

    private static string Dynamic(CompiledTextCatalog catalog)
    {
        var writer = new GenerationWriter();
        writer.Line("// <auto-generated />");
        writer.Line("import { formatInput, formatRelativeTime, localized, localizedContent, resolveLocale, selectPlural, validateInputs } from \"./runtime.js\";");
        writer.Line("const catalog = " + GenerationSupport.JsonString(catalog.Id) + ";");
        writer.Line("const contractFingerprint = " + GenerationSupport.JsonString(catalog.Fingerprint) + ";");
        writer.Line("const contracts = Object.freeze({");
        writer.Indent();
        IReadOnlyList<CompiledTranslation> resources = GenerationSupport.OrderedResources(catalog.CanonicalResources);
        for (int index = 0; index < resources.Count; index++)
        {
            IReadOnlyList<CompiledTextPlaceholder> placeholders = GenerationSupport.OrderedPlaceholders(resources[index].Placeholders);
            var contract = new StringBuilder("{");
            for (int placeholderIndex = 0; placeholderIndex < placeholders.Count; placeholderIndex++)
            {
                if (placeholderIndex != 0) contract.Append(',');
                CompiledTextPlaceholder placeholder = placeholders[placeholderIndex];
                contract.Append(GenerationSupport.JsonString(placeholder.Name)).Append(":Object.freeze({type:")
                    .Append(GenerationSupport.JsonString(GenerationSupport.JsonArgumentType(placeholder.Type)))
                    .Append(",format:").Append(GenerationSupport.JsonString(placeholder.Format)).Append("})");
            }
            contract.Append('}');
            writer.Line(GenerationSupport.JsonString(resources[index].Key) + ": Object.freeze(" + contract + "),");
        }
        writer.Unindent();
        writer.Line("});");
        writer.Line("const selectorFunctions = new Set([\"literal\", \"plural\", \"ordinal\"]);");
        writer.Line("const formatFunctions = new Set([\"string\", \"integer\", \"number\", \"date\", \"time\", \"datetime\", \"uuid\", \"relativeTime\"]);");
        writer.Line("const localePackV2Limits = Object.freeze({ maximumDocumentBytes: 8388608, maximumDepth: 64, maximumMessages: 50000, maximumPatternBytes: 65536, maximumArgumentsPerMessage: 32 });");
        writer.Blank();
        writer.Line("export function decodeLocaleArtifact(value) {");
        writer.Indent();
        writer.Line("if (!isObject(value)) return failure(\"RTR0023/malformed\");");
        writer.Line("if (hasUnknownKeys(value, [\"artifactVersion\",\"messageGrammarVersion\",\"catalog\",\"locale\",\"contractFingerprint\",\"messages\"])) return failure(\"RTR0023/unknown-member\");");
        writer.Line("if (!hasKeys(value, [\"artifactVersion\",\"messageGrammarVersion\",\"catalog\",\"locale\",\"contractFingerprint\",\"messages\"])) return failure(\"RTR0023/malformed\");");
        writer.Line("if (value.artifactVersion !== 2) return failure(\"RTR0023/artifact-version-mismatch\");");
        writer.Line("if (value.messageGrammarVersion !== 2) return failure(\"RTR0023/message-grammar-version-mismatch\");");
        writer.Line("if (value.catalog !== catalog) return failure(\"RTR0023/catalog-mismatch\");");
        writer.Line("if (value.contractFingerprint !== contractFingerprint) return failure(\"RTR0023/contract-fingerprint-mismatch\");");
        writer.Line("if (typeof value.locale !== \"string\") return failure(\"RTR0023/locale-mismatch\");");
        writer.Line("let locale; try { locale = resolveLocale(value.locale); } catch { return failure(\"RTR0023/locale-mismatch\"); }");
        writer.Line("if (locale !== value.locale || !isObject(value.messages)) return failure(\"RTR0023/malformed\");");
        writer.Line("if (Object.keys(value.messages).length > localePackV2Limits.maximumMessages) return failure(\"RTR0023/limit-exceeded\");");
        writer.Line("const decoded = {};");
        writer.Line("for (const [key, ast] of Object.entries(value.messages)) { if (!Object.hasOwn(contracts, key)) return failure(\"RTR0023/unknown-key\"); const validation = validateAst(ast, contracts[key]); if (validation) return failure(`RTR0023/${validation}`); decoded[key] = deepFreeze(ast); }");
        writer.Line("return { ok: true, value: Object.freeze({ artifactVersion: 2, messageGrammarVersion: 2, catalog, locale, contractFingerprint, messages: Object.freeze(decoded) }) };");
        writer.Unindent();
        writer.Line("}");
        writer.Blank();
        writer.Line("export async function decodeLocalePackV2(content, expectedLocale, integrityVerifier) {");
        writer.Indent();
        writer.Line("if (!(content instanceof Uint8Array) || content.byteLength === 0) return failure(\"RTR0023/malformed\");");
        writer.Line("if (content.byteLength > localePackV2Limits.maximumDocumentBytes) return failure(\"RTR0023/limit-exceeded\");");
        writer.Line("const snapshot = new Uint8Array(content);");
        writer.Line("if (integrityVerifier) { try { if (!await integrityVerifier(new Uint8Array(snapshot))) return failure(\"RTR0023/integrity-rejected\"); } catch { return failure(\"RTR0023/integrity-rejected\"); } }");
        writer.Line("if (!withinJsonDepth(snapshot, localePackV2Limits.maximumDepth)) return failure(\"RTR0023/limit-exceeded\");");
        writer.Line("let text, value; try { text = new TextDecoder(\"utf-8\", { fatal: true }).decode(snapshot); if (hasDuplicateJsonProperties(text)) return failure(\"RTR0023/malformed\"); value = JSON.parse(text); } catch { return failure(\"RTR0023/malformed\"); }");
        writer.Line("const decoded = decodeLocaleArtifact(value); if (!decoded.ok) return decoded;");
        writer.Line("if (typeof expectedLocale !== \"string\" || decoded.value.locale !== expectedLocale) return failure(\"RTR0023/locale-mismatch\");");
        writer.Line("return decoded;");
        writer.Unindent();
        writer.Line("}");
        writer.Blank();
        writer.Line("export function formatDynamicMessage(artifact, key, inputs = {}, options) {");
        writer.Indent();
        writer.Line("if (!artifact || artifact.artifactVersion !== 2 || artifact.catalog !== catalog || artifact.contractFingerprint !== contractFingerprint) throw new TypeError(\"A decoded locale artifact is required.\");");
        writer.Line("const ast = artifact.messages[key]; if (!ast) throw new RangeError(`Locale artifact has no message '${key}'.`);");
        writer.Line("const locale = resolveLocale(options?.locale ?? artifact.locale); if (locale !== artifact.locale) throw new RangeError(\"A dynamic locale artifact can only format its own locale.\");");
        writer.Line("const names = Object.keys(ast.inputs).sort(); validateInputs(inputs, names);");
        writer.Line("const selected = ast.selectors.map(selector => { const value = inputs[selector.input]; if (selector.function === \"plural\") return selectPlural(value, locale, false); if (selector.function === \"ordinal\") return selectPlural(value, locale, true); return String(value); });");
        writer.Line("const variant = ast.variants.find(candidate => ast.selectors.every((selector, index) => candidate.matches[selector.name] === \"*\" || candidate.matches[selector.name] === selected[index]));");
        writer.Line("if (!variant) throw new RangeError(\"The decoded message has no matching variant.\");");
        writer.Line("return hasMarkup(variant.nodes) ? localizedContent(contentNodes(variant.nodes, ast.inputs, inputs, locale)) : localized(textNodes(variant.nodes, ast.inputs, inputs, locale));");
        writer.Unindent();
        writer.Line("}");
        writer.Line("function textNodes(nodes, descriptors, inputs, locale) { let result = \"\"; for (const node of nodes) { if (node.kind === \"text\") result += node.value; else if (node.kind === \"input\") result += scalar(node.input, descriptors[node.input], descriptors[node.input].format, inputs, locale); else if (node.kind === \"format\") result += node.function === \"relativeTime\" ? formatRelativeTime(inputs, node.input, node.unit, node.numeric, locale) : scalar(node.input, descriptors[node.input], node.format, inputs, locale); else throw new TypeError(\"Markup requires structured output.\"); } return result; }");
        writer.Line("function contentNodes(nodes, descriptors, inputs, locale) { return nodes.map(node => { if (node.kind === \"markup\") return Object.freeze({ kind: \"element\", name: node.name, attributes: Object.freeze({ ...node.attributes }), children: Object.freeze(contentNodes(node.children, descriptors, inputs, locale)) }); const value = node.kind === \"text\" ? node.value : node.kind === \"input\" ? scalar(node.input, descriptors[node.input], descriptors[node.input].format, inputs, locale) : node.function === \"relativeTime\" ? formatRelativeTime(inputs, node.input, node.unit, node.numeric, locale) : scalar(node.input, descriptors[node.input], node.format, inputs, locale); return Object.freeze({ kind: \"text\", value }); }); }");
        writer.Line("function scalar(name, descriptor, format, inputs, locale) { return formatInput(inputs, name, descriptor.type, format, locale); }");
        writer.Line("function hasMarkup(nodes) { return nodes.some(node => node.kind === \"markup\" || (node.children && hasMarkup(node.children))); }");
        writer.Line("function validateAst(ast, contract) { if (Object.keys(contract).length > localePackV2Limits.maximumArgumentsPerMessage) return \"limit-exceeded\"; if (!isObject(ast)) return \"malformed-pattern\"; if (hasUnknownKeys(ast, [\"astVersion\",\"inputs\",\"selectors\",\"variants\"])) return \"unknown-member\"; if (ast.astVersion !== 2 || !hasKeys(ast, [\"astVersion\",\"inputs\",\"selectors\",\"variants\"]) || !isObject(ast.inputs) || !sameNames(ast.inputs, contract)) return \"argument-contract-mismatch\"; for (const name of Object.keys(contract)) { if (!isObject(ast.inputs[name])) return \"argument-contract-mismatch\"; if (hasUnknownKeys(ast.inputs[name], [\"type\",\"format\"])) return \"unknown-member\"; if (!hasKeys(ast.inputs[name], [\"type\",\"format\"]) || ast.inputs[name].type !== contract[name].type || ast.inputs[name].format !== contract[name].format) return \"argument-contract-mismatch\"; } if (!Array.isArray(ast.selectors) || !Array.isArray(ast.variants)) return \"malformed-pattern\"; if (ast.selectors.length > 16 || ast.variants.length < 1 || ast.variants.length > 256) return \"limit-exceeded\"; const selectorNames = new Set(); for (const selector of ast.selectors) { if (!isObject(selector)) return \"malformed-pattern\"; if (hasUnknownKeys(selector, [\"name\",\"input\",\"function\"])) return \"unknown-member\"; if (!hasKeys(selector, [\"name\",\"input\",\"function\"]) || !identifier(selector.name) || selectorNames.has(selector.name) || !selectorFunctions.has(selector.function)) return \"malformed-pattern\"; if (!Object.hasOwn(contract, selector.input)) return \"argument-contract-mismatch\"; if ((selector.function === \"plural\" || selector.function === \"ordinal\") && ![\"int\",\"number\"].includes(contract[selector.input].type)) return \"argument-contract-mismatch\"; selectorNames.add(selector.name); } let catchAll = false; for (const variant of ast.variants) { if (!isObject(variant)) return \"malformed-pattern\"; if (hasUnknownKeys(variant, [\"matches\",\"nodes\"])) return \"unknown-member\"; if (!hasKeys(variant, [\"matches\",\"nodes\"]) || !isObject(variant.matches) || !sameNames(variant.matches, Object.fromEntries([...selectorNames].map(name => [name, true]))) || !Array.isArray(variant.nodes)) return \"malformed-pattern\"; let all = true; for (const value of Object.values(variant.matches)) { if (typeof value !== \"string\" || value.length === 0) return \"malformed-pattern\"; all &&= value === \"*\"; } catchAll ||= all; const result = validateNodes(variant.nodes, contract, 0, { value: 0, textBytes: 0 }); if (result) return result; } return catchAll ? null : \"malformed-pattern\"; }");
        writer.Line("function validateNodes(nodes, contract, depth, count) { if (depth > 16 || nodes.length > 4096) return \"limit-exceeded\"; for (const node of nodes) { if (++count.value > 4096) return \"limit-exceeded\"; if (!isObject(node)) return \"malformed-pattern\"; if (node.kind === \"text\") { if (!hasKeys(node, [\"kind\",\"value\"]) || typeof node.value !== \"string\") return \"malformed-pattern\"; if ((count.textBytes += new TextEncoder().encode(node.value).byteLength) > localePackV2Limits.maximumPatternBytes) return \"limit-exceeded\"; } else if (node.kind === \"input\") { if (!hasKeys(node, [\"kind\",\"input\"])) return \"malformed-pattern\"; if (!Object.hasOwn(contract, node.input)) return \"argument-contract-mismatch\"; } else if (node.kind === \"format\") { const keys = [\"kind\",\"input\",\"function\",\"format\", ...(node.unit === undefined ? [] : [\"unit\"]), ...(node.numeric === undefined ? [] : [\"numeric\"])]; if (!hasKeys(node, keys)) return \"malformed-pattern\"; if (!Object.hasOwn(contract, node.input)) return \"argument-contract-mismatch\"; const descriptor = contract[node.input]; if (!formatFunctions.has(node.function) || typeof node.format !== \"string\") return \"malformed-pattern\"; if (node.function === \"relativeTime\") { if (![\"int\",\"number\"].includes(descriptor.type) || ![\"second\",\"minute\",\"hour\",\"day\",\"week\",\"month\",\"year\"].includes(node.unit) || ![\"always\",\"auto\"].includes(node.numeric)) return \"argument-contract-mismatch\"; } else if (!formatFunctionMatches(node.function, descriptor.type) || !formatAllowed(descriptor.type, node.format)) return \"argument-contract-mismatch\"; else if (Object.hasOwn(node, \"unit\") || Object.hasOwn(node, \"numeric\")) return \"malformed-pattern\"; } else if (node.kind === \"markup\") { if (!hasKeys(node, [\"kind\",\"name\",\"attributes\",\"children\"]) || !identifier(node.name) || !isObject(node.attributes) || !Array.isArray(node.children) || Object.entries(node.attributes).some(([name,value]) => !identifier(name) || typeof value !== \"string\")) return \"malformed-pattern\"; const result = validateNodes(node.children, contract, depth + 1, count); if (result) return result; } else return \"malformed-pattern\"; } return null; }");
        writer.Line("function formatFunctionMatches(functionName, type) { return (functionName === \"string\" && type === \"string\") || (functionName === \"integer\" && type === \"int\") || (functionName === \"number\" && type === \"number\") || (functionName === \"date\" && type === \"date\") || (functionName === \"time\" && type === \"time\") || (functionName === \"datetime\" && type === \"datetime\") || (functionName === \"uuid\" && type === \"guid\"); }");
        writer.Line("function formatAllowed(type, format) { return (type === \"string\" && format === \"none\") || (type === \"int\" && [\"plain\",\"grouped\"].includes(format)) || (type === \"number\" && [\"plain\",\"grouped\",\"fixed0\",\"fixed1\",\"fixed2\",\"fixed3\",\"fixed4\",\"fixed5\",\"fixed6\",\"percent0\",\"percent1\",\"percent2\",\"percent3\",\"percent4\"].includes(format)) || (type === \"bool\" && format === \"lower\") || ((type === \"date\" || type === \"datetime\") && [\"iso\",\"short\",\"medium\",\"long\"].includes(format)) || (type === \"time\" && [\"iso\",\"short\",\"medium\"].includes(format)) || (type === \"guid\" && [\"d\",\"n\"].includes(format)); }");
        writer.Line("function sameNames(left, right) { const a = Object.keys(left).sort(), b = Object.keys(right).sort(); return a.length === b.length && a.every((name,index) => name === b[index]); }");
        writer.Line("function hasUnknownKeys(value, names) { const allowed = new Set(names); return Object.keys(value).some(name => !allowed.has(name)); }");
        writer.Line("function hasKeys(value, names) { return sameNames(value, Object.fromEntries(names.map(name => [name, true]))); }");
        writer.Line("function identifier(value) { return typeof value === \"string\" && /^[A-Za-z_][A-Za-z0-9_]*$/.test(value); }");
        writer.Line("function isObject(value) { return typeof value === \"object\" && value !== null && !Array.isArray(value); }");
        writer.Line("function deepFreeze(value) { if (value && typeof value === \"object\" && !Object.isFrozen(value)) { for (const child of Object.values(value)) deepFreeze(child); Object.freeze(value); } return value; }");
        writer.Line("function withinJsonDepth(bytes, maximum) { let depth = 0, quoted = false, escaped = false; for (const byte of bytes) { if (quoted) { if (escaped) escaped = false; else if (byte === 92) escaped = true; else if (byte === 34) quoted = false; } else if (byte === 34) quoted = true; else if (byte === 123 || byte === 91) { if (++depth > maximum) return false; } else if (byte === 125 || byte === 93) --depth; } return true; }");
        writer.Line("function hasDuplicateJsonProperties(text) {");
        writer.Line("const scopes = [];");
        writer.Line("for (let index = 0; index < text.length; index++) {");
        writer.Line("const character = text[index];");
        writer.Line("if (character === \"{\") scopes.push({ object: true, keys: new Set() });");
        writer.Line("else if (character === \"[\") scopes.push({ object: false });");
        writer.Line("else if (character === \"}\" || character === \"]\") scopes.pop();");
        writer.Line("else if (character === \"\\\"\") {");
        writer.Line("const start = index++; let escaped = false;");
        writer.Line("for (; index < text.length; index++) { if (escaped) escaped = false; else if (text[index] === \"\\\\\") escaped = true; else if (text[index] === \"\\\"\") break; }");
        writer.Line("if (index >= text.length) return false;");
        writer.Line("let next = index + 1; while (/\\s/.test(text[next] ?? \"\")) next++;");
        writer.Line("if (text[next] !== \":\") continue;");
        writer.Line("const scope = scopes.at(-1); if (!scope?.object) continue;");
        writer.Line("const key = JSON.parse(text.slice(start, index + 1)); if (scope.keys.has(key)) return true; scope.keys.add(key);");
        writer.Line("}");
        writer.Line("}");
        writer.Line("return false;");
        writer.Line("}");
        writer.Line("function failure(reason) { return { ok: false, reason }; }");
        return writer.ToString();
    }

    private static string DynamicTypes(CompiledTextCatalog catalog)
    {
        var writer = new GenerationWriter();
        writer.Line("// <auto-generated />");
        writer.Line("import type { LocalizedContent, LocalizedString, MessageOptions } from \"./runtime.js\";");
        writer.Line("export interface LocaleArtifactV2 { readonly artifactVersion: 2; readonly messageGrammarVersion: 2; readonly catalog: " + GenerationSupport.JsonString(catalog.Id) + "; readonly locale: string; readonly contractFingerprint: " + GenerationSupport.JsonString(catalog.Fingerprint) + "; readonly messages: Readonly<Record<string, unknown>>; }");
        writer.Line("export type LocaleArtifactDecodeResult = { readonly ok: true; readonly value: LocaleArtifactV2 } | { readonly ok: false; readonly reason: string }; ");
        writer.Line("export declare function decodeLocaleArtifact(value: unknown): LocaleArtifactDecodeResult;");
        writer.Line("export declare function decodeLocalePackV2(content: Uint8Array, expectedLocale: string, integrityVerifier?: (content: Uint8Array) => boolean | Promise<boolean>): Promise<LocaleArtifactDecodeResult>;");
        writer.Line("export declare function formatDynamicMessage(artifact: LocaleArtifactV2, key: string, inputs?: Readonly<Record<string, unknown>>, options?: MessageOptions): LocalizedString | LocalizedContent;");
        return writer.ToString();
    }

    private static string PortableType(TranslationArgumentType type) => type switch
    {
        TranslationArgumentType.Int => "int64",
        TranslationArgumentType.Number => "decimal",
        TranslationArgumentType.Boolean => "bool",
        TranslationArgumentType.DateTime => "instant",
        TranslationArgumentType.Guid => "uuid",
        _ => GenerationSupport.JsonArgumentType(type),
    };

    private static string Message(CompiledTextCatalog catalog, CompiledTranslation canonical, string identifier)
    {
        IReadOnlyList<CompiledTextPlaceholder> placeholders = GenerationSupport.OrderedPlaceholders(canonical.Placeholders);
        var writer = new GenerationWriter();
        writer.Line("// <auto-generated />");
        writer.Line("import { formatInput, formatRelativeTime, localized, localizedContent, resolveLocale, selectPlural, getLocale, validateInputs } from \"../runtime.js\";");
        writer.Line("const expectedInputs = Object.freeze(" + JsonPlaceholderNames(placeholders) + ");");
        writer.Blank();
        string parameters = placeholders.Count == 0 ? "options" : "inputs, options";
        writer.Line("export function " + identifier + "(" + parameters + ") {");
        writer.Indent();
        if (placeholders.Count != 0) writer.Line("validateInputs(inputs, expectedInputs);");
        writer.Line("const locale = resolveLocale(options?.locale ?? getLocale());");
        writer.Line("switch (locale) {");
        writer.Indent();
        IReadOnlyList<CompiledTextLocale> locales = GenerationSupport.OrderedLocales(catalog.Locales);
        for (int localeIndex = 0; localeIndex < locales.Count; localeIndex++)
        {
            CompiledTranslation resource = FindResource(locales[localeIndex].ResolvedResources, canonical.Key);
            string result = canonical.Message.HasMarkup
                ? "localizedContent(" + ContentExpression(resource, placeholders) + ")"
                : "localized(" + PatternExpression(resource, placeholders) + ")";
            writer.Line("case " + GenerationSupport.JsonString(locales[localeIndex].Tag) + ": return " + result + ";");
        }
        writer.Line("default: throw new RangeError(`Unsupported locale '${locale}'.`);");
        writer.Unindent();
        writer.Line("}");
        writer.Unindent();
        writer.Line("}");
        return writer.ToString();
    }

    private static string PatternExpression(CompiledTranslation resource, IReadOnlyList<CompiledTextPlaceholder> placeholders)
    {
        if (resource.Message.IsVariant) return VariantExpression(resource.Message, placeholders);
        return NodesExpression(resource.Message, placeholders);
    }

    private static string VariantExpression(CompiledMessagePattern message, IReadOnlyList<CompiledTextPlaceholder> placeholders)
    {
        var selectors = new Dictionary<string, string>(StringComparer.Ordinal);
        for (int index = 0; index < message.Selectors.Count; index++)
        {
            CompiledMessageSelector selector = message.Selectors[index];
            string input = "inputs[" + GenerationSupport.JsonString(selector.Input) + "]";
            string expression = selector.Function switch
            {
                "plural" => "selectPlural(" + input + ", locale, false)",
                "ordinal" => "selectPlural(" + input + ", locale, true)",
                _ => "String(" + input + ")",
            };
            selectors[selector.Name] = expression;
        }
        string fallback = "\"\"";
        for (int index = message.Variants.Count - 1; index >= 0; index--)
        {
            CompiledMessageVariant variant = message.Variants[index];
            var conditions = new List<string>();
            foreach (KeyValuePair<string, string> match in variant.Matches)
                if (match.Value != "*") conditions.Add("(" + selectors[match.Key] + " === " + GenerationSupport.JsonString(match.Value) + ")");
            string value = NodesExpression(variant.Pattern, placeholders);
            if (conditions.Count == 0) fallback = value;
            else fallback = "(" + string.Join(" && ", conditions) + " ? " + value + " : " + fallback + ")";
        }
        return fallback;
    }

    private static string NodesExpression(CompiledMessagePattern pattern, IReadOnlyList<CompiledTextPlaceholder> placeholders)
    {
        if (pattern.Nodes.Count == 0) return "\"\"";
        var parts = new List<string>(pattern.Nodes.Count);
        for (int index = 0; index < pattern.Nodes.Count; index++)
        {
            CompiledMessageNode node = pattern.Nodes[index];
            if (node is CompiledMessageText text)
            {
                parts.Add(GenerationSupport.JsonString(text.Value));
            }
            else if (node is CompiledMessageInput input)
            {
                CompiledTextPlaceholder placeholder = FindPlaceholder(placeholders, input.Name);
                parts.Add("formatInput(inputs, " + GenerationSupport.JsonString(input.Name) + ", " +
                    GenerationSupport.JsonString(GenerationSupport.JsonArgumentType(placeholder.Type)) + ", " +
                    GenerationSupport.JsonString(placeholder.Format) + ", locale)");
            }
            else if (node is CompiledMessageFormat format)
            {
                CompiledTextPlaceholder placeholder = FindPlaceholder(placeholders, format.Input);
                if (format.Function == "relativeTime")
                    parts.Add("formatRelativeTime(inputs, " + GenerationSupport.JsonString(format.Input) + ", " +
                        GenerationSupport.JsonString(format.Unit!) + ", " + GenerationSupport.JsonString(format.Numeric!) + ", locale)");
                else
                    parts.Add("formatInput(inputs, " + GenerationSupport.JsonString(format.Input) + ", " +
                        GenerationSupport.JsonString(GenerationSupport.JsonArgumentType(placeholder.Type)) + ", " +
                        GenerationSupport.JsonString(format.Format) + ", locale)");
            }
        }
        return string.Join(" + ", parts);
    }

    private static string ContentExpression(CompiledTranslation resource, IReadOnlyList<CompiledTextPlaceholder> placeholders)
    {
        if (!resource.Message.IsVariant) return ContentNodes(resource.Message.Nodes, placeholders);
        var selectors = new Dictionary<string, string>(StringComparer.Ordinal);
        for (int index = 0; index < resource.Message.Selectors.Count; index++)
        {
            CompiledMessageSelector selector = resource.Message.Selectors[index];
            string input = "inputs[" + GenerationSupport.JsonString(selector.Input) + "]";
            selectors[selector.Name] = selector.Function switch
            {
                "plural" => "selectPlural(" + input + ", locale, false)",
                "ordinal" => "selectPlural(" + input + ", locale, true)",
                _ => "String(" + input + ")",
            };
        }
        string fallback = "[]";
        for (int index = resource.Message.Variants.Count - 1; index >= 0; index--)
        {
            CompiledMessageVariant variant = resource.Message.Variants[index];
            var conditions = new List<string>();
            foreach (KeyValuePair<string, string> match in variant.Matches)
                if (match.Value != "*") conditions.Add("(" + selectors[match.Key] + " === " + GenerationSupport.JsonString(match.Value) + ")");
            string value = ContentNodes(variant.Pattern.Nodes, placeholders);
            fallback = conditions.Count == 0 ? value : "(" + string.Join(" && ", conditions) + " ? " + value + " : " + fallback + ")";
        }
        return fallback;
    }

    private static string ContentNodes(IReadOnlyList<CompiledMessageNode> nodes, IReadOnlyList<CompiledTextPlaceholder> placeholders)
    {
        var result = new List<string>(nodes.Count);
        for (int index = 0; index < nodes.Count; index++)
        {
            CompiledMessageNode node = nodes[index];
            if (node is CompiledMessageText text)
                result.Add("Object.freeze({ kind: \"text\", value: " + GenerationSupport.JsonString(text.Value) + " })");
            else if (node is CompiledMessageInput input)
            {
                CompiledTextPlaceholder placeholder = FindPlaceholder(placeholders, input.Name);
                string value = "formatInput(inputs, " + GenerationSupport.JsonString(input.Name) + ", " +
                    GenerationSupport.JsonString(GenerationSupport.JsonArgumentType(placeholder.Type)) + ", " +
                    GenerationSupport.JsonString(placeholder.Format) + ", locale)";
                result.Add("Object.freeze({ kind: \"text\", value: " + value + " })");
            }
            else if (node is CompiledMessageFormat format)
            {
                CompiledTextPlaceholder placeholder = FindPlaceholder(placeholders, format.Input);
                string value = format.Function == "relativeTime"
                    ? "formatRelativeTime(inputs, " + GenerationSupport.JsonString(format.Input) + ", " + GenerationSupport.JsonString(format.Unit!) + ", " + GenerationSupport.JsonString(format.Numeric!) + ", locale)"
                    : "formatInput(inputs, " + GenerationSupport.JsonString(format.Input) + ", " + GenerationSupport.JsonString(GenerationSupport.JsonArgumentType(placeholder.Type)) + ", " + GenerationSupport.JsonString(format.Format) + ", locale)";
                result.Add("Object.freeze({ kind: \"text\", value: " + value + " })");
            }
            else if (node is CompiledMessageMarkup markup)
            {
                var attributes = new StringBuilder("{");
                int count = 0;
                foreach (KeyValuePair<string, string> attribute in markup.Attributes)
                {
                    if (count++ != 0) attributes.Append(',');
                    attributes.Append(GenerationSupport.JsonString(attribute.Key)).Append(':').Append(GenerationSupport.JsonString(attribute.Value));
                }
                attributes.Append('}');
                result.Add("Object.freeze({ kind: \"element\", name: " + GenerationSupport.JsonString(markup.Name) +
                    ", attributes: Object.freeze(" + attributes + "), children: Object.freeze(" + ContentNodes(markup.Children, placeholders) + ") })");
            }
        }
        return "[" + string.Join(",", result) + "]";
    }

    private static string MessageNamespaceIndex(IReadOnlyList<MessageModule> modules)
    {
        var writer = new GenerationWriter();
        writer.Line("// <auto-generated />");
        for (int index = 0; index < modules.Count; index++)
            writer.Line("export { " + modules[index].Identifier + " as " + ExportName(modules[index].Resource.Key) +
                " } from \"./" + modules[index].FileName + "\";");
        return writer.ToString();
    }

    private static string MessagesIndex()
    {
        var writer = new GenerationWriter();
        writer.Line("// <auto-generated />");
        writer.Line("export * as m from \"./messages/_index.js\";");
        return writer.ToString();
    }

    private static string MessagesTypes(IReadOnlyList<MessageModule> modules)
    {
        var writer = new GenerationWriter();
        writer.Line("// <auto-generated />");
        writer.Line("import type { LocalizedContent, LocalizedString, MessageOptions } from \"./runtime.js\";");
        writer.Blank();
        writer.Line("export declare const m: Readonly<{");
        writer.Indent();
        for (int index = 0; index < modules.Count; index++)
        {
            MessageModule module = modules[index];
            WriteDocumentation(writer, module.Resource);
            IReadOnlyList<CompiledTextPlaceholder> placeholders = GenerationSupport.OrderedPlaceholders(module.Resource.Placeholders);
            if (placeholders.Count == 0)
            {
                writer.Line("readonly " + PropertyName(module.Resource.Key) + ": (options?: MessageOptions) => " +
                    (module.Resource.ProducesStructuredContent ? "LocalizedContent" : "LocalizedString") + ";");
                continue;
            }
            writer.Line("readonly " + PropertyName(module.Resource.Key) + ": (inputs: Readonly<{");
            writer.Indent();
            for (int placeholderIndex = 0; placeholderIndex < placeholders.Count; placeholderIndex++)
            {
                CompiledTextPlaceholder placeholder = placeholders[placeholderIndex];
                writer.Line("readonly " + placeholder.Name + ": " + EsmType(placeholder.Type) + ";");
            }
            writer.Unindent();
            writer.Line("}>, options?: MessageOptions) => " + (module.Resource.ProducesStructuredContent ? "LocalizedContent" : "LocalizedString") + ";");
        }
        writer.Unindent();
        writer.Line("}>;");
        return writer.ToString();
    }

    private static TranslationGeneratedOutput WebModuleManifest(
        CompiledTextCatalog catalog,
        List<TranslationGeneratedOutput> outputs)
    {
        var ordered = new List<TranslationGeneratedOutput>(outputs.Count);
        for (int index = 0; index < outputs.Count; index++) ordered.Add(outputs[index]);
        ordered.Sort(static (left, right) => StringComparer.Ordinal.Compare(left.RelativePath, right.RelativePath));
        string root = catalog.Id + ".esm/";
        var json = new StringBuilder();
        json.Append("{\"webModuleManifestVersion\":1,\"esmAbiVersion\":")
            .Append(TranslationOutputRenderer.EsmAbiVersion)
            .Append(",\"catalog\":").Append(GenerationSupport.JsonString(catalog.Id))
            .Append(",\"contractFingerprint\":").Append(GenerationSupport.JsonString(catalog.Fingerprint))
            .Append(",\"entrypoints\":{\"messages\":\"messages.js\",\"types\":\"messages.d.ts\",\"runtime\":\"runtime.js\",\"server\":\"server.js\",\"dynamic\":\"dynamic.js\"},\"assets\":[");
        for (int index = 0; index < ordered.Count; index++)
        {
            if (index != 0) json.Append(',');
            TranslationGeneratedOutput output = ordered[index];
            string path = output.RelativePath.StartsWith(root, StringComparison.Ordinal)
                ? output.RelativePath.Substring(root.Length)
                : output.RelativePath;
            json.Append("{\"path\":").Append(GenerationSupport.JsonString(path))
                .Append(",\"sha256\":").Append(GenerationSupport.JsonString(output.Sha256.Substring("sha256:".Length)))
                .Append(",\"byteLength\":").Append(output.GetUtf8Bytes().Length)
                .Append(",\"mediaType\":").Append(GenerationSupport.JsonString(output.MediaType)).Append('}');
        }
        json.Append("]}");
        return Output(
            TranslationGeneratedOutputKind.WebModuleManifestJson,
            root + "web-module-manifest-v1.json",
            "application/json",
            json.ToString());
    }

    private static CompiledTranslation FindResource(IReadOnlyList<CompiledTranslation> resources, string key)
    {
        for (int index = 0; index < resources.Count; index++)
            if (string.Equals(resources[index].Key, key, StringComparison.Ordinal)) return resources[index];
        throw new InvalidOperationException("Resolved locale does not contain canonical key '" + key + "'.");
    }

    private static CompiledTextPlaceholder FindPlaceholder(IReadOnlyList<CompiledTextPlaceholder> placeholders, string name)
    {
        for (int index = 0; index < placeholders.Count; index++)
            if (string.Equals(placeholders[index].Name, name, StringComparison.Ordinal)) return placeholders[index];
        throw new InvalidOperationException("Compiled message input '" + name + "' has no descriptor.");
    }

    private static string MessageIdentifier(string key) => "m$" + key.Replace('.', '$');

    private static string MessageFileName(string key) => MessageIdentifier(key) + ".js";

    private static string ExportName(string key) => IsJavaScriptIdentifier(key) && key != "default"
        ? key
        : GenerationSupport.JsonString(key);

    private static string PropertyName(string key) => IsJavaScriptIdentifier(key)
        ? key
        : GenerationSupport.JsonString(key);

    private static bool IsJavaScriptIdentifier(string value)
    {
        if (value.Length == 0 || !IsStart(value[0])) return false;
        for (int index = 1; index < value.Length; index++)
            if (!IsStart(value[index]) && !char.IsAsciiDigit(value[index])) return false;
        return true;

        static bool IsStart(char value) => char.IsAsciiLetter(value) || value is '_' or '$';
    }

    private static string JsonLocales(IReadOnlyList<CompiledTextLocale> locales)
    {
        IReadOnlyList<CompiledTextLocale> ordered = GenerationSupport.OrderedLocales(locales);
        var builder = new StringBuilder("[");
        for (int index = 0; index < ordered.Count; index++)
        {
            if (index != 0) builder.Append(',');
            builder.Append(GenerationSupport.JsonString(ordered[index].Tag));
        }
        return builder.Append(']').ToString();
    }

    private static string LocaleUnion(IReadOnlyList<CompiledTextLocale> locales)
    {
        IReadOnlyList<CompiledTextLocale> ordered = GenerationSupport.OrderedLocales(locales);
        var values = new string[ordered.Count];
        for (int index = 0; index < ordered.Count; index++) values[index] = GenerationSupport.JsonString(ordered[index].Tag);
        return string.Join(" | ", values);
    }

    private static string JsonPlaceholderNames(IReadOnlyList<CompiledTextPlaceholder> placeholders)
    {
        var builder = new StringBuilder("[");
        for (int index = 0; index < placeholders.Count; index++)
        {
            if (index != 0) builder.Append(',');
            builder.Append(GenerationSupport.JsonString(placeholders[index].Name));
        }
        return builder.Append(']').ToString();
    }

    private static string EsmType(TranslationArgumentType type) => type switch
    {
        TranslationArgumentType.Int => "number | bigint",
        TranslationArgumentType.Number => "number",
        TranslationArgumentType.Boolean => "boolean",
        _ => "string",
    };

    private static void WriteDocumentation(GenerationWriter writer, CompiledTranslation resource)
    {
        writer.Line("/** Key: " + SafeComment(resource.Key));
        if (resource.Description is not null) writer.Line(" * " + SafeComment(resource.Description));
        if (resource.DeprecatedReason is not null) writer.Line(" * @deprecated " + SafeComment(resource.DeprecatedReason));
        writer.Line(" */");
    }

    private static string SafeComment(string value) => value
        .Replace("\r\n", " ", StringComparison.Ordinal)
        .Replace('\r', ' ')
        .Replace('\n', ' ')
        .Replace("*/", "* /", StringComparison.Ordinal);

    private static TranslationGeneratedOutput Output(
        TranslationGeneratedOutputKind kind,
        string path,
        string mediaType,
        string text) => new(kind, path, mediaType, text);

    private sealed class MessageModule
    {
        internal MessageModule(CompiledTranslation resource, string identifier, string fileName)
        {
            Resource = resource;
            Identifier = identifier;
            FileName = fileName;
        }

        internal CompiledTranslation Resource { get; }
        internal string Identifier { get; }
        internal string FileName { get; }
    }
}
