using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;

namespace Runic.Translations.Compiler.Generation;

// ESM backend over the selected typed RMF2 carrier.
internal static class Rmf2EsmOutputRendererV5
{
    internal static IReadOnlyList<TranslationGeneratedOutput> Render(Rmf2ProjectV5 project)
    {
        string root = project.Id + ".esm-v5/";
        var messages = project.CanonicalMessages.OrderBy(item => item.Key, StringComparer.Ordinal).ToArray();
        var outputs = new List<TranslationGeneratedOutput>(messages.Length + 10)
        {
            Output(TranslationGeneratedOutputKind.EsmRuntime, root + "runtime.js", "text/javascript", Runtime(project)),
            Output(TranslationGeneratedOutputKind.EsmRuntimeTypes, root + "runtime.d.ts", "text/typescript", RuntimeTypes(project)),
            Output(TranslationGeneratedOutputKind.EsmTransport, root + "transport.js", "text/javascript", Transport(project)),
            Output(TranslationGeneratedOutputKind.EsmTransportTypes, root + "transport.d.ts", "text/typescript", TransportTypes(project)),
            Output(TranslationGeneratedOutputKind.EsmDynamic, root + "dynamic.js", "text/javascript", Dynamic()),
            Output(TranslationGeneratedOutputKind.EsmDynamicTypes, root + "dynamic.d.ts", "text/typescript", DynamicTypes(project)),
            Output(TranslationGeneratedOutputKind.EsmServer, root + "server.js", "text/javascript", Server()),
            Output(TranslationGeneratedOutputKind.EsmServerTypes, root + "server.d.ts", "text/typescript", ServerTypes()),
        };
        foreach (Rmf2MessageContractV5 message in messages)
            outputs.Add(Output(TranslationGeneratedOutputKind.EsmMessage, root + "messages/" + FileName(message.Key),
                "text/javascript", Message(project, message)));
        outputs.Add(Output(TranslationGeneratedOutputKind.EsmMessageNamespace, root + "messages/_index.js",
            "text/javascript", Namespace(messages)));
        outputs.Add(Output(TranslationGeneratedOutputKind.EsmMessagesIndex, root + "messages.js",
            "text/javascript", "// <auto-generated />\nexport { m } from \"./messages/_index.js\";\n"));
        outputs.Add(Output(TranslationGeneratedOutputKind.EsmMessagesTypes, root + "messages.d.ts",
            "text/typescript", MessageTypes(project, messages)));
        outputs.Add(Manifest(project, outputs, root));
        outputs.Sort(static (left, right) => StringComparer.Ordinal.Compare(left.RelativePath, right.RelativePath));
        return outputs;
    }

    private static string Runtime(Rmf2ProjectV5 project)
    {
        var writer = new GenerationWriter();
        writer.Line("// <auto-generated />");
        writer.Line("export const esmAbiVersion = " + TranslationOutputRenderer.EsmAbiVersion + ";");
        writer.Line("export const rmf2RuntimeAbiVersion = " + Rmf2ProjectV5.RuntimeAbiVersion + ";");
        writer.Line("export const messageGrammarVersion = " + Rmf2ProjectV5.MessageGrammarVersion + ";");
        writer.Line("export const profile = " + GenerationSupport.JsonString(Rmf2ProjectV5.Profile) + ";");
        writer.Line("export const generatedNameVersion = " + Rmf2GeneratedNamesV1.Version + ";");
        writer.Line("export const catalog = " + GenerationSupport.JsonString(project.Id) + ";");
        writer.Line("export const contractFingerprint = " + GenerationSupport.JsonString(project.CallerFingerprint) + ";");
        writer.Line("export const sourceHash = " + GenerationSupport.JsonString(project.SourceHash) + ";");
        writer.Line("export const baseLocale = " + GenerationSupport.JsonString(project.DefaultLocale) + ";");
        writer.Line("export const locales = Object.freeze(" + JsonSerializer.Serialize(project.Locales.Select(item => item.Tag).OrderBy(item => item, StringComparer.Ordinal)) + ");");
        writer.Line("const unsupportedLocalePolicy = " + GenerationSupport.JsonString(project.UnsupportedLocale.ToString()) + ";");
        writer.Line("const generatedLocaleData = " + TranslationCapabilityRegistry.EsmLocaleDataJson + ";");
        writer.Line("export const rmf2Contract = freezeTrusted(JSON.parse(" + GenerationSupport.JsonString(project.MarkupContract) + "));");
        writer.Line("export const messageContracts = freezeTrusted(JSON.parse(" + GenerationSupport.JsonString(ContractsJson(project, includeExtras: true)) + "));");
        using Stream stream = typeof(Rmf2EsmOutputRendererV5).Assembly.GetManifestResourceStream("Runic.Translations.Compiler.Generation.Rmf2EsmRuntimeV5.js")!;
        using var reader = new StreamReader(stream);
        writer.Line(reader.ReadToEnd());
        return writer.ToString();
    }

    private static string ContractsJson(Rmf2ProjectV5 project, bool includeExtras)
    {
        using var stream = new MemoryStream();
        using (var writer = new Utf8JsonWriter(stream))
        {
            writer.WriteStartObject();
            IEnumerable<Rmf2MessageContractV5> messages = includeExtras
                ? project.CanonicalMessages.Concat(project.ExtraMessages)
                : project.CanonicalMessages;
            foreach (Rmf2MessageContractV5 message in messages.OrderBy(item => item.Key, StringComparer.Ordinal))
            {
                writer.WriteStartObject(message.Key); writer.WriteBoolean("structured", message.Structured); writer.WriteStartArray("inputs");
                foreach (Rmf2InputV5 input in message.Inputs) { writer.WriteStartObject(); writer.WriteString("name", input.Name); writer.WriteString("type", input.Type); writer.WriteEndObject(); }
                writer.WriteEndArray(); writer.WriteEndObject();
            }
            writer.WriteEndObject();
        }
        return Encoding.UTF8.GetString(stream.ToArray());
    }

    private static string Message(Rmf2ProjectV5 project, Rmf2MessageContractV5 contract)
    {
        var writer = new GenerationWriter();
        writer.Line("// <auto-generated />");
        writer.Line("import { formatCompiledMessage, freezeGeneratedMessage, getLocale, resolveLocale } from \"../runtime.js\";");
        writer.Line("const messages = Object.freeze(Object.assign(Object.create(null), {"); writer.Indent();
        foreach (Rmf2LocaleV5 locale in project.Locales.OrderBy(item => item.Tag, StringComparer.Ordinal))
        {
            Rmf2TranslationV5 resource = locale.ResolvedResources.Single(item => item.Key == contract.Key);
            string wrapper = "{\"contentLocale\":" + GenerationSupport.JsonString(resource.ContentLocale) + ",\"ast\":" +
                Rmf2MessageJsonV5.Serialize(resource.Message with { Inputs = contract.Inputs }) + "}";
            writer.Line(GenerationSupport.JsonString(locale.Tag) + ": freezeGeneratedMessage(" + GenerationSupport.JsonString(contract.Key) + ", JSON.parse(" + GenerationSupport.JsonString(wrapper) + ")), ");
        }
        writer.Unindent(); writer.Line("}));");
        string identifier = Rmf2GeneratedNamesV1.Identifier(contract.Key);
        writer.Line("export function " + identifier + "(" + (contract.Inputs.Count == 0 ? "options" : "inputs, options") + ") {"); writer.Indent();
        if (contract.Inputs.Count == 0) writer.Line("const inputs = Object.create(null);");
        writer.Line("const locale = resolveLocale(options?.locale ?? getLocale());");
        writer.Line("return formatCompiledMessage(" + GenerationSupport.JsonString(contract.Key) + ", messages[locale], inputs, locale);");
        writer.Unindent(); writer.Line("}");
        return writer.ToString();
    }

    private static string Namespace(IReadOnlyList<Rmf2MessageContractV5> messages)
    {
        var writer = new GenerationWriter(); writer.Line("// <auto-generated />");
        foreach (Rmf2MessageContractV5 message in messages)
            writer.Line("import { " + Rmf2GeneratedNamesV1.Identifier(message.Key) + " } from \"./" + FileName(message.Key) + "\";");
        writer.Line("const values = Object.create(null);");
        foreach (Rmf2MessageContractV5 message in messages)
            writer.Line("Object.defineProperty(values, " + GenerationSupport.JsonString(message.Key) + ", { value: " + Rmf2GeneratedNamesV1.Identifier(message.Key) + ", enumerable: true });");
        writer.Line("export const m = Object.freeze(values);");
        return writer.ToString();
    }

    private static string RuntimeTypes(Rmf2ProjectV5 project) => """
        // <auto-generated />
        export declare const esmAbiVersion: 4;
        export declare const rmf2RuntimeAbiVersion: 2;
        export declare const messageGrammarVersion: 5;
        export declare const profile: "rmf2-execution-v2";
        export declare const generatedNameVersion: 1;
        export declare const catalog: string;
        export declare const contractFingerprint: string;
        export declare const sourceHash: string;
        export type Rmf2Decimal = Readonly<{ readonly coefficient: bigint; readonly scale: number; readonly negative: boolean }>;
        export type Rmf2Input = string | boolean | bigint | number | Rmf2Decimal;
        export type MessageOptions = Readonly<{ locale?: string }>;
        export type Rmf2Annotation = Readonly<{ name: string; value?: string | Rmf2Decimal }>;
        export type LocalizedContentNode = Readonly<{ kind: "text"; value: string; annotations: readonly Rmf2Annotation[] } | { kind: "element"; name: string; attributes: Readonly<Record<string,string>>; annotations: readonly Rmf2Annotation[]; closingAnnotations: readonly Rmf2Annotation[]; standalone: boolean; occurrence: string; children: readonly LocalizedContentNode[] }>;
        export type LocalizedContent<Slots extends Record<string,string> = Record<string,string>> = Readonly<{ readonly __slots?: Slots; kind: "localized-content"; key: string; locale: string; nodes: readonly LocalizedContentNode[] }>;
        export type LinkBinding = Readonly<{ kind: "runic:link"; href: string }>;
        export type ActionBinding = Readonly<{ kind: "runic:action"; onActivate: () => void }>;
        export type IconBinding = Readonly<{ kind: "runic:icon"; asset: unknown; decorative: boolean; accessibleName?: (locale: string) => string }>;
        export type SlotBindings<S extends Record<string,string>> = { readonly [K in keyof S]: S[K] extends "runic:link" ? LinkBinding : S[K] extends "runic:action" ? ActionBinding : IconBinding };
        export interface MarkupOption { readonly type: "string" | "enum" | "number" | "boolean"; readonly values?: readonly string[]; readonly default?: string; readonly literalOnly?: boolean; }
        export interface MarkupContract { readonly name: string; readonly kind: "paired" | "standalone"; readonly children: "inline" | "none"; readonly interactive: boolean; readonly plainText: "children" | "lineBreak" | "alternateText" | "explicit" | "omit"; readonly options?: Readonly<Record<string,MarkupOption>>; }
        export interface InlineElement<T> { readonly name: string; readonly children: readonly T[]; readonly options: Readonly<Record<string,string>>; readonly binding?: LinkBinding | ActionBinding | IconBinding; readonly occurrence: string; readonly locale: string; readonly standalone: boolean; }
        export interface MarkupBinding<T> { readonly contract: MarkupContract; readonly render: (element: InlineElement<T>) => T; }
        export interface InlineRenderer<T> { render<S extends Record<string,string>>(content: LocalizedContent<S>, options: { slots: SlotBindings<S> }): readonly T[]; extend(bindings: readonly MarkupBinding<T>[]): InlineRenderer<T>; }
        export declare const baseLocale: string;
        export declare const locales: readonly string[];
        export declare function decimal(value: string): Rmf2Decimal;
        export declare function resolveLocale(locale: string): string;
        export declare function getLocale(): string;
        export declare function configureLocaleResolver(resolver: () => string): () => void;
        export declare function createLocaleSource(options?: { initialLocale?: string }): Readonly<{ getLocale(): string; setLocale(locale: string): void; subscribe(listener: (locale: string) => void): () => void }>;
        export declare function linkBinding(options: { href: string }): LinkBinding;
        export declare function actionBinding(options: { onActivate: () => void }): ActionBinding;
        export declare function iconBinding(options: { asset: unknown; decorative: true } | { asset: unknown; decorative: false; accessibleName: (locale: string) => string }): IconBinding;
        export declare function enumOption(values: readonly string[], defaultValue?: string): MarkupOption;
        export declare function defineMarkup(contract: MarkupContract): MarkupContract;
        export declare function bindMarkup<T>(contract: MarkupContract, render: (element: InlineElement<T>) => T): MarkupBinding<T>;
        export declare function createInlineRenderer<T>(factory: { text(value: string): T; element(element: InlineElement<T>): T }, bindings?: readonly MarkupBinding<T>[]): InlineRenderer<T>;
        export declare function toPlainText<S extends Record<string,string>>(content: LocalizedContent<S>, options: { slots: SlotBindings<S>; allowActionLabels?: boolean; annotateLinkDestinations?: boolean; custom?: readonly MarkupBinding<string>[] }): string;
        export declare function createDomInlineRenderer(document: Document, bindings?: readonly MarkupBinding<Node>[]): InlineRenderer<Node>;
        """;

    private static string MessageTypes(Rmf2ProjectV5 project, IReadOnlyList<Rmf2MessageContractV5> messages)
    {
        var writer = new GenerationWriter(); writer.Line("// <auto-generated />");
        writer.Line("import type { LocalizedContent, MessageOptions, Rmf2Decimal } from \"./runtime.js\";");
        writer.Line("export declare const m: Readonly<{"); writer.Indent();
        foreach (Rmf2MessageContractV5 message in messages)
        {
            if (message.Inputs.Count == 0)
            {
                writer.Line("readonly " + GenerationSupport.JsonString(message.Key) + ": (options?: MessageOptions) => " + ResultType(message) + ";");
                continue;
            }
            writer.Line("readonly " + GenerationSupport.JsonString(message.Key) + ": (inputs: Readonly<{"); writer.Indent();
            foreach (Rmf2InputV5 input in message.Inputs)
                writer.Line("readonly " + GenerationSupport.JsonString(input.Name) + ": " + TypeScriptType(input.Type) + ";");
            writer.Unindent(); writer.Line("}>, options?: MessageOptions) => " + ResultType(message) + ";");
        }
        writer.Unindent(); writer.Line("}>;"); return writer.ToString();
    }

    private static string TypeScriptType(string type) => type switch
    {
        "string" or "date" or "time" or "datetime" or "guid" => "string",
        "boolean" => "boolean", "int64" => "bigint | number", "decimal" => "Rmf2Decimal | string",
        _ => throw new InvalidOperationException("Unknown RMF2 v5 input type."),
    };

    private static string ResultType(Rmf2MessageContractV5 message)
    {
        if (!message.Structured) return "string";
        string slots = string.Join("; ", message.Slots.OrderBy(item => item.Key, StringComparer.Ordinal)
            .Select(item => "readonly " + GenerationSupport.JsonString(item.Key) + ": " + GenerationSupport.JsonString(item.Value.Kind)));
        return "LocalizedContent<{ " + slots + " }>";
    }

    private static string Dynamic() => """
        // <auto-generated />
        import { decodeLocaleArtifactV5, decodeLocalePackV5, formatDynamicMessageV5 } from "./runtime.js";
        export const decodeLocaleArtifact = decodeLocaleArtifactV5;
        export const decodeLocalePack = decodeLocalePackV5;
        export const formatDynamicMessage = formatDynamicMessageV5;
        """;

    private static string DynamicTypes(Rmf2ProjectV5 project) => """
        // <auto-generated />
        import type { LocalizedContent, MessageOptions, Rmf2Input } from "./runtime.js";
        export interface LocaleArtifactV5 { readonly artifactVersion: 5; readonly messageGrammarVersion: 5; readonly profile: "rmf2-execution-v2"; readonly catalog: string; readonly locale: string; readonly contractFingerprint: string; readonly messages: Readonly<Record<string, unknown>>; readonly markupContract: Readonly<Record<string, unknown>>; }
        export type DecodeResult = { readonly ok: true; readonly value: LocaleArtifactV5 } | { readonly ok: false; readonly reason: string };
        export declare function decodeLocaleArtifact(value: unknown): DecodeResult;
        export declare function decodeLocalePack(content: Uint8Array, expectedLocale: string, integrityVerifier?: (content: Uint8Array) => boolean | Promise<boolean>): Promise<DecodeResult>;
        export declare function formatDynamicMessage(artifact: LocaleArtifactV5, key: string, inputs?: Readonly<Record<string, Rmf2Input>>, options?: MessageOptions): string | LocalizedContent;
        """;

    private static string Transport(Rmf2ProjectV5 project)
    {
        var writer = new GenerationWriter(); writer.Line("// <auto-generated />");
        writer.Line("import { decodeWireValue, freezeOwnRecord } from \"./runtime.js\";");
        writer.Line("const catalog = " + GenerationSupport.JsonString(project.Id) + ";");
        writer.Line("const contractFingerprint = " + GenerationSupport.JsonString(project.CallerFingerprint) + ";");
        writer.Line("const contracts = JSON.parse(" + GenerationSupport.JsonString(ContractsJson(project, includeExtras: false)) + ");");
        writer.Line("export function decodeTextReference(value) {"); writer.Indent();
        writer.Line("if (!value || typeof value !== \"object\" || Array.isArray(value)) return failure(\"unsupported-version\");");
        writer.Line("try {"); writer.Indent();
        writer.Line("const names = Object.keys(value).sort(); const fallbackPresent = names.includes(\"fallbackText\"); const expectedMembers = [\"arguments\",\"catalog\",\"contractFingerprint\",...(fallbackPresent ? [\"fallbackText\"] : []),\"key\",\"version\"].sort(); if (names.length !== expectedMembers.length || names.some((name,index) => name !== expectedMembers[index])) return failure(\"malformed\");");
        writer.Line("const version = value.version, wireCatalog = value.catalog, wireFingerprint = value.contractFingerprint, key = value.key, argumentsValue = value.arguments, fallbackText = fallbackPresent ? value.fallbackText : undefined;");
        writer.Line("if (version !== 1) return failure(\"unsupported-version\"); if (wireCatalog !== catalog) return failure(\"catalog-mismatch\"); if (wireFingerprint !== contractFingerprint) return failure(\"fingerprint-mismatch\");");
        writer.Line("if (typeof key !== \"string\" || !Object.hasOwn(contracts, key)) return failure(\"unknown-key\");");
        writer.Line("const contract = contracts[key].inputs; if (!argumentsValue || typeof argumentsValue !== \"object\" || Array.isArray(argumentsValue)) return failure(\"invalid-arguments\");");
        writer.Line("const argumentNames = Object.keys(argumentsValue).sort(); const expectedArguments = contract.map(item => item.name).sort(); if (argumentNames.length !== expectedArguments.length || argumentNames.some((name,index) => name !== expectedArguments[index])) return failure(\"invalid-arguments\");");
        writer.Line("const entries = []; for (const item of contract) { const wireValue = argumentsValue[item.name]; const decoded = decodeWireValue(wireValue, item.type); if (!decoded.ok) return failure(`invalid-argument:${item.name}`); entries.push([item.name, decoded.value]); }");
        writer.Line("if (fallbackPresent && (typeof fallbackText !== \"string\" || fallbackText.length > 65536)) return failure(\"invalid-fallback\");");
        writer.Line("return Object.freeze({ ok: true, value: Object.freeze({ version: 1, catalog, contractFingerprint, key, arguments: freezeOwnRecord(entries), fallbackText }) });");
        writer.Unindent(); writer.Line("} catch { return failure(\"malformed\"); }");
        writer.Unindent(); writer.Line("}");
        writer.Line("export function formatTextReference(reference, handlers, options) { if (!handlers || typeof handlers !== \"object\" || !Object.hasOwn(handlers, reference.key) || typeof handlers[reference.key] !== \"function\") { if (reference.fallbackText !== undefined) return reference.fallbackText; throw new RangeError(`No text-reference handler for '${reference.key}'.`); } return handlers[reference.key](reference.arguments, options); }");
        writer.Line("function failure(reason) { return Object.freeze({ ok: false, reason }); }"); return writer.ToString();
    }

    private static string TransportTypes(Rmf2ProjectV5 project) => """
        // <auto-generated />
        import type { LocalizedContent, MessageOptions, Rmf2Decimal } from "./runtime.js";
        export interface TextReferenceWire { readonly version: 1; readonly catalog: string; readonly contractFingerprint: string; readonly key: string; readonly arguments: Readonly<Record<string, string | boolean>>; readonly fallbackText?: string; }
        export interface DecodedTextReference { readonly version: 1; readonly catalog: string; readonly contractFingerprint: string; readonly key: string; readonly arguments: Readonly<Record<string, string | boolean | bigint | Rmf2Decimal>>; readonly fallbackText?: string; }
        export type DecodeResult = { readonly ok: true; readonly value: DecodedTextReference } | { readonly ok: false; readonly reason: string };
        export declare function decodeTextReference(value: unknown): DecodeResult;
        export declare function formatTextReference(reference: DecodedTextReference, handlers: Readonly<Record<string,(inputs: Readonly<Record<string,unknown>>, options?: MessageOptions) => string | LocalizedContent>>, options?: MessageOptions): string | LocalizedContent;
        """;

    private static string Server() => """
        // <auto-generated />
        import { AsyncLocalStorage } from "node:async_hooks";
        import { baseLocale, configureLocaleResolver, resolveLocale } from "./runtime.js";
        const storage = new AsyncLocalStorage();
        configureLocaleResolver(() => storage.getStore() ?? baseLocale);
        export function runWithLocale(locale, operation) { if (typeof operation !== "function") throw new TypeError("A request operation is required."); return storage.run(resolveLocale(locale), operation); }
        export function getRequestLocale() { return storage.getStore() ?? baseLocale; }
        """;

    private static string ServerTypes() => """
        // <auto-generated />
        export declare function runWithLocale<T>(locale: string, operation: () => T): T;
        export declare function getRequestLocale(): string;
        """;

    private static TranslationGeneratedOutput Manifest(Rmf2ProjectV5 project, List<TranslationGeneratedOutput> outputs, string root)
    {
        var ordered = outputs.OrderBy(item => item.RelativePath, StringComparer.Ordinal).ToArray();
        var json = new StringBuilder("{\"webModuleManifestVersion\":" + TranslationOutputRenderer.WebModuleManifestVersion + ",\"esmAbiVersion\":" + TranslationOutputRenderer.EsmAbiVersion + ",\"rmf2RuntimeAbiVersion\":2,\"messageGrammarVersion\":5,\"profile\":\"rmf2-execution-v2\",\"generatedNameVersion\":1,\"catalog\":")
            .Append(GenerationSupport.JsonString(project.Id)).Append(",\"contractFingerprint\":").Append(GenerationSupport.JsonString(project.CallerFingerprint))
            .Append(",\"sourceHash\":").Append(GenerationSupport.JsonString(project.SourceHash))
            .Append(",\"entrypoints\":{\"messages\":\"messages.js\",\"types\":\"messages.d.ts\",\"runtime\":\"runtime.js\",\"server\":\"server.js\",\"transport\":\"transport.js\",\"dynamic\":\"dynamic.js\"},\"assets\":[");
        for (int index = 0; index < ordered.Length; index++)
        {
            if (index != 0) json.Append(','); TranslationGeneratedOutput output = ordered[index];
            json.Append("{\"path\":").Append(GenerationSupport.JsonString(output.RelativePath.Substring(root.Length)))
                .Append(",\"sha256\":").Append(GenerationSupport.JsonString(output.Sha256["sha256:".Length..]))
                .Append(",\"byteLength\":").Append(output.GetUtf8Bytes().Length).Append(",\"mediaType\":").Append(GenerationSupport.JsonString(output.MediaType)).Append('}');
        }
        json.Append("]}");
        return Output(TranslationGeneratedOutputKind.WebModuleManifestJson, root + "web-module-manifest-v3.json", "application/json", json.ToString());
    }

    private static string FileName(string key) => Rmf2GeneratedNamesV1.Identifier(key) + ".js";
    private static TranslationGeneratedOutput Output(TranslationGeneratedOutputKind kind, string path, string mediaType, string text) => new(kind, path, mediaType, text);
}
