using System;
using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using Microsoft.CodeAnalysis;

namespace Runic.Translations.Generator.Tests;

internal static class GeneratorTests
{
    private const string Project = """
        {
          "schemaVersion": 1,
          "catalog": "app",
          "code": { "namespace": "Example.Localization", "className": "AppText", "visibility": "public" },
          "baseLocale": "en",
          "locales": [ "en" ]
        }
        """;

    private const string Message = """
        .input {$folder :string}
        .input {$count :integer}
        Deleted {$count} files from {$folder}.
        """;

    internal static void Register(TestRunner runner)
    {
        runner.Add("locale TOML incremental membership updates generated catalogs", TomlMembershipChanges);
        runner.Add("locale TOML generates matching compilable source", TomlGenerationCompiles);
        runner.Add("locale TOML diagnostics retain physical document identity", TomlDiagnosticLocation);
        runner.Add("valid MF2 generation emits four compiling concerns", ValidGenerationCompiles);
        runner.Add("MF2 compiler diagnostics preserve normalized paths", DiagnosticLocation);
        runner.Add("multiple project declarations are rejected", MultipleProjects);
        runner.Add("input enumeration produces deterministic source bytes", DeterministicInputOrder);
        runner.Add("unmarked inputs are invisible", UnmarkedInputsAreIgnored);
        runner.Add("unchanged rerun caches tracked incremental inputs", IncrementalTrackingIsEnabled);
        runner.Add("mismatched runtime ABI reports RTR0024", MismatchedRuntimeAbi);
        runner.Add("missing runtime ABI reports RTR0024", MissingRuntimeAbi);
        runner.Add("Windows device hint stems are rejected before emission", WindowsDeviceHintStem);
    }

    private static TestInput ProjectInput(string text = Project, string path = "C:/repo/translations/runic.json") =>
        new(path, "Project", text);

    private static TestInput MessageInput(string text = Message, string path = "C:/repo/translations/en/FilesDeleted.mf2") =>
        new(path, "Mf2", text);

    private static void TomlMembershipChanges()
    {
        string project = Project.Replace("\"schemaVersion\": 1,", "\"schemaVersion\": 1, \"sourceLayout\": \"locale-toml\",", StringComparison.Ordinal)
            .Replace(",\n  \"locales\": [ \"en\" ]", string.Empty, StringComparison.Ordinal);
        var english = new TestInput("C:/repo/translations/en.toml", "Toml", "Greeting = 'Hello'\n");
        var german = new TestInput("C:/repo/translations/de.toml", "Toml", "Greeting = 'Hallo'\n");
        GeneratorRun initial = GeneratorTestHost.Run(ProjectInput(project), english);
        GeneratorRunResult added = GeneratorTestHost.Rerun(initial, ProjectInput(project), english, german);
        Assert.Equal(0, added.Diagnostics.Length, string.Join("\n", added.Diagnostics));
        Assert.True(string.Join("\n", added.GeneratedSources.Select(static source => source.SourceText.ToString())).Contains("Hallo", StringComparison.Ordinal), "added locale was ignored");
        GeneratorRun withGerman = GeneratorTestHost.Run(ProjectInput(project), english, german);
        GeneratorRunResult removed = GeneratorTestHost.Rerun(withGerman, ProjectInput(project), english);
        Assert.Equal(0, removed.Diagnostics.Length, string.Join("\n", removed.Diagnostics));
        Assert.True(!string.Join("\n", removed.GeneratedSources.Select(static source => source.SourceText.ToString())).Contains("Hallo", StringComparison.Ordinal), "removed locale survived");
    }

    private static void TomlGenerationCompiles()
    {
        string project = Project.Replace("\"schemaVersion\": 1,", "\"schemaVersion\": 1, \"sourceLayout\": \"locale-toml\",", StringComparison.Ordinal);
        GeneratorRun run = GeneratorTestHost.Run(ProjectInput(project),
            new TestInput("C:/repo/translations/en.toml", "Toml", "FilesDeleted = \u0027\u0027\u0027\n" + Message + "\u0027\u0027\u0027\n"));
        Assert.Equal(0, run.SingleResult.Diagnostics.Length, string.Join("\n", run.SingleResult.Diagnostics));
        Assert.Equal(4, run.SingleResult.GeneratedSources.Length, "TOML generated sources");
        Diagnostic[] errors = run.Compilation.GetDiagnostics().Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error).ToArray();
        Assert.Equal(0, errors.Length, string.Join("\n", errors.Select(static error => error.ToString())));
        Assert.Equal(Serialize(GeneratorTestHost.Run(ProjectInput(), MessageInput())), Serialize(run), "container-independent generated bytes");
    }

    private static void TomlDiagnosticLocation()
    {
        string project = Project.Replace("\"schemaVersion\": 1,", "\"schemaVersion\": 1, \"sourceLayout\": \"locale-toml\",", StringComparison.Ordinal);
        GeneratorRun run = GeneratorTestHost.Run(ProjectInput(project),
            new TestInput("C:/repo/translations/en.toml", "Toml", "Greeting = [1, 2]\n"));
        Assert.True(run.SingleResult.Diagnostics.Any(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error &&
            diagnostic.Location.GetLineSpan().Path == "translations/en.toml"), "TOML error did not identify its physical input");
        Assert.Equal(0, run.SingleResult.GeneratedSources.Length, "invalid TOML output");
    }

    private static void ValidGenerationCompiles()
    {
        GeneratorRun run = GeneratorTestHost.Run(ProjectInput(), MessageInput());
        Assert.Equal(0, run.SingleResult.Diagnostics.Length, "generator diagnostics");
        Assert.Equal(
            "AppText.Accessors.g.cs|AppText.CatalogData.g.cs|AppText.Keys.g.cs|AppText.Registration.g.cs",
            string.Join("|", HintNames(run)),
            "hint files");
        Diagnostic[] errors = run.Compilation.GetDiagnostics().Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error).ToArray();
        Assert.Equal(0, errors.Length, errors.Length == 0 ? "generated compilation" : string.Join(Environment.NewLine, errors.Select(static error => error.ToString())));
        string allText = string.Join("\n", run.SingleResult.GeneratedSources.Select(static source => source.SourceText.ToString()));
        Assert.True(allText.Contains("RuntimeAbiVersion = 1", StringComparison.Ordinal), "generated ABI marker missing");
        Assert.True(allText.Contains("GeneratorVersion = 1", StringComparison.Ordinal), "generator version marker missing");
        Assert.True(!allText.Contains("C:/repo", StringComparison.OrdinalIgnoreCase), "absolute path leaked into generated source");
    }

    private static void DiagnosticLocation()
    {
        GeneratorRun run = GeneratorTestHost.Run(
            ProjectInput(),
            MessageInput("Hello\n", "C:/repo/translations/en/Bad-Key.mf2"));
        Diagnostic diagnostic = run.SingleResult.Diagnostics.Single(static item => item.Id == "RTR0006");
        Assert.Equal("translations/en/Bad-Key.mf2", diagnostic.Location.GetLineSpan().Path, "diagnostic path");
    }

    private static void MultipleProjects()
    {
        GeneratorRun run = GeneratorTestHost.Run(
            ProjectInput(),
            ProjectInput(Project.Replace("\"app\"", "\"admin\"", StringComparison.Ordinal), "C:/repo/admin/runic.json"),
            MessageInput());
        Diagnostic diagnostic = run.SingleResult.Diagnostics.Single(static item => item.Id == "RTR0002");
        Assert.True(diagnostic.GetMessage(CultureInfo.InvariantCulture).Contains("Exactly one", StringComparison.Ordinal), "multiple-project message");
        Assert.Equal(0, run.SingleResult.GeneratedSources.Length, "multiple-project generated sources");
    }

    private static void DeterministicInputOrder()
    {
        TestInput project = ProjectInput();
        TestInput message = MessageInput();
        Assert.Equal(
            Serialize(GeneratorTestHost.Run(project, message)),
            Serialize(GeneratorTestHost.Run(message, project)),
            "generated bytes by input order");
    }

    private static void UnmarkedInputsAreIgnored()
    {
        GeneratorRun run = GeneratorTestHost.Run(new TestInput("C:/repo/random.json", "Other", "not json"));
        Assert.Equal(0, run.SingleResult.Diagnostics.Length, "ignored diagnostics");
        Assert.Equal(0, run.SingleResult.GeneratedSources.Length, "ignored generated sources");
    }

    private static void IncrementalTrackingIsEnabled()
    {
        GeneratorRun run = GeneratorTestHost.Run(ProjectInput(), MessageInput());
        ImmutableDictionary<string, ImmutableArray<IncrementalGeneratorRunStep>> steps = run.SingleResult.TrackedSteps;
        Assert.True(steps.ContainsKey("TranslationInputs"), "input tracking step missing");
        Assert.True(steps.ContainsKey("TranslationCompilation"), "compilation tracking step missing");
        GeneratorRunResult rerun = run.Driver.RunGenerators(run.InputCompilation).GetRunResult().Results.Single();
        Assert.True(
            rerun.TrackedSteps["TranslationInputs"].SelectMany(static step => step.Outputs)
                .All(static output => output.Reason == IncrementalStepRunReason.Cached),
            "unchanged additional inputs were not cached");
    }

    private static void MismatchedRuntimeAbi()
    {
        GeneratorRun run = GeneratorTestHost.Run(RuntimeReferenceMode.Mismatched, ProjectInput(), MessageInput());
        Diagnostic diagnostic = run.SingleResult.Diagnostics.Single(static item => item.Id == "RTR0024");
        Assert.Equal(
            "Referenced Runic.Translations runtime ABI version 2 is incompatible with generated ABI version 1.",
            diagnostic.GetMessage(CultureInfo.InvariantCulture),
            "mismatched ABI message");
        Assert.Equal(0, run.SingleResult.GeneratedSources.Length, "mismatched ABI generated sources");
    }

    private static void MissingRuntimeAbi()
    {
        GeneratorRun run = GeneratorTestHost.Run(RuntimeReferenceMode.Missing, ProjectInput(), MessageInput());
        Diagnostic diagnostic = run.SingleResult.Diagnostics.Single(static item => item.Id == "RTR0024");
        Assert.Equal(
            "Referenced Runic.Translations runtime ABI is missing; generated code requires ABI version 1.",
            diagnostic.GetMessage(CultureInfo.InvariantCulture),
            "missing ABI message");
        Assert.Equal(0, run.SingleResult.GeneratedSources.Length, "missing ABI generated sources");
    }

    private static void WindowsDeviceHintStem()
    {
        GeneratorRun run = GeneratorTestHost.Run(
            ProjectInput(Project.Replace("AppText", "CON", StringComparison.Ordinal)),
            MessageInput());
        Diagnostic diagnostic = run.SingleResult.Diagnostics.Single(static item => item.Id == "RTR0018");
        Assert.Equal("translations/runic.json", diagnostic.Location.GetLineSpan().Path, "device diagnostic path");
        Assert.Equal(0, run.SingleResult.GeneratedSources.Length, "device generated sources");
    }

    private static string[] HintNames(GeneratorRun run) => run.SingleResult.GeneratedSources
        .Select(static source => source.HintName)
        .OrderBy(static name => name, StringComparer.Ordinal)
        .ToArray();

    private static string Serialize(GeneratorRun run) => string.Join(
        "\u001e",
        run.SingleResult.GeneratedSources
            .OrderBy(static source => source.HintName, StringComparer.Ordinal)
            .Select(static source => source.HintName + "\u001f" + source.SourceText.ToString()));
}
