using System;
using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using Microsoft.CodeAnalysis;

namespace Runic.Translations.Generator.Tests;

internal static class GeneratorTests
{
    private const string Project = """
        {
          "schemaVersion": 1,
          "catalog": "app",
          "code": { "namespace": "Example.Localization", "className": "AppText", "visibility": "public" },
          "baseLocale": "en",
          "locales": [ "en" ]
        }
        """;

    private const string Message = """
        .input {$folder :string}
        .input {$count :integer}
        Deleted {$count} files from {$folder}.
        """;

    internal static void Register(TestRunner runner)
    {
        runner.Add("valid MF2 generation emits four compiling concerns", ValidGenerationCompiles);
        runner.Add("MF2 compiler diagnostics preserve normalized paths", DiagnosticLocation);
        runner.Add("multiple project declarations are rejected", MultipleProjects);
        runner.Add("input enumeration produces deterministic source bytes", DeterministicInputOrder);
        runner.Add("unmarked inputs are invisible", UnmarkedInputsAreIgnored);
        runner.Add("unchanged rerun caches tracked incremental inputs", IncrementalTrackingIsEnabled);
        runner.Add("mismatched runtime ABI reports RTR0024", MismatchedRuntimeAbi);
        runner.Add("missing runtime ABI reports RTR0024", MissingRuntimeAbi);
        runner.Add("Windows device hint stems are rejected before emission", WindowsDeviceHintStem);
    }

    private static TestInput ProjectInput(string text = Project, string path = "C:/repo/translations/runic.json") =>
        new(path, "Project", text);

    private static TestInput MessageInput(string text = Message, string path = "C:/repo/translations/en/FilesDeleted.mf2") =>
        new(path, "Mf2", text);

    private static void ValidGenerationCompiles()
    {
        GeneratorRun run = GeneratorTestHost.Run(ProjectInput(), MessageInput());
        Assert.Equal(0, run.SingleResult.Diagnostics.Length, "generator diagnostics");
        Assert.Equal(
            "AppText.Accessors.g.cs|AppText.CatalogData.g.cs|AppText.Keys.g.cs|AppText.Registration.g.cs",
            string.Join("|", HintNames(run)),
            "hint files");
        Diagnostic[] errors = run.Compilation.GetDiagnostics().Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error).ToArray();
        Assert.Equal(0, errors.Length, errors.Length == 0 ? "generated compilation" : string.Join(Environment.NewLine, errors.Select(static error => error.ToString())));
        string allText = string.Join("\n", run.SingleResult.GeneratedSources.Select(static source => source.SourceText.ToString()));
        Assert.True(allText.Contains("RuntimeAbiVersion = 1", StringComparison.Ordinal), "generated ABI marker missing");
        Assert.True(allText.Contains("GeneratorVersion = 1", StringComparison.Ordinal), "generator version marker missing");
        Assert.True(!allText.Contains("C:/repo", StringComparison.OrdinalIgnoreCase), "absolute path leaked into generated source");
    }

    private static void DiagnosticLocation()
    {
        GeneratorRun run = GeneratorTestHost.Run(
            ProjectInput(),
            MessageInput("Hello\n", "C:/repo/translations/en/Bad-Key.mf2"));
        Diagnostic diagnostic = run.SingleResult.Diagnostics.Single(static item => item.Id == "RTR0006");
        Assert.Equal("translations/en/Bad-Key.mf2", diagnostic.Location.GetLineSpan().Path, "diagnostic path");
    }

    private static void MultipleProjects()
    {
        GeneratorRun run = GeneratorTestHost.Run(
            ProjectInput(),
            ProjectInput(Project.Replace("\"app\"", "\"admin\"", StringComparison.Ordinal), "C:/repo/admin/runic.json"),
            MessageInput());
        Diagnostic diagnostic = run.SingleResult.Diagnostics.Single(static item => item.Id == "RTR0002");
        Assert.True(diagnostic.GetMessage(CultureInfo.InvariantCulture).Contains("Exactly one", StringComparison.Ordinal), "multiple-project message");
        Assert.Equal(0, run.SingleResult.GeneratedSources.Length, "multiple-project generated sources");
    }

    private static void DeterministicInputOrder()
    {
        TestInput project = ProjectInput();
        TestInput message = MessageInput();
        Assert.Equal(
            Serialize(GeneratorTestHost.Run(project, message)),
            Serialize(GeneratorTestHost.Run(message, project)),
            "generated bytes by input order");
    }

    private static void UnmarkedInputsAreIgnored()
    {
        GeneratorRun run = GeneratorTestHost.Run(new TestInput("C:/repo/random.json", "Other", "not json"));
        Assert.Equal(0, run.SingleResult.Diagnostics.Length, "ignored diagnostics");
        Assert.Equal(0, run.SingleResult.GeneratedSources.Length, "ignored generated sources");
    }

    private static void IncrementalTrackingIsEnabled()
    {
        GeneratorRun run = GeneratorTestHost.Run(ProjectInput(), MessageInput());
        ImmutableDictionary<string, ImmutableArray<IncrementalGeneratorRunStep>> steps = run.SingleResult.TrackedSteps;
        Assert.True(steps.ContainsKey("TranslationInputs"), "input tracking step missing");
        Assert.True(steps.ContainsKey("TranslationCompilation"), "compilation tracking step missing");
        GeneratorRunResult rerun = run.Driver.RunGenerators(run.InputCompilation).GetRunResult().Results.Single();
        Assert.True(
            rerun.TrackedSteps["TranslationInputs"].SelectMany(static step => step.Outputs)
                .All(static output => output.Reason == IncrementalStepRunReason.Cached),
            "unchanged additional inputs were not cached");
    }

    private static void MismatchedRuntimeAbi()
    {
        GeneratorRun run = GeneratorTestHost.Run(RuntimeReferenceMode.Mismatched, ProjectInput(), MessageInput());
        Diagnostic diagnostic = run.SingleResult.Diagnostics.Single(static item => item.Id == "RTR0024");
        Assert.Equal(
            "Referenced Runic.Translations runtime ABI version 2 is incompatible with generated ABI version 1.",
            diagnostic.GetMessage(CultureInfo.InvariantCulture),
            "mismatched ABI message");
        Assert.Equal(0, run.SingleResult.GeneratedSources.Length, "mismatched ABI generated sources");
    }

    private static void MissingRuntimeAbi()
    {
        GeneratorRun run = GeneratorTestHost.Run(RuntimeReferenceMode.Missing, ProjectInput(), MessageInput());
        Diagnostic diagnostic = run.SingleResult.Diagnostics.Single(static item => item.Id == "RTR0024");
        Assert.Equal(
            "Referenced Runic.Translations runtime ABI is missing; generated code requires ABI version 1.",
            diagnostic.GetMessage(CultureInfo.InvariantCulture),
            "missing ABI message");
        Assert.Equal(0, run.SingleResult.GeneratedSources.Length, "missing ABI generated sources");
    }

    private static void WindowsDeviceHintStem()
    {
        GeneratorRun run = GeneratorTestHost.Run(
            ProjectInput(Project.Replace("AppText", "CON", StringComparison.Ordinal)),
            MessageInput());
        Diagnostic diagnostic = run.SingleResult.Diagnostics.Single(static item => item.Id == "RTR0018");
        Assert.Equal("translations/runic.json", diagnostic.Location.GetLineSpan().Path, "device diagnostic path");
        Assert.Equal(0, run.SingleResult.GeneratedSources.Length, "device generated sources");
    }

    private static string[] HintNames(GeneratorRun run) => run.SingleResult.GeneratedSources
        .Select(static source => source.HintName)
        .OrderBy(static name => name, StringComparer.Ordinal)
        .ToArray();

    private static string Serialize(GeneratorRun run) => string.Join(
        "\u001e",
        run.SingleResult.GeneratedSources
            .OrderBy(static source => source.HintName, StringComparer.Ordinal)
            .Select(static source => source.HintName + "\u001f" + source.SourceText.ToString()));
}
