using System;
using System.Collections.Immutable;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Runic.Translations.Generator.Tests;

internal static class GeneratorTests
{
    private const string Project = """
        {
          "schemaVersion": 1,
          "catalog": "app",
          "code": { "namespace": "Example.Localization", "className": "AppText", "visibility": "public" },
          "baseLocale": "en",
          "locales": [ "en" ]
        }
        """;

    private const string Message = """
        .input {$folder :string}
        .input {$count :integer}
        Deleted {$count} files from {$folder}.
        """;

    internal static void Register(TestRunner runner)
    {
        runner.Add("RMF2 generation rejects missing unsupported and unknown additive runtime ABIs", Rmf2UnsupportedRuntime);
        runner.Add("RMF2 v4 generation pins ABI 1 on both known supporting runtime markers", Rmf2SupportedRuntime);
        runner.Add("RMF2 generation compiles standalone markup caller contracts and pack v4", Rmf2GenerationCompiles);
        runner.Add("explicit v5 consumer ABI 2 checks remain separate from v4 generation", Rmf2ExplicitV5Requirement);
        runner.Add("staged RMF2 v5 generator emits four compiling typed concerns", Rmf2V5GenerationCompiles);
        runner.Add("staged RMF2 v5 generator preserves source and caller identities", Rmf2V5GeneratedIdentity);
        runner.Add("staged RMF2 v5 generator rejects runtime-invalid empty catalogs", Rmf2V5EmptyCatalog);
        runner.Add("staged RMF2 v5 generated code executes the frozen semantic surface", Rmf2V5GeneratedExecution);
        runner.Add("staged RMF2 v5 structured contracts execute plain locale variants", Rmf2V5CrossLocaleStructuredContract);
        runner.Add("staged RMF2 v5 generated fallback preserves canonical inputs and content locale", Rmf2V5GeneratedFallback);
        runner.Add("staged RMF2 v5 generated data assigns safe IDs to locale extras", Rmf2V5GeneratedExtras);
        runner.Add("staged RMF2 v5 generated external-pack factory executes artifact v5", Rmf2V5ExternalPack);
        runner.Add("staged RMF2 v5 generated names retain broad NFC wire identities", Rmf2V5GeneratedNames);
        runner.Add("staged RMF2 v5 generator requires the exact additive ABI", Rmf2V5RuntimeRequirement);
        runner.Add("staged RMF2 v5 work preserves the v1 generated byte golden", LegacyV1ByteGolden);
        runner.Add("staged RMF2 v5 work preserves the v4 generated byte golden", Rmf2V4ByteGolden);
        runner.Add("grouped TOML paths preserve typed legacy accessors", GroupedTomlGenerationCompiles);
        runner.Add("grouped TOML collisions reject ambiguous generated identifiers", GroupedTomlCollisions);
        runner.Add("locale TOML incremental membership updates generated catalogs", TomlMembershipChanges);
        runner.Add("locale TOML generates matching compilable source", TomlGenerationCompiles);
        runner.Add("locale TOML diagnostics retain physical document identity", TomlDiagnosticLocation);
        runner.Add("valid MF2 generation emits four compiling concerns", ValidGenerationCompiles);
        runner.Add("MF2 compiler diagnostics preserve normalized paths", DiagnosticLocation);
        runner.Add("multiple project declarations are rejected", MultipleProjects);
        runner.Add("input enumeration produces deterministic source bytes", DeterministicInputOrder);
        runner.Add("unmarked inputs are invisible", UnmarkedInputsAreIgnored);
        runner.Add("unchanged rerun caches tracked incremental inputs", IncrementalTrackingIsEnabled);
        runner.Add("mismatched runtime ABI reports RTR0024", MismatchedRuntimeAbi);
        runner.Add("missing runtime ABI reports RTR0024", MissingRuntimeAbi);
        runner.Add("Windows device hint stems are rejected before emission", WindowsDeviceHintStem);
    }

    private static void Rmf2UnsupportedRuntime()
    {
        string project = Project.Replace("\"schemaVersion\": 1,", "\"schemaVersion\": 1, \"sourceLayout\": \"rmf2-v1\",", StringComparison.Ordinal);
        foreach (RuntimeReferenceMode mode in new[] { RuntimeReferenceMode.Legacy, RuntimeReferenceMode.Rmf2Zero, RuntimeReferenceMode.Rmf2Unknown })
        {
            GeneratorRun run = GeneratorTestHost.Run(mode, ProjectInput(project), new TestInput("C:/repo/translations/en.rmf2", "Rmf2", "greeting = Hello"));
            Assert.Equal("RTR0024", run.SingleResult.Diagnostics.Single().Id, mode + ": additive RMF2 ABI diagnostic");
            Assert.Equal(0, run.SingleResult.GeneratedSources.Length, mode + ": incompatible runtime received RMF2 source");
        }
    }

    private static void Rmf2SupportedRuntime()
    {
        string project = Project.Replace("\"schemaVersion\": 1,", "\"schemaVersion\": 1, \"sourceLayout\": \"rmf2-v1\",", StringComparison.Ordinal);
        foreach (RuntimeReferenceMode mode in new[] { RuntimeReferenceMode.Rmf2V1, RuntimeReferenceMode.Rmf2V2 })
        {
            // Marker-only references exercise discovery without requiring ABI 2 helper methods.
            GeneratorRun run = GeneratorTestHost.Run(mode, ProjectInput(project), new TestInput("C:/repo/translations/en.rmf2", "Rmf2", "greeting = Hello"));
            Assert.Equal(0, run.SingleResult.Diagnostics.Length, string.Join("\n", run.SingleResult.Diagnostics));
            Assert.Equal(4, run.SingleResult.GeneratedSources.Length, mode + ": v4 generated sources");
            Assert.True(Serialize(run).Contains("public const int Rmf2RuntimeAbiVersion = 1;", StringComparison.Ordinal), mode + ": v4 requirement must be literal 1");
        }
    }

    private static void Rmf2GenerationCompiles()
    {
        string project = Project.Replace("\"schemaVersion\": 1,", "\"schemaVersion\": 1, \"sourceLayout\": \"rmf2-v1\",", StringComparison.Ordinal);
        GeneratorRun run = GeneratorTestHost.Run(ProjectInput(project), new TestInput("C:/repo/translations/en.rmf2", "Rmf2",
            "greeting = {#strong}Hello {$name}{/strong} {#icon ref=star/} {#link}Open{/link}\n"));
        Assert.Equal(0, run.SingleResult.Diagnostics.Length, string.Join("\n", run.SingleResult.Diagnostics));
        Diagnostic[] errors = run.Compilation.GetDiagnostics().Where(d => d.Severity == DiagnosticSeverity.Error).ToArray();
        Assert.Equal(0, errors.Length, string.Join("\n", errors.Select(d => d.ToString())));
        IFieldSymbol requirement = (IFieldSymbol)run.Compilation.GetTypeByMetadataName("Example.Localization.AppTextCatalog")!.GetMembers("Rmf2RuntimeAbiVersion").Single();
        Assert.Equal(1, (int)requirement.ConstantValue!, "v4 compilation must not inherit the referenced runtime's ABI 2 marker");
    }

    private static void Rmf2ExplicitV5Requirement()
    {
        GeneratorRun run = GeneratorTestHost.Run();
        const string source = """
            internal static class FutureV5Consumer
            {
                internal const int RequiredRmf2RuntimeAbiVersion = 2;
                internal static void CheckRuntime() =>
                    global::Runic.Translations.TranslationsCompatibility.EnsureRmf2RuntimeAbi(RequiredRmf2RuntimeAbiVersion);
            }
            """;
        Compilation compilation = run.InputCompilation.AddSyntaxTrees(CSharpSyntaxTree.ParseText(source, new CSharpParseOptions(LanguageVersion.Preview)));
        Diagnostic[] errors = compilation.GetDiagnostics().Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error).ToArray();
        Assert.Equal(0, errors.Length, string.Join("\n", errors.Select(static error => error.ToString())));
        IFieldSymbol requirement = (IFieldSymbol)compilation.GetTypeByMetadataName("FutureV5Consumer")!.GetMembers("RequiredRmf2RuntimeAbiVersion").Single();
        Assert.Equal(2, (int)requirement.ConstantValue!, "v5 consumers can embed a distinct literal requirement");
        TranslationsCompatibility.EnsureRmf2RuntimeAbi(2);
    }

    private static void Rmf2V5GenerationCompiles()
    {
        string project = Project.Replace("\"schemaVersion\": 1,", "\"schemaVersion\": 1, \"sourceLayout\": \"rmf2-v1\",", StringComparison.Ordinal);
        GeneratorRun shipping = GeneratorTestHost.Run(ProjectInput(project),
            new TestInput("C:/repo/translations/en.rmf2", "Rmf2", "literal = {1e+2 :number}"));
        Assert.True(shipping.SingleResult.Diagnostics.Any(static diagnostic => diagnostic.Id == "RTR0065"),
            "the shipping generator silently activated the staged v5 profile");
        Assert.Equal(0, shipping.SingleResult.GeneratedSources.Length, "shipping generator emitted v5-only input");
        const string resource = """
            account {
              summary =
                .input {$count :integer}
                .input {$rate :number}
                .local $percent = {$rate :number style=percent maximumFractionDigits=2}
                .match $count
                one {{One item at {$percent}}}
                * {{{$count} items at {$percent}}}
              rich = {#strong @open}Hello{/strong @close}
              carriers =
                .input {$boolean :runic:boolean}
                .input {$date :date}
                .input {$datetime :datetime}
                .input {$guid :runic:uuid}
                .input {$time :time}
                {{{$boolean} {$date} {$datetime} {$guid} {$time}}}
            }
            """;
        GeneratorRun run = GeneratorTestHost.RunRmf2V5(ProjectInput(project),
            new TestInput("C:/repo/translations/en.rmf2", "Rmf2", resource));
        Assert.Equal(0, run.SingleResult.Diagnostics.Length, string.Join("\n", run.SingleResult.Diagnostics));
        Assert.Equal(4, run.SingleResult.GeneratedSources.Length, "v5 generated concerns");
        string text = Serialize(run);
        Diagnostic[] errors = run.Compilation.GetDiagnostics().Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error).ToArray();
        Assert.Equal(0, errors.Length, string.Join("\n", errors.Select(static error => error.ToString())) + "\n" + text);
        Assert.True(text.Contains("CompiledTranslationDefinition.FromRmf2Inputs", StringComparison.Ordinal), "v5 definition factory missing");
        Assert.True(text.Contains("CompiledTextMessage.FromRmf2", StringComparison.Ordinal), "v5 message wrapper missing");
        Assert.True(text.Contains("new global::Runic.Translations.CompiledRmf2Message", StringComparison.Ordinal), "typed v5 model missing");
        Assert.True(text.Contains("EnsureRmf2RuntimeAbi(2)", StringComparison.Ordinal), "literal ABI 2 guard missing");
        Assert.True(text.Contains("public const int Rmf2RuntimeAbiVersion = 2;", StringComparison.Ordinal), "literal ABI 2 marker missing");
        Assert.Equal(text, Serialize(GeneratorTestHost.RunRmf2V5(
            new TestInput("C:/repo/translations/en.rmf2", "Rmf2", resource), ProjectInput(project))),
            "v5 generated bytes depend on input enumeration");
    }

    private static void Rmf2V5RuntimeRequirement()
    {
        string project = Project.Replace("\"schemaVersion\": 1,", "\"schemaVersion\": 1, \"sourceLayout\": \"rmf2-v1\",", StringComparison.Ordinal);
        TestInput message = new("C:/repo/translations/en.rmf2", "Rmf2", "greeting = Hello");
        foreach (RuntimeReferenceMode mode in new[] { RuntimeReferenceMode.Missing, RuntimeReferenceMode.Mismatched, RuntimeReferenceMode.Legacy, RuntimeReferenceMode.Rmf2V1, RuntimeReferenceMode.Rmf2Zero, RuntimeReferenceMode.Rmf2Unknown })
        {
            GeneratorRun run = GeneratorTestHost.RunRmf2V5(mode, ProjectInput(project), message);
            Assert.Equal("RTR0024", run.SingleResult.Diagnostics.Single().Id, mode + ": v5 ABI diagnostic");
            Assert.Equal(0, run.SingleResult.GeneratedSources.Length, mode + ": incompatible runtime received v5 source");
        }
    }

    private static void Rmf2V5GeneratedIdentity()
    {
        string project = Project.Replace("\"schemaVersion\": 1,", "\"schemaVersion\": 1, \"sourceLayout\": \"rmf2-v1\",", StringComparison.Ordinal);
        GeneratorRun first = GeneratorTestHost.RunRmf2V5(ProjectInput(project),
            new TestInput("C:/repo/translations/en.rmf2", "Rmf2", "greeting = First"));
        GeneratorRun second = GeneratorTestHost.RunRmf2V5(ProjectInput(project),
            new TestInput("C:/repo/translations/en.rmf2", "Rmf2", "greeting = Second"));

        Assert.Equal(Constant(first, "ContractFingerprint"), Constant(second, "ContractFingerprint"),
            "content-only changes altered the caller contract fingerprint");
        Assert.True(!string.Equals(Constant(first, "SourceHash"), Constant(second, "SourceHash"), StringComparison.Ordinal),
            "content-only changes did not alter the generated source hash");
    }

    private static void Rmf2V5EmptyCatalog()
    {
        string project = Project.Replace("\"schemaVersion\": 1,", "\"schemaVersion\": 1, \"sourceLayout\": \"rmf2-v1\",", StringComparison.Ordinal);
        GeneratorRun run = GeneratorTestHost.RunRmf2V5(ProjectInput(project));
        Assert.Equal("RTR0009", run.SingleResult.Diagnostics.Single().Id, "empty v5 catalog diagnostic");
        Assert.Equal(0, run.SingleResult.GeneratedSources.Length, "empty v5 catalog emitted runtime-invalid sources");
    }

    private static void Rmf2V4ByteGolden()
    {
        string project = Project.Replace("\"schemaVersion\": 1,", "\"schemaVersion\": 1, \"sourceLayout\": \"rmf2-v1\",", StringComparison.Ordinal);
        GeneratorRun run = GeneratorTestHost.Run(ProjectInput(project),
            new TestInput("C:/repo/translations/en.rmf2", "Rmf2", "greeting = Hello {$name}"));
        string hash = Convert.ToHexStringLower(SHA256.HashData(Encoding.UTF8.GetBytes(Serialize(run))));
        Assert.Equal("b3fcf87034724a43ba3f1222674e291c36b37a2a166c3daa426a3d81fb958e8a", hash,
            "v4 generated bytes changed");
        Assert.True(Serialize(run).Contains("public const int Rmf2RuntimeAbiVersion = 1;", StringComparison.Ordinal),
            "v4 generated ABI requirement changed");
    }

    private static void LegacyV1ByteGolden()
    {
        GeneratorRun run = GeneratorTestHost.Run(ProjectInput(), MessageInput());
        string hash = Convert.ToHexStringLower(SHA256.HashData(Encoding.UTF8.GetBytes(Serialize(run))));
        Assert.Equal("66d1bdcb37f57ea1ce2d807ffb996aa5e7241155cc45efe3163b72b90dc21dc3", hash,
            "v1 generated bytes changed");
        Assert.True(!Serialize(run).Contains("Rmf2RuntimeAbiVersion", StringComparison.Ordinal),
            "legacy generated output acquired an RMF2 requirement");
    }

    private static void Rmf2V5GeneratedExecution()
    {
        string project = Project.Replace("\"schemaVersion\": 1,", "\"schemaVersion\": 1, \"sourceLayout\": \"rmf2-v1\",", StringComparison.Ordinal);
        const string resource = """
            dynamic =
              .input {$digits :integer}
              .input {$n :number}
              .input {$style :string}
              .local $d = {$digits}
              {{{$n :number style=$style minimumFractionDigits=$d maximumFractionDigits=$digits}}}
            exact =
              .input {$n :number}
              .match $n
              1.0 {{exact}}
              one {{category}}
              * {{other}}
            literal = {1e+2 :number}
            rich = {#strong @open}Hello{/strong @close}
            """;
        string dynamicMember = PathMember("dynamic"), exactMember = PathMember("exact");
        string literalMember = PathMember("literal"), richMember = PathMember("rich");
        string source = $$"""
            namespace Example.Localization;
            public static class V5ExecutionProbe
            {
                public static string Run()
                {
                    global::Runic.Translations.ITranslationManager manager =
                        AppTextCatalog.CreateManagerAsync().AsTask().GetAwaiter().GetResult();
                    var text = new AppText(manager);
                    string dynamicValue = text.{{dynamicMember}}(2L, 0.125m, "percent");
                    string exact = text.{{exactMember}}(1.00m);
                    string literal = text.{{literalMember}};
                    int richNodes = text.{{richMember}}.Nodes.Length;
                    global::Runic.Translations.TranslationPackContract contract = AppTextCatalog.CreateExternalPackContract("en");
                    return dynamicValue + "|" + exact + "|" + literal + "|" + richNodes.ToString(global::System.Globalization.CultureInfo.InvariantCulture)
                        + "|" + contract.Profile + "|" + contract.MessageGrammarVersion.ToString(global::System.Globalization.CultureInfo.InvariantCulture);
                }
            }
            """;
        GeneratorRun run = GeneratorTestHost.RunRmf2V5WithConsumer(source, ProjectInput(project),
            new TestInput("C:/repo/translations/en.rmf2", "Rmf2", resource));
        Assert.Equal(0, run.SingleResult.Diagnostics.Length, string.Join("\n", run.SingleResult.Diagnostics));
        Assert.Equal("12.50%|exact|100|3|rmf2-execution-v2|5",
            Execute(run, "Example.Localization.V5ExecutionProbe", "Run"), "generated v5 execution");
    }

    private static void Rmf2V5GeneratedNames()
    {
        string project = Project.Replace("\"schemaVersion\": 1,", "\"schemaVersion\": 1, \"sourceLayout\": \"rmf2-v1\",", StringComparison.Ordinal);
        const string resource = """
            class =
              .input {$a-b :string}
              .input {$café :string}
              .input {$class :string}
              .input {$用户 :string}
              {{{$a-b}|{$café}|{$class}|{$用户}}}
            """;
        string member = PathMember("class");
        string source = $$"""
            namespace Example.Localization;
            public static class V5NameProbe
            {
                public static string Run()
                {
                    global::Runic.Translations.ITranslationManager manager =
                        AppTextCatalog.CreateManagerAsync().AsTask().GetAwaiter().GetResult();
                    var text = new AppText(manager);
                    string typed = text.{{member}}("dash", "accent", "keyword", "unicode");
                    global::Runic.Translations.TextArgument[] arguments =
                    [
                        global::Runic.Translations.TextArgument.CreateRmf2("a-b", new global::Runic.Translations.TextArgument("_", "dash")),
                        global::Runic.Translations.TextArgument.CreateRmf2("café", new global::Runic.Translations.TextArgument("_", "accent")),
                        global::Runic.Translations.TextArgument.CreateRmf2("class", new global::Runic.Translations.TextArgument("_", "keyword")),
                        global::Runic.Translations.TextArgument.CreateRmf2("用户", new global::Runic.Translations.TextArgument("_", "unicode")),
                    ];
                    string fallback = text.r_args_{{member}}(arguments);
                    return typed + "|" + fallback;
                }
            }
            """;
        GeneratorRun run = GeneratorTestHost.RunRmf2V5WithConsumer(source, ProjectInput(project),
            new TestInput("C:/repo/translations/en.rmf2", "Rmf2", resource));
        Assert.Equal("dash|accent|keyword|unicode|dash|accent|keyword|unicode",
            Execute(run, "Example.Localization.V5NameProbe", "Run"), "typed and span caller identity");
        string generated = Serialize(run);
        foreach (string name in new[] { "a-b", "café", "class", "用户" })
        {
            Assert.True(generated.Contains("TextArgument.CreateRmf2(" + Quote(name), StringComparison.Ordinal), "wire identity missing: " + name);
            Assert.True(generated.Contains(Encoded(name), StringComparison.Ordinal), "encoded parameter missing: " + name);
        }
        Assert.True(Encoded("a-b") != Encoded("a_b"), "punctuation mapping collided");
        Assert.True(Encoded("café") == Encoded("cafe\u0301"), "NFC equivalents did not converge");
        Assert.True(Encoded("1lead").All(static character => char.IsAsciiLetterOrDigit(character) || character == '_'), "leading-digit mapping is not a C# identifier");
        Assert.True(Encoded("+-.") != Encoded("_"), "punctuation mapping collided");
    }

    private static void Rmf2V5CrossLocaleStructuredContract()
    {
        string project = Project
            .Replace("\"schemaVersion\": 1,", "\"schemaVersion\": 1, \"sourceLayout\": \"rmf2-v1\",", StringComparison.Ordinal)
            .Replace("[ \"en\" ]", "[ \"en\", \"de\" ]", StringComparison.Ordinal);
        string member = PathMember("value");
        string source = $$"""
            namespace Example.Localization;
            public static class V5StructuredLocaleProbe
            {
                public static string Run()
                {
                    var manager = AppTextCatalog.CreateManagerAsync("en").AsTask().GetAwaiter().GetResult();
                    var text = new AppText(manager);
                    string english = text.{{member}}.Nodes.Span[0].Value;
                    manager.SetLocaleAsync("de").AsTask().GetAwaiter().GetResult();
                    string german = text.{{member}}.Nodes.Span[1].Value;
                    manager.SetLocaleAsync("en").AsTask().GetAwaiter().GetResult();
                    return english + "|" + german + "|" + text.{{member}}.Nodes.Span[0].Value;
                }
            }
            """;
        GeneratorRun run = GeneratorTestHost.RunRmf2V5WithConsumer(source, ProjectInput(project),
            new TestInput("C:/repo/translations/en.rmf2", "Rmf2", "value = Plain"),
            new TestInput("C:/repo/translations/de.rmf2", "Rmf2", "value = {#strong}Rich{/strong}"));
        Assert.Equal("Plain|Rich|Plain", Execute(run, "Example.Localization.V5StructuredLocaleProbe", "Run"),
            "contract-wide structured output did not survive plain/markup locale switching");
    }

    private static void Rmf2V5GeneratedFallback()
    {
        string project = Project
            .Replace("\"schemaVersion\": 1,", "\"schemaVersion\": 1, \"sourceLayout\": \"rmf2-v1\", \"validation\": { \"translationCompleteness\": \"allow\" },", StringComparison.Ordinal)
            .Replace("[ \"en\" ]", "[ \"en\", \"de\", { \"tag\": \"fr\", \"fallback\": \"de\" } ]", StringComparison.Ordinal);
        const string english = """
            value =
              .input {$rate :number}
              .input {$unused :string}
              {{English {$rate} {$unused}}}
            """;
        const string german = """
            value =
              .input {$rate :number}
              .local $formatted = {$rate :number style=percent minimumFractionDigits=2 maximumFractionDigits=2}
              {{{$formatted}}}
            """;
        string member = PathMember("value");
        string source = $$"""
            namespace Example.Localization;
            public static class V5FallbackProbe
            {
                public static string Run()
                {
                    var manager = AppTextCatalog.CreateManagerAsync("fr").AsTask().GetAwaiter().GetResult();
                    return manager.Current.Locale + "|" + new AppText(manager).{{member}}(0.125m, "unused");
                }
            }
            """;
        GeneratorRun run = GeneratorTestHost.RunRmf2V5WithConsumer(source, ProjectInput(project),
            new TestInput("C:/repo/translations/en.rmf2", "Rmf2", english),
            new TestInput("C:/repo/translations/de.rmf2", "Rmf2", german));
        Assert.Equal("fr|12,50%", Execute(run, "Example.Localization.V5FallbackProbe", "Run"),
            "generated v5 fallback or canonical input expansion");
    }

    private static void Rmf2V5ExternalPack()
    {
        string project = Project.Replace("\"schemaVersion\": 1,", "\"schemaVersion\": 1, \"sourceLayout\": \"rmf2-v1\",", StringComparison.Ordinal);
        string member = PathMember("greeting");
        string source = $$$$"""
            namespace Example.Localization;
            public static class V5ExternalPackProbe
            {
                public static string Run()
                {
                    string json = "{\"artifactVersion\":5,\"messageGrammarVersion\":5,\"profile\":\"rmf2-execution-v2\",\"catalog\":\"app\",\"locale\":\"en\",\"contractFingerprint\":\""
                        + AppTextCatalog.ContractFingerprint
                        + "\",\"messages\":{\"greeting\":{\"contentLocale\":\"en\",\"ast\":{\"astVersion\":5,\"profile\":\"rmf2-execution-v2\",\"inputs\":[],\"declarations\":[],\"selectors\":[],\"variants\":[{\"keys\":[],\"nodes\":[{\"kind\":\"text\",\"value\":\"External\"}]}]}}},\"markupContract\":"
                        + AppTextCatalog.Rmf2MarkupContract + "}";
                    var manager = AppTextCatalog.CreateExternalManagerAsync(new Source(global::System.Text.Encoding.UTF8.GetBytes(json)))
                        .AsTask().GetAwaiter().GetResult();
                    return new AppText(manager).{{{{member}}}};
                }

                private sealed class Source(byte[] bytes) : global::Runic.Translations.IExternalTranslationSource
                {
                    public global::System.Threading.Tasks.ValueTask<global::Runic.Translations.ExternalTranslationPack?> LoadAsync(
                        string catalog, string locale, global::System.Threading.CancellationToken cancellationToken) =>
                        global::System.Threading.Tasks.ValueTask.FromResult<global::Runic.Translations.ExternalTranslationPack?>(
                            new global::Runic.Translations.ExternalTranslationPack(bytes));
                }
            }
            """;
        GeneratorRun run = GeneratorTestHost.RunRmf2V5WithConsumer(source, ProjectInput(project),
            new TestInput("C:/repo/translations/en.rmf2", "Rmf2", "greeting = Compiled"));
        Assert.Equal("External", Execute(run, "Example.Localization.V5ExternalPackProbe", "Run"),
            "generated v5 external-pack factory");
    }

    private static void Rmf2V5GeneratedExtras()
    {
        string project = Project
            .Replace("\"schemaVersion\": 1,", "\"schemaVersion\": 1, \"sourceLayout\": \"rmf2-v1\", \"validation\": { \"extraLocaleKeys\": \"allow\" },", StringComparison.Ordinal)
            .Replace("[ \"en\" ]", "[ \"en\", \"de\" ]", StringComparison.Ordinal);
        const string german = """
            x = Deutsch
            extra = {$用户}
            """;
        string source = """
            namespace Example.Localization;
            public static class V5ExtraProbe
            {
                public static string Run()
                {
                    var manager = AppTextCatalog.CreateManagerAsync("de").AsTask().GetAwaiter().GetResult();
                    var key = new global::Runic.Translations.TranslationKey("app", global::Runic.Translations.CompiledTranslationCatalog.DynamicKeyId, "extra");
                    string value = manager.Current.Format(key,
                    [
                        global::Runic.Translations.TextArgument.CreateRmf2("用户", new global::Runic.Translations.TextArgument("_", "Ada")),
                    ]);
                    int id = global::System.Linq.Enumerable.Single(
                        AppTextCatalog.CreateExternalPackContract("de").Messages,
                        message => message.Key.Name == "extra").Key.Id;
                    return value + "|" + id.ToString(global::System.Globalization.CultureInfo.InvariantCulture);
                }
            }
            """;
        GeneratorRun run = GeneratorTestHost.RunRmf2V5WithConsumer(source, ProjectInput(project),
            new TestInput("C:/repo/translations/en.rmf2", "Rmf2", "x = English"),
            new TestInput("C:/repo/translations/de.rmf2", "Rmf2", german));
        Assert.Equal("Ada|1", Execute(run, "Example.Localization.V5ExtraProbe", "Run"),
            "generated v5 locale extra ID or contract");
        string keys = run.SingleResult.GeneratedSources.Single(item => item.HintName.EndsWith(".Keys.g.cs", StringComparison.Ordinal)).SourceText.ToString();
        Assert.True(!keys.Contains("\"extra\"", StringComparison.Ordinal), "locale extra leaked into canonical generated keys");
    }

    private static string Execute(GeneratorRun run, string typeName, string methodName)
    {
        using var stream = new MemoryStream();
        Microsoft.CodeAnalysis.Emit.EmitResult emitted = run.Compilation.Emit(stream);
        Assert.True(emitted.Success, string.Join("\n", emitted.Diagnostics));
        Assembly assembly = Assembly.Load(stream.ToArray());
        MethodInfo method = assembly.GetType(typeName, throwOnError: true)!.GetMethod(methodName, BindingFlags.Public | BindingFlags.Static)!;
        return (string)method.Invoke(null, null)!;
    }

    private static string Constant(GeneratorRun run, string name)
    {
        IFieldSymbol field = (IFieldSymbol)run.Compilation.GetTypeByMetadataName("Example.Localization.AppTextCatalog")!.GetMembers(name).Single();
        return (string)field.ConstantValue!;
    }

    private static string PathMember(params string[] segments) => string.Join("_", segments.Select(Encoded));
    private static string Encoded(string value) => "r_" + Convert.ToHexStringLower(Encoding.UTF8.GetBytes(value.Normalize(NormalizationForm.FormC)));
    private static string Quote(string value) => "\"" + value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal) + "\"";

    private static TestInput ProjectInput(string text = Project, string path = "C:/repo/translations/runic.json") =>
        new(path, "Project", text);

    private static TestInput MessageInput(string text = Message, string path = "C:/repo/translations/en/FilesDeleted.mf2") =>
        new(path, "Mf2", text);

    private static void GroupedTomlGenerationCompiles()
    {
        string project = Project.Replace("\"schemaVersion\": 1,", "\"schemaVersion\": 1, \"sourceLayout\": \"locale-toml\",", StringComparison.Ordinal);
        GeneratorRun legacy = GeneratorTestHost.Run(ProjectInput(), MessageInput(Message, "C:/repo/translations/en/ui_dialog_FilesDeleted.mf2"));
        string value = " = \u0027\u0027\u0027\n" + Message + "\u0027\u0027\u0027\n";
        string[] documents =
        [
            "# Dialog messages\n[ui.dialog]\nFilesDeleted" + value,
            "ui.dialog.FilesDeleted" + value,
            "[ui]\ndialog.FilesDeleted" + value,
            "ui_dialog_FilesDeleted" + value,
        ];
        foreach (string document in documents)
        {
            GeneratorRun run = GeneratorTestHost.Run(ProjectInput(project), new TestInput("C:/repo/translations/en.toml", "Toml", document));
            Assert.Equal(0, run.SingleResult.Diagnostics.Length, string.Join("\n", run.SingleResult.Diagnostics));
            Diagnostic[] errors = run.Compilation.GetDiagnostics().Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error).ToArray();
            Assert.Equal(0, errors.Length, string.Join("\n", errors.Select(static error => error.ToString())));
            Assert.Equal(Serialize(legacy), Serialize(run), "nested/dotted/flat paths preserve typed accessors and message bytes");
        }
    }

    private static void GroupedTomlCollisions()
    {
        string project = Project.Replace("\"schemaVersion\": 1,", "\"schemaVersion\": 1, \"sourceLayout\": \"locale-toml\",", StringComparison.Ordinal);
        GeneratorRun run = GeneratorTestHost.Run(ProjectInput(project),
            new TestInput("C:/repo/translations/en.toml", "Toml", "ui_Greeting = 'Hello'\n[ui]\nGreeting = 'Hallo'\n"));
        Assert.True(run.SingleResult.Diagnostics.Any(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error &&
            diagnostic.Location.GetLineSpan().Path == "translations/en.toml"), "group collision did not identify physical TOML input");
        Assert.Equal(0, run.SingleResult.GeneratedSources.Length, "ambiguous grouped identifiers generated source");
    }

    private static void TomlMembershipChanges()
    {
        string project = Project.Replace("\"schemaVersion\": 1,", "\"schemaVersion\": 1, \"sourceLayout\": \"locale-toml\",", StringComparison.Ordinal)
            .Replace(",\n  \"locales\": [ \"en\" ]", string.Empty, StringComparison.Ordinal);
        var english = new TestInput("C:/repo/translations/en.toml", "Toml", "Greeting = 'Hello'\n");
        var german = new TestInput("C:/repo/translations/de.toml", "Toml", "Greeting = 'Hallo'\n");
        GeneratorRun initial = GeneratorTestHost.Run(ProjectInput(project), english);
        GeneratorRunResult added = GeneratorTestHost.Rerun(initial, ProjectInput(project), english, german);
        Assert.Equal(0, added.Diagnostics.Length, string.Join("\n", added.Diagnostics));
        Assert.True(string.Join("\n", added.GeneratedSources.Select(static source => source.SourceText.ToString())).Contains("Hallo", StringComparison.Ordinal), "added locale was ignored");
        GeneratorRun withGerman = GeneratorTestHost.Run(ProjectInput(project), english, german);
        GeneratorRunResult removed = GeneratorTestHost.Rerun(withGerman, ProjectInput(project), english);
        Assert.Equal(0, removed.Diagnostics.Length, string.Join("\n", removed.Diagnostics));
        Assert.True(!string.Join("\n", removed.GeneratedSources.Select(static source => source.SourceText.ToString())).Contains("Hallo", StringComparison.Ordinal), "removed locale survived");
    }

    private static void TomlGenerationCompiles()
    {
        string project = Project.Replace("\"schemaVersion\": 1,", "\"schemaVersion\": 1, \"sourceLayout\": \"locale-toml\",", StringComparison.Ordinal);
        GeneratorRun run = GeneratorTestHost.Run(ProjectInput(project),
            new TestInput("C:/repo/translations/en.toml", "Toml", "FilesDeleted = \u0027\u0027\u0027\n" + Message + "\u0027\u0027\u0027\n"));
        Assert.Equal(0, run.SingleResult.Diagnostics.Length, string.Join("\n", run.SingleResult.Diagnostics));
        Assert.Equal(4, run.SingleResult.GeneratedSources.Length, "TOML generated sources");
        Diagnostic[] errors = run.Compilation.GetDiagnostics().Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error).ToArray();
        Assert.Equal(0, errors.Length, string.Join("\n", errors.Select(static error => error.ToString())));
        Assert.Equal(Serialize(GeneratorTestHost.Run(ProjectInput(), MessageInput())), Serialize(run), "container-independent generated bytes");
    }

    private static void TomlDiagnosticLocation()
    {
        string project = Project.Replace("\"schemaVersion\": 1,", "\"schemaVersion\": 1, \"sourceLayout\": \"locale-toml\",", StringComparison.Ordinal);
        GeneratorRun run = GeneratorTestHost.Run(ProjectInput(project),
            new TestInput("C:/repo/translations/en.toml", "Toml", "Greeting = [1, 2]\n"));
        Assert.True(run.SingleResult.Diagnostics.Any(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error &&
            diagnostic.Location.GetLineSpan().Path == "translations/en.toml"), "TOML error did not identify its physical input");
        Assert.Equal(0, run.SingleResult.GeneratedSources.Length, "invalid TOML output");
    }

    private static void ValidGenerationCompiles()
    {
        GeneratorRun run = GeneratorTestHost.Run(ProjectInput(), MessageInput());
        Assert.Equal(0, run.SingleResult.Diagnostics.Length, "generator diagnostics");
        Assert.Equal(
            "AppText.Accessors.g.cs|AppText.CatalogData.g.cs|AppText.Keys.g.cs|AppText.Registration.g.cs",
            string.Join("|", HintNames(run)),
            "hint files");
        Diagnostic[] errors = run.Compilation.GetDiagnostics().Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error).ToArray();
        Assert.Equal(0, errors.Length, errors.Length == 0 ? "generated compilation" : string.Join(Environment.NewLine, errors.Select(static error => error.ToString())));
        string allText = string.Join("\n", run.SingleResult.GeneratedSources.Select(static source => source.SourceText.ToString()));
        Assert.True(allText.Contains("RuntimeAbiVersion = 1", StringComparison.Ordinal), "generated ABI marker missing");
        Assert.True(allText.Contains("GeneratorVersion = 1", StringComparison.Ordinal), "generator version marker missing");
        Assert.True(!allText.Contains("C:/repo", StringComparison.OrdinalIgnoreCase), "absolute path leaked into generated source");
    }

    private static void DiagnosticLocation()
    {
        GeneratorRun run = GeneratorTestHost.Run(
            ProjectInput(),
            MessageInput("Hello\n", "C:/repo/translations/en/Bad-Key.mf2"));
        Diagnostic diagnostic = run.SingleResult.Diagnostics.Single(static item => item.Id == "RTR0006");
        Assert.Equal("translations/en/Bad-Key.mf2", diagnostic.Location.GetLineSpan().Path, "diagnostic path");
    }

    private static void MultipleProjects()
    {
        GeneratorRun run = GeneratorTestHost.Run(
            ProjectInput(),
            ProjectInput(Project.Replace("\"app\"", "\"admin\"", StringComparison.Ordinal), "C:/repo/admin/runic.json"),
            MessageInput());
        Diagnostic diagnostic = run.SingleResult.Diagnostics.Single(static item => item.Id == "RTR0002");
        Assert.True(diagnostic.GetMessage(CultureInfo.InvariantCulture).Contains("Exactly one", StringComparison.Ordinal), "multiple-project message");
        Assert.Equal(0, run.SingleResult.GeneratedSources.Length, "multiple-project generated sources");
    }

    private static void DeterministicInputOrder()
    {
        TestInput project = ProjectInput();
        TestInput message = MessageInput();
        Assert.Equal(
            Serialize(GeneratorTestHost.Run(project, message)),
            Serialize(GeneratorTestHost.Run(message, project)),
            "generated bytes by input order");
    }

    private static void UnmarkedInputsAreIgnored()
    {
        GeneratorRun run = GeneratorTestHost.Run(new TestInput("C:/repo/random.json", "Other", "not json"));
        Assert.Equal(0, run.SingleResult.Diagnostics.Length, "ignored diagnostics");
        Assert.Equal(0, run.SingleResult.GeneratedSources.Length, "ignored generated sources");
    }

    private static void IncrementalTrackingIsEnabled()
    {
        GeneratorRun run = GeneratorTestHost.Run(ProjectInput(), MessageInput());
        ImmutableDictionary<string, ImmutableArray<IncrementalGeneratorRunStep>> steps = run.SingleResult.TrackedSteps;
        Assert.True(steps.ContainsKey("TranslationInputs"), "input tracking step missing");
        Assert.True(steps.ContainsKey("TranslationCompilation"), "compilation tracking step missing");
        GeneratorRunResult rerun = run.Driver.RunGenerators(run.InputCompilation).GetRunResult().Results.Single();
        Assert.True(
            rerun.TrackedSteps["TranslationInputs"].SelectMany(static step => step.Outputs)
                .All(static output => output.Reason == IncrementalStepRunReason.Cached),
            "unchanged additional inputs were not cached");
    }

    private static void MismatchedRuntimeAbi()
    {
        GeneratorRun run = GeneratorTestHost.Run(RuntimeReferenceMode.Mismatched, ProjectInput(), MessageInput());
        Diagnostic diagnostic = run.SingleResult.Diagnostics.Single(static item => item.Id == "RTR0024");
        Assert.Equal(
            "Referenced Runic.Translations runtime ABI version 2 is incompatible with generated ABI version 1.",
            diagnostic.GetMessage(CultureInfo.InvariantCulture),
            "mismatched ABI message");
        Assert.Equal(0, run.SingleResult.GeneratedSources.Length, "mismatched ABI generated sources");
    }

    private static void MissingRuntimeAbi()
    {
        GeneratorRun run = GeneratorTestHost.Run(RuntimeReferenceMode.Missing, ProjectInput(), MessageInput());
        Diagnostic diagnostic = run.SingleResult.Diagnostics.Single(static item => item.Id == "RTR0024");
        Assert.Equal(
            "Referenced Runic.Translations runtime ABI is missing; generated code requires ABI version 1.",
            diagnostic.GetMessage(CultureInfo.InvariantCulture),
            "missing ABI message");
        Assert.Equal(0, run.SingleResult.GeneratedSources.Length, "missing ABI generated sources");
    }

    private static void WindowsDeviceHintStem()
    {
        GeneratorRun run = GeneratorTestHost.Run(
            ProjectInput(Project.Replace("AppText", "CON", StringComparison.Ordinal)),
            MessageInput());
        Diagnostic diagnostic = run.SingleResult.Diagnostics.Single(static item => item.Id == "RTR0018");
        Assert.Equal("translations/runic.json", diagnostic.Location.GetLineSpan().Path, "device diagnostic path");
        Assert.Equal(0, run.SingleResult.GeneratedSources.Length, "device generated sources");
    }

    private static string[] HintNames(GeneratorRun run) => run.SingleResult.GeneratedSources
        .Select(static source => source.HintName)
        .OrderBy(static name => name, StringComparer.Ordinal)
        .ToArray();

    private static string Serialize(GeneratorRun run) => string.Join(
        "\u001e",
        run.SingleResult.GeneratedSources
            .OrderBy(static source => source.HintName, StringComparer.Ordinal)
            .Select(static source => source.HintName + "\u001f" + source.SourceText.ToString()));
}
