using System;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Runic.Translations.Generator.Tests;

/// <summary>The readable C# surface and typed slots (W220-002, design note W220-001 sections 3 to 9).</summary>
internal static class GeneratorReadableTests
{
    private const string Project = """
        {
          "schemaVersion": 1,
          "catalog": "app",
          "code": { "namespace": "Example.Translations", "className": "AppText" },
          "baseLocale": "en",
          "locales": [ "en", "de" ],
          "markup": { "slots": { "checkout_help": { "retry": { "min": 0, "max": 1 } } } }
        }
        """;

    private const string English = """
        application {
          title = AppText
        }
        greeting = Hello {$name}
        profile {
          badge = Badge for {$user-name}
        }
        cart {
          items =
            .input {$count :integer}
            .match $count
            one {{One item}}
            * {{{$count} items}}
        }
        checkout {
          help = Read the {#link ref=guide}guide{/link} or {#action ref=retry}retry{/action}.
        }
        """;

    private const string German = """
        application {
          title = AppText
        }
        greeting = Hallo {$name}
        profile {
          badge = Abzeichen für {$user-name}
        }
        cart {
          items =
            .input {$count :integer}
            .match $count
            one {{Ein Artikel}}
            * {{{$count} Artikel}}
        }
        checkout {
          help = Lies die {#link ref=guide}Anleitung{/link}.
        }
        """;

    // Section 3 of the design note, generated for the source above.
    private const string Snapshot = """
        // <auto-generated />
        #nullable enable
        #pragma warning disable CS1591

        namespace Example.Translations;

        public sealed partial class @AppText
        {
            private global::@Example.@Translations.@AppTextMessages? __readable;

            /// <summary>Readable accessors for the app translation catalog.</summary>
            public global::@Example.@Translations.@AppTextMessages Messages => this.__readable ??= new global::@Example.@Translations.@AppTextMessages(this);
        }

        /// <summary>Readable accessors for the app translation catalog. Each member forwards to its encoded accessor.</summary>
        public sealed class @AppTextMessages
        {
            /// <summary>The readable C# name policy version of this surface.</summary>
            public const int ReadableNameVersion = 1;
            private readonly global::@Example.@Translations.@AppText __text;

            internal @AppTextMessages(global::@Example.@Translations.@AppText text) => this.__text = text;

            /// <summary>Formats <c>application.title</c>.</summary>
            public string @application_title => this.__text.r_6170706c69636174696f6e_r_7469746c65;

            /// <summary>Formats <c>cart.items</c>.</summary>
            public string @cart_items(long @count) =>
                this.__text.r_63617274_r_6974656d73(r_636f756e74: @count);

            /// <summary>Formats <c>checkout.help</c>.</summary>
            public global::Runic.Translations.LocalizedTextContent<global::@Example.@Translations.@AppTextSlots.@checkout_help> @checkout_help => new(this.__text.r_636865636b6f7574_r_68656c70);

            /// <summary>Formats <c>greeting</c>.</summary>
            public string @greeting(string @name) =>
                this.__text.r_6772656574696e67(r_6e616d65: @name);

            /// <summary>Formats <c>profile.badge</c>.</summary>
            public string @profile_badge(string @r_757365722d6e616d65) =>
                this.__text.r_70726f66696c65_r_6261646765(r_757365722d6e616d65: @r_757365722d6e616d65);
        }

        /// <summary>Typed slot bindings for the structured messages of the app translation catalog.</summary>
        public static class @AppTextSlots
        {
            /// <summary>Slot bindings for <c>checkout.help</c>.</summary>
            public sealed class @checkout_help : global::Runic.Translations.IRmf2SlotBindings<global::@Example.@Translations.@AppTextSlots.@checkout_help>
            {
                /// <summary>Binds every slot. Use named arguments: slots of the same kind share a type.</summary>
                public @checkout_help(global::Runic.Translations.InlineLinkBinding @guide, global::Runic.Translations.InlineActionBinding @retry)
                {
                    this.@guide = @guide ?? throw new global::System.ArgumentNullException("guide");
                    this.@retry = @retry ?? throw new global::System.ArgumentNullException("retry");
                }
                /// <summary>Binding for slot <c>guide</c>.</summary>
                public global::Runic.Translations.InlineLinkBinding @guide { get; }
                /// <summary>Binding for slot <c>retry</c>.</summary>
                public global::Runic.Translations.InlineActionBinding @retry { get; }
                static string global::Runic.Translations.IRmf2SlotBindings<global::@Example.@Translations.@AppTextSlots.@checkout_help>.MessageKey => "checkout_help";
                void global::Runic.Translations.IRmf2SlotBindings<global::@Example.@Translations.@AppTextSlots.@checkout_help>.CopyTo(global::System.Collections.Generic.IDictionary<string, global::Runic.Translations.MarkupBinding> __destination)
                {
                    __destination.Add("guide", this.@guide);
                    __destination.Add("retry", this.@retry);
                }
            }
        }
        """;

    internal static void Register(TestRunner runner)
    {
        runner.Add("readable surface snapshot matches the design shape", ReadableSnapshot);
        runner.Add("readable surface forwards to the encoded surface in every locale", ReadableEqualsEncoded);
        runner.Add("readable surface compiles identifier edge cases under warnings as errors", IdentifierEdgeCases);
        runner.Add("typed slots reject wrong kinds, missing (including min:0), misspelled and foreign slots at the Bind argument", CompileFailures);
        runner.Add("readable surface needs the runtime capability and reports RTR0068 otherwise", RuntimeCapability);
        runner.Add("readable surface leaves reserved messages encoded-only with RTR0069", ReservedMessages);
        runner.Add("readable surface stays reflection-free and keeps the encoded files", ReflectionFreeAndAdditive);
    }

    private static TestInput ProjectInput(string text = Project) => new("C:/repo/translations/runic.json", "Project", text);
    private static TestInput EnglishInput(string text = English) => new("C:/repo/translations/en.rmf2", "Rmf2", text);
    private static TestInput GermanInput(string text = German) => new("C:/repo/translations/de.rmf2", "Rmf2", text);

    private static string Readable(GeneratorRun run) =>
        run.SingleResult.GeneratedSources.Single(source => source.HintName == "AppText.Readable.g.cs").SourceText.ToString();

    private static void ReadableSnapshot()
    {
        GeneratorRun run = GeneratorTestHost.Run(ProjectInput(), EnglishInput(), GermanInput());
        Assert.Equal(0, run.SingleResult.Diagnostics.Length, string.Join("\n", run.SingleResult.Diagnostics));
        Assert.Equal(Snapshot + "\n", Readable(run), "readable snapshot");
    }

    private static void ReadableEqualsEncoded()
    {
        string title = Path("application", "title"), greeting = Path("greeting"), badge = Path("profile", "badge");
        string items = Path("cart", "items"), help = Path("checkout", "help");
        string userName = Encoded("user-name");
        string source = $$"""
            namespace Example.Consumer;
            using System;
            using System.Collections.Generic;
            using Example.Translations;
            using Runic.Translations;

            public static class Probe
            {
                public static string Run()
                {
                    ITranslationManager manager = AppTextCatalog.CreateManagerAsync("en").AsTask().GetAwaiter().GetResult();
                    var text = new AppText(manager);
                    var renderer = new Rmf2InlineRenderer(AppTextCatalog.Rmf2MarkupContract);
                    var guide = new InlineLinkBinding(new Uri("https://example.test/guide"));
                    var retry = new InlineActionBinding(() => { });
                    var output = new List<string>();
                    foreach (string locale in new[] { "en", "de" })
                    {
                        manager.SetLocaleAsync(locale).AsTask().GetAwaiter().GetResult();
                        Require(ReferenceEquals(text.Messages, text.Messages), "facade is cached");
                        Require(text.Messages.application_title == text.{{title}}, "title");
                        Require(text.Messages.greeting(name: "Ada") == text.{{greeting}}(Ada()), "greeting");
                        Require(text.Messages.profile_badge({{userName}}: "ada") == text.{{badge}}("ada"), "badge");
                        Require(text.Messages.cart_items(count: 3) == text.{{items}}(3), "items");
                        LocalizedTextContent<AppTextSlots.checkout_help> content = text.Messages.checkout_help;
                        BoundLocalizedTextContent bound = content.Bind(new(guide: guide, retry: retry));
                        var slots = new Dictionary<string, InlineMarkupBinding> { ["guide"] = guide, ["retry"] = retry };
                        string typed = renderer.ToPlainText(bound, allowActionLabels: true);
                        Require(typed == renderer.ToPlainText("checkout_help", text.{{help}}, slots, allowActionLabels: true), "help");
                        LocalizedTextContent untyped = content;
                        Require(untyped.Locale == locale && content.Locale == locale, "content locale");
                        output.Add(text.Messages.greeting(name: "Ada") + "|" + text.Messages.profile_badge({{userName}}: "ada") + "|" +
                            text.Messages.cart_items(count: 1) + "|" + typed);
                    }
                    Require(AppTextMessages.ReadableNameVersion == 1, "version");
                    return string.Join("\n", output);
                }

                private static string Ada() => "Ada";
                private static void Require(bool condition, string message) { if (!condition) throw new InvalidOperationException(message); }
            }
            """;
        GeneratorRun run = GeneratorTestHost.RunWithConsumer(source, ProjectInput(), EnglishInput(), GermanInput());
        AssertClean(run);
        Assert.Equal("Hello Ada|Badge for ada|One item|Read the guide or retry.\nHallo Ada|Abzeichen für ada|Ein Artikel|Lies die Anleitung.",
            Execute(run, "Example.Consumer.Probe"), "readable execution");
    }

    private static void IdentifierEdgeCases()
    {
        const string resources = """
            help = {#link}Go{/link}
            extension = {$value} {#link ref=d}d{/link}{#link ref=destination}x{/link}
            field = Field
            allows = {$class}
            class = {#action ref=__destination}A{/action}{#link ref=MessageKey}B{/link}{#icon ref=CopyTo/}
            value = {#link ref=help-link}Help{/link}{#link ref=|app:x|}X{/link}
            hostile =
              .input {$__proto__ :string}
              .input {$constructor :string}
              .input {$user-name :string}
              .input {$café :string}
              .input {$用户 :string}
              {{{$__proto__}|{$constructor}|{$user-name}|{$café}|{$用户}}}
            plain = {#strong}Bold{/strong}
            """;
        string source = $$"""
            namespace Example.Consumer;
            using System;
            using Example.Translations;
            using Runic.Translations;

            public static class Probe
            {
                public static string Run()
                {
                    ITranslationManager manager = AppTextCatalog.CreateManagerAsync().AsTask().GetAwaiter().GetResult();
                    AppTextMessages m = new AppText(manager).Messages;
                    var link = new InlineLinkBinding(new Uri("https://example.test"));
                    var action = new InlineActionBinding(() => { });
                    var icon = new InlineIconBinding(new object(), true);
                    var renderer = new Rmf2InlineRenderer(AppTextCatalog.Rmf2MarkupContract);
                    string help = renderer.ToPlainText(m.help.Bind(new(link: link)));
                    string extension = renderer.ToPlainText(m.extension(value: "v").Bind(new(d: link, destination: link)));
                    string keywords = m.field + "|" + m.allows(@class: "c");
                    string @class = renderer.ToPlainText(m.@class.Bind(new(__destination: action, MessageKey: link, CopyTo: icon)), allowActionLabels: true);
                    string value = renderer.ToPlainText(m.value.Bind(new({{Encoded("help-link")}}: link, {{Encoded("app:x")}}: link)));
                    string hostile = m.hostile(__proto__: "p", constructor: "c", {{Encoded("user-name")}}: "u", {{Encoded("café")}}: "e", {{Encoded("用户")}}: "y");
                    string plain = renderer.ToPlainText(m.plain.Bind(new()));
                    return string.Join("/", help, extension, keywords, @class, value, hostile, plain);
                }
            }
            """;
        GeneratorRun run = GeneratorTestHost.RunWithConsumer(source, ProjectInput(Project
            .Replace(", \"de\"", "", StringComparison.Ordinal).Replace("\"checkout_help\": { \"retry\": { \"min\": 0, \"max\": 1 } }", "", StringComparison.Ordinal)),
            EnglishInput(resources));
        AssertClean(run);
        Assert.Equal("Go/v dx/Field|c/AB/HelpX/p|c|u|e|y/Bold", Execute(run, "Example.Consumer.Probe"), "edge-case execution");
    }

    private static void CompileFailures()
    {
        const string resources = """
            help = {#link ref=guide}Guide{/link} {#action ref=retry}Retry{/action}
            other = {#link ref=guide}Other{/link}
            """;
        string project = Project.Replace(", \"de\"", "", StringComparison.Ordinal).Replace("checkout_help", "help", StringComparison.Ordinal);
        (string Call, string Id)[] cases =
        [
            ("text.Messages.help.Bind(new(guide: action, retry: action))", "CS1503"),
            ("text.Messages.help.Bind(new(guide: link))", "CS7036"),
            ("text.Messages.help.Bind(new(guide: link, retyr: action))", "CS1739"),
            ("text.Messages.help.Bind(new AppTextSlots.other(guide: link))", "CS1503"),
        ];
        foreach ((string call, string id) in cases)
        {
            string source = """
                namespace Example.Consumer;
                using System;
                using Example.Translations;
                using Runic.Translations;
                public static class Probe
                {
                    public static BoundLocalizedTextContent Run(AppText text, InlineLinkBinding link, InlineActionBinding action) =>
                        CALL;
                }
                """.Replace("CALL", call, StringComparison.Ordinal);
            GeneratorRun run = GeneratorTestHost.RunWithConsumer(source, ProjectInput(project), EnglishInput(resources));
            Assert.Equal(0, run.SingleResult.Diagnostics.Length, string.Join("\n", run.SingleResult.Diagnostics));
            Diagnostic[] errors = run.Compilation.GetDiagnostics().Where(static item => item.Severity == DiagnosticSeverity.Error).ToArray();
            Assert.Equal(id, string.Join(",", errors.Select(static item => item.Id)), call);
            // Every error is reported inside the Bind argument.
            int argument = source.IndexOf(".Bind(", StringComparison.Ordinal) + ".Bind(".Length;
            TextSpan span = errors[0].Location.SourceSpan;
            Assert.True(ReferenceEquals(errors[0].Location.SourceTree, run.InputCompilation.SyntaxTrees.Single()), "error outside the consumer: " + errors[0]);
            Assert.True(span.Start >= argument && span.End <= source.LastIndexOf(')'), call + ": " + errors[0]);
        }
    }

    private static void RuntimeCapability()
    {
        const string consumer = """
            namespace Example.Consumer;
            public static class Probe
            {
                public static string Run(Example.Translations.AppText text) => text.r_6772656574696e67(r_6e616d65: "Ada");
            }
            """;
        foreach (RuntimeReferenceMode mode in new[] { RuntimeReferenceMode.Rmf2V2, RuntimeReferenceMode.ProjectReferenceRmf2V2 })
        {
            GeneratorRun run = GeneratorTestHost.RunWithConsumer(mode, consumer, ProjectInput(), EnglishInput(), GermanInput());
            Diagnostic diagnostic = GeneratorTestHost.Run(mode, ProjectInput(), EnglishInput(), GermanInput()).SingleResult.Diagnostics.Single();
            Assert.Equal("RTR0068", diagnostic.Id, mode + ": diagnostic");
            Assert.Equal(DiagnosticSeverity.Warning, diagnostic.Severity, mode + ": severity");
            Assert.True(ReferenceEquals(TranslationsDiagnostics.ReadableSurfaceUnsupported, diagnostic.Descriptor), mode + ": descriptor");
            // Under TreatWarningsAsErrors, RTR0068 itself fails the build; it stays a warning by default.
            Assert.Equal(DiagnosticSeverity.Error, run.SingleResult.Diagnostics.Single().Severity, mode + ": warnings as errors");
            Assert.Equal("AppText.Accessors.g.cs|AppText.CatalogData.g.cs|AppText.Keys.g.cs|AppText.Registration.g.cs",
                string.Join("|", run.SingleResult.GeneratedSources.Select(static item => item.HintName).Order(StringComparer.Ordinal)), mode + ": hint files");

            // The encoded files the old runtime got still compile, with the consumer, against a real runtime.
            Compilation real = run.InputCompilation
                .RemoveReferences(run.InputCompilation.References.Where(static reference => reference is PortableExecutableReference { FilePath: null } ||
                    reference is CompilationReference))
                .AddReferences(MetadataReference.CreateFromFile(typeof(TranslationKey).Assembly.Location))
                .AddSyntaxTrees(run.SingleResult.GeneratedSources.Select(static item => item.SyntaxTree));
            Diagnostic[] problems = real.GetDiagnostics().Where(static item => item.Severity >= DiagnosticSeverity.Warning).ToArray();
            Assert.Equal(0, problems.Length, mode + ": " + string.Join("\n", problems.Select(static item => item.ToString())));
        }
        foreach (RuntimeReferenceMode mode in new[] { RuntimeReferenceMode.Rmf2V2Typed, RuntimeReferenceMode.ProjectReferenceRmf2V2Typed })
        {
            GeneratorRun run = GeneratorTestHost.Run(mode, ProjectInput(), EnglishInput(), GermanInput());
            Assert.Equal(0, run.SingleResult.Diagnostics.Length, mode + ": " + string.Join("\n", run.SingleResult.Diagnostics));
            Assert.True(run.SingleResult.GeneratedSources.Any(static item => item.HintName == "AppText.Readable.g.cs"), mode + ": readable file");
        }
    }

    private static void ReservedMessages()
    {
        string source = $$"""
            namespace Example.Consumer;
            public static class Probe
            {
                public static string Run(Example.Translations.AppText text) =>
                    text.Messages.kept + text.{{Path("ToString")}};
            }
            """;
        string project = Project.Replace(", \"de\"", "", StringComparison.Ordinal)
            .Replace("\"checkout_help\": { \"retry\": { \"min\": 0, \"max\": 1 } }", "", StringComparison.Ordinal);
        TestInput english = EnglishInput("ToString = Reserved\nkept = Kept\n");
        GeneratorRun plain = GeneratorTestHost.Run(ProjectInput(project), english);
        Diagnostic warning = plain.SingleResult.Diagnostics.Single();
        Assert.Equal("RTR0069", warning.Id, "diagnostic");
        Assert.Equal(DiagnosticSeverity.Warning, warning.Severity, "severity");
        Assert.True(ReferenceEquals(TranslationsDiagnostics.ReadableNameReserved, warning.Descriptor), "RTR0069 descriptor");
        Assert.Equal("translations/en.rmf2", warning.Location.GetLineSpan().Path, "RTR0069 path");
        Assert.Equal(0, warning.Location.GetLineSpan().StartLinePosition.Line, "RTR0069 line");
        Assert.True(!Readable(plain).Contains("@ToString", StringComparison.Ordinal), "Reserved message reached the readable surface.");

        // The consumer still compiles; under warnings as errors the compiler options escalate RTR0069 itself.
        GeneratorRun run = GeneratorTestHost.RunWithConsumer(source, ProjectInput(project), english);
        Assert.Equal(DiagnosticSeverity.Error, run.SingleResult.Diagnostics.Single().Severity, "escalated severity");
        Diagnostic[] errors = run.Compilation.GetDiagnostics().Where(static item => item.Severity >= DiagnosticSeverity.Warning).ToArray();
        Assert.Equal(0, errors.Length, string.Join("\n", errors.Select(static item => item.ToString())));

        // A class named like a facade member keeps building with its encoded surface only.
        GeneratorRun messages = GeneratorTestHost.RunWithConsumer("""
            namespace Example.Consumer;
            public static class Probe
            {
                public static string Run(Example.Translations.Messages text) => text.r_6b657074;
            }
            """, ProjectInput(project.Replace("\"AppText\"", "\"Messages\"", StringComparison.Ordinal)), EnglishInput("kept = Kept\n"));
        Assert.Equal("RTR0069", messages.SingleResult.Diagnostics.Single().Id, "class-name diagnostic");
        Assert.Equal("Messages.Accessors.g.cs|Messages.CatalogData.g.cs|Messages.Keys.g.cs|Messages.Registration.g.cs",
            string.Join("|", messages.SingleResult.GeneratedSources.Select(static item => item.HintName).Order(StringComparer.Ordinal)), "class-name hint files");
        Diagnostic[] classNameProblems = messages.Compilation.GetDiagnostics().Where(static item => item.Severity >= DiagnosticSeverity.Warning).ToArray();
        Assert.Equal(0, classNameProblems.Length, string.Join("\n", classNameProblems.Select(static item => item.ToString())));
    }

    private static void ReflectionFreeAndAdditive()
    {
        GeneratorRun run = GeneratorTestHost.Run(ProjectInput(), EnglishInput(), GermanInput());
        string readable = Readable(run);
        Assert.True(!readable.Contains("System.Reflection", StringComparison.Ordinal) && !readable.Contains("typeof(", StringComparison.Ordinal) &&
            !readable.Contains("Activator", StringComparison.Ordinal), "The readable output uses reflection.");
        Assert.Equal("AppText.Accessors.g.cs|AppText.CatalogData.g.cs|AppText.Keys.g.cs|AppText.Readable.g.cs|AppText.Registration.g.cs",
            string.Join("|", run.SingleResult.GeneratedSources.Select(static item => item.HintName).Order(StringComparer.Ordinal)), "hint files");
        // The encoded files are the same with and without the readable surface.
        GeneratorRun old = GeneratorTestHost.Run(RuntimeReferenceMode.Rmf2V2, ProjectInput(), EnglishInput(), GermanInput());
        foreach (GeneratedSourceResult encoded in old.SingleResult.GeneratedSources)
            Assert.Equal(encoded.SourceText.ToString(), run.SingleResult.GeneratedSources.Single(item => item.HintName == encoded.HintName).SourceText.ToString(), encoded.HintName);
    }

    private static void AssertClean(GeneratorRun run)
    {
        Assert.Equal(0, run.SingleResult.Diagnostics.Length, string.Join("\n", run.SingleResult.Diagnostics));
        Diagnostic[] problems = run.Compilation.GetDiagnostics().Where(static item => item.Severity >= DiagnosticSeverity.Warning).ToArray();
        Assert.Equal(0, problems.Length, string.Join("\n", problems.Select(static item => item.ToString())));
    }

    private static string Execute(GeneratorRun run, string typeName)
    {
        using var stream = new MemoryStream();
        Microsoft.CodeAnalysis.Emit.EmitResult emitted = run.Compilation.Emit(stream);
        Assert.True(emitted.Success, string.Join("\n", emitted.Diagnostics));
        Assembly assembly = Assembly.Load(stream.ToArray());
        MethodInfo method = assembly.GetType(typeName, throwOnError: true)!.GetMethod("Run", BindingFlags.Public | BindingFlags.Static)!;
        return (string)method.Invoke(null, null)!;
    }

    private static string Path(params string[] segments) => string.Join("_", segments.Select(Encoded));
    private static string Encoded(string value) => "r_" + Convert.ToHexStringLower(Encoding.UTF8.GetBytes(value.Normalize(NormalizationForm.FormC)));
}
