<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../eng/build/translations.props" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <CentralPackageVersionOverrideEnabled>true</CentralPackageVersionOverrideEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" VersionOverride="5.9.0" PrivateAssets="all" />
    <ProjectReference Include="..\..\..\packages\dotnet\Runic.Translations.Generator\Runic.Translations.Generator.csproj" />
    <ProjectReference Include="..\..\..\packages\dotnet\Runic.Translations\Runic.Translations.csproj" />
  </ItemGroup>
  <Import Project="../../../eng/build/translations.targets" />
</Project>
