import { readFile, writeFile } from "node:fs/promises";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const sourcePath = resolve(
  root,
  "specs/translations/cldr/runic-subset-48.2.json",
);
const registryPath = resolve(
  root,
  "tools/Runic.Translations.Compiler/TranslationCapabilityRegistry.cs",
);
const runtimePath = resolve(
  root,
  "packages/dotnet/Runic.Translations/Formatting/GeneratedLocaleData.cs",
);
const matrixPath = resolve(root, "specs/translations/capabilities-v1.json");
// Capability support is declared for the next translations preview; package
// versions are advanced separately by the release tooling.
const releaseTarget = "0.4.0-preview.1";
const check = process.argv.slice(2).includes("--check");

if (process.argv.length > (check ? 3 : 2))
  throw new Error("Usage: bun eng/generate-cldr.mjs [--check]");

const source = JSON.parse(await readFile(sourcePath, "utf8"));
if (!source.source || typeof source.source !== "object")
  throw new Error("CLDR subset has no source metadata.");
for (const name of [
  "cldrVersion",
  "cldrJsonTag",
  "archive",
  "archiveSha512",
  "license",
])
  if (
    typeof source.source[name] !== "string" ||
    source.source[name].length === 0
  )
    throw new Error(
      `CLDR subset source metadata '${name}' must be a non-empty string.`,
    );

const locales = source.locales;
if (!Array.isArray(locales) || locales.length === 0)
  throw new Error("CLDR subset has no locales.");
for (let index = 0; index < locales.length; index++) {
  const locale = locales[index];
  if (!locale || typeof locale !== "object" || !/^[a-z]{2,3}$/.test(locale.tag))
    throw new Error(`Invalid locale tag at index ${index}.`);
  if (
    typeof locale.cardinalRule !== "string" ||
    typeof locale.ordinalRule !== "string"
  )
    throw new Error(
      `Locale '${locale.tag}' must declare cardinal and ordinal rules.`,
    );
  if (index > 0 && locales[index - 1].tag >= locale.tag)
    throw new Error("Locales must be unique and ordinal-sorted.");
}

const cardinal = locales.map((locale) => locale.tag);
const ordinal = locales
  .filter((locale) => locale.ordinalRule)
  .map((locale) => locale.tag);
const relativeLanguages = locales
  .filter((locale) => locale.relativeTime)
  .map((locale) => locale.tag);
const esmLocaleData = JSON.stringify({
  plural: Object.fromEntries(
    locales.map((locale) => [
      locale.tag,
      [locale.cardinalRule, locale.ordinalRule],
    ]),
  ),
  relativeTime: Object.fromEntries(
    locales
      .filter((locale) => locale.relativeTime)
      .map((locale) => [locale.tag, locale.relativeTime]),
  ),
});
const csString = (value) =>
  JSON.stringify(value)
    .replaceAll("\u2028", "\\u2028")
    .replaceAll("\u2029", "\\u2029");
const csArray = (values) => `[${values.map(csString).join(", ")}]`;

const registry = `// <auto-generated by eng/generate-cldr.mjs from CLDR ${source.source.cldrVersion} />
using System;

namespace Runic.Translations.Compiler;

internal static class TranslationCapabilityRegistry
{
    internal const string CldrVersion = ${csString(source.source.cldrVersion)};
    internal const string EsmLocaleDataJson = ${csString(esmLocaleData)};
    internal static readonly string[] CardinalLanguages = ${csArray(cardinal)};
    internal static readonly string[] OrdinalLanguages = ${csArray(ordinal)};
    internal static readonly string[] RelativeTimeLanguages = ${csArray(relativeLanguages)};

    internal static bool SupportsCardinal(string locale) => Contains(CardinalLanguages, Language(locale));
    internal static bool SupportsOrdinal(string locale) => Contains(OrdinalLanguages, Language(locale));
    internal static bool SupportsRelativeTime(string locale) => Contains(RelativeTimeLanguages, Language(locale));
    private static string Language(string locale) => locale.Split('-')[0].ToLowerInvariant();
    private static bool Contains(string[] values, string value) => Array.BinarySearch(values, value, StringComparer.Ordinal) >= 0;
}
`;

const pluralRows = locales
  .map(
    (locale) =>
      `        new(${csString(locale.tag)}, ${csString(locale.cardinalRule)}, ${csString(locale.ordinalRule)}),`,
  )
  .join("\n");
const relativeRows = locales
  .filter((locale) => locale.relativeTime)
  .map((locale) => {
    const data = locale.relativeTime;
    if (
      !Array.isArray(data.autoDay) ||
      typeof data.past !== "string" ||
      typeof data.future !== "string" ||
      !data.units
    )
      throw new Error(`Relative-time data for '${locale.tag}' is incomplete.`);
    const units = Object.entries(data.units)
      .map(([unit, forms]) => {
        if (
          !Array.isArray(forms) ||
          forms.length !== 2 ||
          forms.some((form) => typeof form !== "string")
        )
          throw new Error(
            `Relative-time unit '${locale.tag}/${unit}' must have two forms.`,
          );
        return `new(${csString(unit)}, ${csString(forms[0])}, ${csString(forms[1])})`;
      })
      .join(", ");
    return `        new(${csString(locale.tag)}, ${csArray(data.autoDay)}, ${csString(data.past)}, ${csString(data.future)}, [${units}]),`;
  })
  .join("\n");
const runtime = `// <auto-generated by eng/generate-cldr.mjs from CLDR ${source.source.cldrVersion} />
#nullable enable
namespace Runic.Translations;

internal sealed record GeneratedPluralLocale(string Language, string CardinalRule, string OrdinalRule);
internal sealed record GeneratedRelativeTimeUnit(string Name, string One, string Other);
internal sealed record GeneratedRelativeTimeLocale(string Language, string[] AutoDay, string Past, string Future, GeneratedRelativeTimeUnit[] Units);

internal static class GeneratedLocaleData
{
    internal const string CldrVersion = ${csString(source.source.cldrVersion)};
    internal static readonly GeneratedPluralLocale[] PluralLocales =
    [
${pluralRows}
    ];
    internal static readonly GeneratedRelativeTimeLocale[] RelativeTimeLocales =
    [
${relativeRows}
    ];

    internal static GeneratedPluralLocale? FindPlural(string language)
    {
        for (int index = 0; index < PluralLocales.Length; index++)
            if (PluralLocales[index].Language == language) return PluralLocales[index];
        return null;
    }

    internal static GeneratedRelativeTimeLocale? FindRelativeTime(string language)
    {
        for (int index = 0; index < RelativeTimeLocales.Length; index++)
            if (RelativeTimeLocales[index].Language == language) return RelativeTimeLocales[index];
        return null;
    }
}
`;

const matrix =
  JSON.stringify(
    {
      capabilityMatrixVersion: 1,
      releaseTarget,
      cldr: {
        version: source.source.cldrVersion,
        jsonTag: source.source.cldrJsonTag,
        source: source.source.archive,
        sha512: source.source.archiveSha512,
        license: source.source.license,
      },
      backends: ["dotnet", "esm"],
      equivalence: {
        exact:
          "Backends produce the same canonical value for every accepted portable input.",
        semantic:
          "Backends preserve meaning but platform globalization can change punctuation, spacing, names, or representable decimal precision.",
      },
      formatterProfile: {
        string: { default: "exact" },
        boolean: { default: "exact" },
        integer: { plain: "exact", grouped: "semantic" },
        number: {
          plain: "semantic",
          grouped: "semantic",
          fixed: "semantic",
          percent: "semantic",
        },
        date: { iso: "exact", localized: "semantic" },
        time: { iso: "exact", localized: "semantic" },
        datetime: { iso: "semantic", localized: "semantic" },
        uuid: { d: "exact", n: "exact" },
      },
      messageProfile: {
        cardinal: "exact",
        ordinal: "exact",
        relativeTime: "semantic",
      },
      locales: locales.map((locale) => ({
        tag: locale.tag,
        cardinal: Boolean(locale.cardinalRule),
        ordinal: Boolean(locale.ordinalRule),
        relativeTime: Boolean(locale.relativeTime),
      })),
    },
    null,
    2,
  ) + "\n";

await Promise.all([
  emit(registryPath, registry),
  emit(runtimePath, runtime),
  emit(matrixPath, matrix),
]);

async function emit(file, content) {
  if (check) {
    const current = await readFile(file, "utf8").catch(() => "");
    if (current !== content)
      throw new Error(
        `${relative(root, file)} is stale; run bun eng/generate-cldr.mjs`,
      );
    return;
  }
  await writeFile(file, content, "utf8");
}
