<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <TranslationsGenerateOnBuild>true</TranslationsGenerateOnBuild>
    <TranslationsEmitEsm>true</TranslationsEmitEsm>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Runic.Translations" Version="__PACKAGE_VERSION__" />
    <PackageReference Include="Runic.Translations.Build" Version="__PACKAGE_VERSION__" PrivateAssets="all" />
  </ItemGroup>
</Project>
