using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;

namespace RunicTextResources.Build.Tests;

internal static class CliIntegrationTests
{
    private static readonly string[] MinimalArtifacts =
    [
        "MinimalText.Accessors.g.cs",
        "MinimalText.CatalogData.g.cs",
        "MinimalText.Keys.g.cs",
        "MinimalText.Registration.g.cs",
        "minimal.asset-manifest-v1.json",
        "minimal.en.locale-v1.json",
        "minimal.esm/dynamic.d.ts",
        "minimal.esm/dynamic.js",
        "minimal.esm/messages.d.ts",
        "minimal.esm/messages.js",
        "minimal.esm/messages/m$Hello.js",
        "minimal.esm/runtime.d.ts",
        "minimal.esm/runtime.js",
        "minimal.esm/transport.d.ts",
        "minimal.esm/transport.js",
        "minimal.esm/web-module-manifest-v1.json",
        "minimal.template-manifest-v1.json",
        "minimal.text-resources-v1.d.ts",
    ];

    public static void Register(TestRunner runner)
    {
        runner.Add("CLI help and invalid invocation use stable exit codes", HelpAndUsageExitCodes);
        runner.Add("CLI init creates and validates a one-locale schema-v2 project", InitCreatesOneLocaleProject);
        runner.Add("CLI init creates canonical locale files and explicit fallbacks", InitCreatesMultipleLocales);
        runner.Add("CLI init rejects conflicts without changing the target", InitConflictDoesNotWrite);
        runner.Add("CLI init supports an empty schema-v2 project", InitWithoutStarterIsValid);
        runner.Add("CLI validate succeeds without writing files", ValidateDoesNotWrite);
        runner.Add("CLI validation diagnostics return exit code one", InvalidCatalogReturnsDiagnosticExitCode);
        runner.Add("CLI generate writes the declared deterministic artifact set", GenerateWritesArtifactSet);
        runner.Add("CLI generation is byte deterministic", GenerateIsByteDeterministic);
        runner.Add("CLI verify accepts exact generated bytes", VerifyAcceptsExactOutput);
        runner.Add("CLI verify reports missing files", VerifyReportsMissing);
        runner.Add("CLI verify reports changed files", VerifyReportsChanged);
        runner.Add("CLI verify reports extra files", VerifyReportsExtra);
        runner.Add("CLI expands nested UTF-8 response files", ResponseFilesAreExpanded);
        runner.Add("CLI expands document globs deterministically", DocumentGlobsAreExpanded);
        runner.Add("CLI verify bounds comparison of oversized changed files", VerifyBoundsOversizedFiles);
        runner.Add("CLI artifact normalization rejects portable case aliases", PortableDestinationAliasesAreRejected);
        runner.Add("CLI generate rejects a reparse-point output root", CliReparsePointOutputIsRejected);
        runner.Add("CLI glob rejects a nested reparse point without traversal", GlobRejectsNestedReparsePoint);
        runner.Add("CLI verify rejects a nested output reparse point", VerifyRejectsNestedReparsePoint);
        runner.Add("CLI rejects oversized input before writing output", OversizedInputIsRejectedWithoutOutput);
        runner.Add("CLI rejects portable Windows device output components", WindowsDeviceOutputIsRejected);
        runner.Add("CLI response file accepts many explicit documents", ResponseFileAcceptsManyDocuments);
        runner.Add("CLI schema writes exact bundled versioned schemas", SchemaWritesExactSchemas);
        runner.Add("CLI preserves canonical IDs when locales add allowed extra keys", LocaleExtrasStayDataOnly);
    }

    private static void HelpAndUsageExitCodes()
    {
        using TemporaryDirectory temporary = new();
        ProcessResult help = TestFixture.RunTool(temporary, "--help");
        Assert.Equal(0, help.ExitCode);
        Assert.Contains("validate --catalog", help.StandardOutput);
        Assert.Contains("Exit codes: 0", help.StandardOutput);

        ProcessResult invalid = TestFixture.RunTool(temporary, "unknown-command");
        Assert.Equal(2, invalid.ExitCode);
        Assert.Contains("unknown command", invalid.StandardError);
    }

    private static void InitCreatesOneLocaleProject()
    {
        using TemporaryDirectory temporary = new();
        ProcessResult create = TestFixture.RunTool(
            temporary,
            "init",
            "--directory",
            "Resources",
            "--catalog",
            "product",
            "--default-locale",
            "de",
            "--namespace",
            "Customer.Product",
            "--class",
            "ProductText");

        Assert.Equal(0, create.ExitCode, create.Combined);
        Assert.Contains("created 2 text-resource file(s)", create.StandardOutput);
        Assert.Equal(
            "product.catalog.json|product.de.json",
            string.Join('|', TestFixture.RelativeFiles(temporary.Resolve("Resources"))));
        ProcessResult validate = TestFixture.RunTool(
            temporary,
            "validate",
            "--catalog",
            "Resources/product.catalog.json",
            "--documents",
            "Resources/product.de.json");
        Assert.Equal(0, validate.ExitCode, validate.Combined);
    }

    private static void InitCreatesMultipleLocales()
    {
        using TemporaryDirectory temporary = new();
        ProcessResult create = TestFixture.RunTool(
            temporary,
            "init",
            "--directory",
            "Resources",
            "--catalog",
            "product",
            "--default-locale",
            "de-de",
            "--locale",
            "en-us",
            "--locale",
            "fr:en-US",
            "--namespace",
            "Customer.Product",
            "--class",
            "ProductText");

        Assert.Equal(0, create.ExitCode, create.Combined);
        Assert.Equal(
            "product.catalog.json|product.de-DE.json|product.en-US.json|product.fr.json",
            string.Join('|', TestFixture.RelativeFiles(temporary.Resolve("Resources"))));
        string manifest = File.ReadAllText(temporary.Resolve("Resources", "product.catalog.json"), Encoding.UTF8);
        Assert.Contains("\"tag\": \"en-US\"", manifest);
        Assert.Contains("\"fallback\": \"de-DE\"", manifest);
        Assert.Contains("\"fallback\": \"en-US\"", manifest);
    }

    private static void InitConflictDoesNotWrite()
    {
        using TemporaryDirectory temporary = new();
        Directory.CreateDirectory(temporary.Resolve("Resources"));
        File.WriteAllText(temporary.Resolve("Resources", "customer.txt"), "keep", new UTF8Encoding(false));
        ProcessResult create = TestFixture.RunTool(
            temporary,
            "init",
            "--directory",
            "Resources",
            "--catalog",
            "product",
            "--default-locale",
            "de",
            "--namespace",
            "Customer.Product",
            "--class",
            "ProductText");

        Assert.Equal(2, create.ExitCode, create.Combined);
        Assert.Contains("already exists; no files were written", create.StandardError);
        Assert.Equal("customer.txt", string.Join('|', TestFixture.RelativeFiles(temporary.Resolve("Resources"))));
        Assert.Equal("keep", File.ReadAllText(temporary.Resolve("Resources", "customer.txt"), Encoding.UTF8));
    }

    private static void InitWithoutStarterIsValid()
    {
        using TemporaryDirectory temporary = new();
        ProcessResult create = TestFixture.RunTool(
            temporary,
            "init",
            "--directory",
            "Resources",
            "--catalog",
            "empty",
            "--default-locale",
            "en",
            "--namespace",
            "Customer.Empty",
            "--class",
            "EmptyText",
            "--no-starter");
        Assert.Equal(0, create.ExitCode, create.Combined);
        string document = File.ReadAllText(temporary.Resolve("Resources", "empty.en.json"), Encoding.UTF8);
        Assert.Contains("\"resources\": {}", document);
        ProcessResult validate = TestFixture.RunTool(
            temporary,
            "validate",
            "--catalog",
            "Resources/empty.catalog.json",
            "--documents",
            "Resources/empty.en.json");
        Assert.Equal(0, validate.ExitCode, validate.Combined);
    }

    private static void ValidateDoesNotWrite()
    {
        using TemporaryDirectory temporary = new();
        TestFixture.CopyMinimal(temporary);
        Dictionary<string, (long Length, DateTime LastWriteUtc)> before = TestFixture.SnapshotFiles(temporary.Path);

        ProcessResult result = TestFixture.RunTool(
            temporary,
            "validate",
            "--catalog",
            "manifest.json",
            "--documents",
            "en.json");

        Assert.Equal(0, result.ExitCode, result.Combined);
        Assert.Contains("validated 1 catalog(s) and 1 document(s)", result.StandardOutput);
        Dictionary<string, (long Length, DateTime LastWriteUtc)> after = TestFixture.SnapshotFiles(temporary.Path);
        Assert.Equal(string.Join('|', before.Keys.Order()), string.Join('|', after.Keys.Order()), "Validate created files");
        foreach (string path in before.Keys)
        {
            Assert.Equal(before[path], after[path], $"Validate changed {path}");
        }
    }

    private static void InvalidCatalogReturnsDiagnosticExitCode()
    {
        using TemporaryDirectory temporary = new();
        TestFixture.CopyMinimal(temporary);
        string manifest = File.ReadAllText(temporary.Resolve("manifest.json"), Encoding.UTF8);
        File.WriteAllText(temporary.Resolve("manifest.json"), manifest.Replace("\"schemaVersion\": 1", "\"schemaVersion\": 3", StringComparison.Ordinal), new UTF8Encoding(false));

        ProcessResult result = TestFixture.RunTool(temporary, "validate", "--catalog", "manifest.json", "--documents", "en.json");

        Assert.Equal(1, result.ExitCode, result.Combined);
        Assert.Contains("error RTR0003", result.StandardError);
        Assert.Contains("manifest.json(", result.StandardError);
    }

    private static void GenerateWritesArtifactSet()
    {
        using TemporaryDirectory temporary = new();
        TestFixture.CopyMinimal(temporary);
        ProcessResult result = TestFixture.Generate(temporary);

        Assert.Equal(0, result.ExitCode, result.Combined);
        Assert.Equal(string.Join('|', MinimalArtifacts), string.Join('|', TestFixture.RelativeFiles(temporary.Resolve("generated"))));
        foreach (string path in MinimalArtifacts)
        {
            byte[] bytes = File.ReadAllBytes(temporary.Resolve("generated", path));
            Assert.False(bytes.Length >= 3 && bytes[0] == 0xef && bytes[1] == 0xbb && bytes[2] == 0xbf, $"{path} has a UTF-8 BOM.");
            if (path.EndsWith(".json", StringComparison.Ordinal))
            {
                Assert.True(bytes.Length > 0 && bytes[^1] != (byte)'\n', $"{path} has a forbidden terminal newline.");
            }
            else
            {
                Assert.True(bytes.Length > 0 && bytes[^1] == (byte)'\n', $"{path} lacks a final LF.");
            }
        }
    }

    private static void GenerateIsByteDeterministic()
    {
        using TemporaryDirectory temporary = new();
        TestFixture.CopyMinimal(temporary);
        Assert.Equal(0, TestFixture.Generate(temporary, "first").ExitCode);
        Assert.Equal(0, TestFixture.Generate(temporary, "second").ExitCode);
        foreach (string path in MinimalArtifacts)
        {
            Assert.FileBytesEqual(temporary.Resolve("first", path), temporary.Resolve("second", path));
        }
    }

    private static void VerifyAcceptsExactOutput()
    {
        using TemporaryDirectory temporary = GeneratedFixture();
        ProcessResult result = Verify(temporary);
        Assert.Equal(0, result.ExitCode, result.Combined);
        Assert.Contains("verified 18 artifact(s)", result.StandardOutput);
    }

    private static void VerifyReportsMissing()
    {
        using TemporaryDirectory temporary = GeneratedFixture();
        File.Delete(temporary.Resolve("generated", MinimalArtifacts[0]));
        ProcessResult result = Verify(temporary);
        Assert.Equal(1, result.ExitCode, result.Combined);
        Assert.Contains($"verify: missing: {MinimalArtifacts[0]}", result.StandardError);
    }

    private static void VerifyReportsChanged()
    {
        using TemporaryDirectory temporary = GeneratedFixture();
        File.AppendAllText(temporary.Resolve("generated", MinimalArtifacts[1]), "changed", Encoding.UTF8);
        ProcessResult result = Verify(temporary);
        Assert.Equal(1, result.ExitCode, result.Combined);
        Assert.Contains($"verify: changed: {MinimalArtifacts[1]}", result.StandardError);
    }

    private static void VerifyReportsExtra()
    {
        using TemporaryDirectory temporary = GeneratedFixture();
        File.WriteAllText(temporary.Resolve("generated", "extra.txt"), "extra", new UTF8Encoding(false));
        ProcessResult result = Verify(temporary);
        Assert.Equal(1, result.ExitCode, result.Combined);
        Assert.Contains("verify: extra: extra.txt", result.StandardError);
    }

    private static void ResponseFilesAreExpanded()
    {
        using TemporaryDirectory temporary = new();
        TestFixture.CopyMinimal(temporary);
        string inner = temporary.Resolve("inner args.rsp");
        string outer = temporary.Resolve("outer.rsp");
        File.WriteAllText(
            inner,
            $"# paths containing spaces are quoted{Environment.NewLine}--catalog \"{temporary.Resolve("manifest.json")}\"{Environment.NewLine}--documents \"{temporary.Resolve("en.json")}\"{Environment.NewLine}",
            new UTF8Encoding(false));
        File.WriteAllText(outer, $"validate{Environment.NewLine}\"@{inner}\"{Environment.NewLine}", new UTF8Encoding(false));

        ProcessResult result = TestFixture.RunTool(temporary, $"@{outer}");
        Assert.Equal(0, result.ExitCode, result.Combined);
        Assert.Contains("validated 1 catalog(s)", result.StandardOutput);
    }

    private static void SchemaWritesExactSchemas()
    {
        using TemporaryDirectory temporary = new();
        ProcessResult result = TestFixture.RunTool(temporary, "schema", "--output", "schemas");
        Assert.Equal(0, result.ExitCode, result.Combined);
        string source = RepositoryPaths.Resolve("spec", "schemas");
        string[] expected = Directory.EnumerateFiles(source, "*.schema.json").Select(path => Path.GetFileName(path)!).Order(StringComparer.Ordinal).ToArray();
        Assert.Equal(string.Join('|', expected), string.Join('|', TestFixture.RelativeFiles(temporary.Resolve("schemas"))));
        foreach (string schema in expected)
        {
            Assert.FileBytesEqual(Path.Combine(source, schema), temporary.Resolve("schemas", schema));
        }
    }

    private static void DocumentGlobsAreExpanded()
    {
        using TemporaryDirectory temporary = new();
        TestFixture.CopyMinimal(temporary);
        Directory.CreateDirectory(temporary.Resolve("documents"));
        File.Move(temporary.Resolve("en.json"), temporary.Resolve("documents", "en.texts.json"));
        ProcessResult result = TestFixture.RunTool(
            temporary,
            "validate",
            "--catalog",
            "manifest.json",
            "--documents",
            "documents/*.texts.json");
        Assert.Equal(0, result.ExitCode, result.Combined);
        Assert.Contains("1 document(s)", result.StandardOutput);
    }

    private static void VerifyBoundsOversizedFiles()
    {
        using TemporaryDirectory temporary = GeneratedFixture();
        string changed = temporary.Resolve("generated", MinimalArtifacts[0]);
        using (FileStream stream = new(changed, FileMode.Open, FileAccess.Write, FileShare.None))
        {
            stream.SetLength(32L * 1024 * 1024);
        }

        ProcessResult result = Verify(temporary);
        Assert.Equal(1, result.ExitCode, result.Combined);
        Assert.Contains($"verify: changed: {MinimalArtifacts[0]}", result.StandardError);
    }

    private static void PortableDestinationAliasesAreRejected()
    {
        Assembly tool = Assembly.LoadFrom(RepositoryPaths.ToolAssembly);
        Type artifactType = tool.GetType("RunicTextResources.Tool.ToolArtifact", throwOnError: true)!;
        Type filesType = tool.GetType("RunicTextResources.Tool.ArtifactFiles", throwOnError: true)!;
        object first = Activator.CreateInstance(
            artifactType,
            BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic,
            binder: null,
            args: ["Case.txt", new byte[] { 1 }],
            culture: null)!;
        object second = Activator.CreateInstance(
            artifactType,
            BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic,
            binder: null,
            args: ["case.txt", new byte[] { 2 }],
            culture: null)!;
        Type listType = typeof(List<>).MakeGenericType(artifactType);
        object list = Activator.CreateInstance(listType)!;
        listType.GetMethod("Add")!.Invoke(list, [first]);
        listType.GetMethod("Add")!.Invoke(list, [second]);
        MethodInfo normalize = filesType.GetMethod("Normalize", BindingFlags.Static | BindingFlags.NonPublic)!;
        try
        {
            _ = normalize.Invoke(null, [list]);
            throw new InvalidOperationException("Portable case-alias collision was accepted.");
        }
        catch (TargetInvocationException exception)
        {
            Assert.Contains("RTR0020", exception.InnerException?.Message ?? string.Empty);
            Assert.Contains("collision", exception.InnerException?.Message ?? string.Empty);
        }
    }

    private static void CliReparsePointOutputIsRejected()
    {
        using TemporaryDirectory temporary = new();
        TestFixture.CopyMinimal(temporary);
        string target = temporary.Resolve("actual-output");
        string link = temporary.Resolve("linked-output");
        Directory.CreateDirectory(target);
        try
        {
            Directory.CreateSymbolicLink(link, target);
        }
        catch (Exception exception) when (exception is UnauthorizedAccessException or IOException or PlatformNotSupportedException)
        {
            return;
        }

        ProcessResult result = TestFixture.Generate(temporary, "linked-output");
        Assert.Equal(1, result.ExitCode, result.Combined);
        Assert.Contains("RTR0020", result.StandardError);
        Assert.False(Directory.EnumerateFiles(target, "*", SearchOption.AllDirectories).Any(), "CLI wrote through the rejected output link.");
    }

    private static void GlobRejectsNestedReparsePoint()
    {
        using TemporaryDirectory temporary = new();
        TestFixture.CopyMinimal(temporary);
        Directory.CreateDirectory(temporary.Resolve("documents"));
        File.Move(temporary.Resolve("en.json"), temporary.Resolve("documents", "en.json"));
        string link = temporary.Resolve("documents", "loop");
        try
        {
            Directory.CreateSymbolicLink(link, temporary.Resolve("documents"));
        }
        catch (Exception exception) when (exception is UnauthorizedAccessException or IOException or PlatformNotSupportedException)
        {
            return;
        }

        ProcessResult result = TestFixture.RunTool(
            temporary,
            "validate", "--catalog", "manifest.json", "--documents", "documents/**/*.json");
        Assert.Equal(2, result.ExitCode, result.Combined);
        Assert.Contains("reparse point", result.StandardError);
        Assert.Contains("documents/loop", result.StandardError.Replace('\\', '/'));
    }

    private static void VerifyRejectsNestedReparsePoint()
    {
        using TemporaryDirectory temporary = GeneratedFixture();
        string target = temporary.Resolve("nested-target");
        string link = temporary.Resolve("generated", "nested-link");
        Directory.CreateDirectory(target);
        File.WriteAllText(Path.Combine(target, "escaped.txt"), "outside", new UTF8Encoding(false));
        try
        {
            Directory.CreateSymbolicLink(link, target);
        }
        catch (Exception exception) when (exception is UnauthorizedAccessException or IOException or PlatformNotSupportedException)
        {
            return;
        }

        ProcessResult result = Verify(temporary);
        Assert.Equal(1, result.ExitCode, result.Combined);
        Assert.Contains("RTR0020", result.StandardError);
        Assert.Contains("reparse point", result.StandardError);
    }

    private static void OversizedInputIsRejectedWithoutOutput()
    {
        using TemporaryDirectory temporary = new();
        TestFixture.CopyMinimal(temporary);
        string document = temporary.Resolve("en.json");
        using (FileStream stream = new(document, FileMode.Open, FileAccess.Write, FileShare.None))
        {
            stream.SetLength((8L * 1024 * 1024) + 1);
        }

        ProcessResult result = TestFixture.Generate(temporary, "must-not-exist");
        Assert.Equal(1, result.ExitCode, result.Combined);
        Assert.Contains("RTR0022", result.StandardError);
        Assert.Contains("8388608", result.StandardError);
        Assert.False(Directory.Exists(temporary.Resolve("must-not-exist")), "Oversized input created an output directory.");
    }

    private static void WindowsDeviceOutputIsRejected()
    {
        using TemporaryDirectory temporary = new();
        File.WriteAllText(
            temporary.Resolve("manifest.json"),
            "{\"schemaVersion\":1,\"catalog\":\"con\",\"code\":{\"namespace\":\"RunicTextResources.Examples.Localization\",\"className\":\"DeviceText\"},\"defaultLocale\":\"en\",\"locales\":[{\"tag\":\"en\"}],\"layers\":[{\"name\":\"base\",\"priority\":0}]}",
            new UTF8Encoding(false));
        File.WriteAllText(
            temporary.Resolve("en.json"),
            "{\"schemaVersion\":1,\"catalog\":\"con\",\"locale\":\"en\",\"layer\":\"base\",\"resources\":{\"A\":\"A\"}}",
            new UTF8Encoding(false));

        ProcessResult result = TestFixture.Generate(temporary, "generated");
        Assert.Equal(1, result.ExitCode, result.Combined);
        Assert.Contains("RTR0018", result.StandardError);
        Assert.Contains("Windows-reserved generated filename stem", result.StandardError);
        Assert.False(Directory.Exists(temporary.Resolve("generated")), "Portable device-name rejection wrote output.");
    }

    private static void ResponseFileAcceptsManyDocuments()
    {
        using TemporaryDirectory temporary = new();
        const int documentCount = 96;
        File.WriteAllText(
            temporary.Resolve("manifest.json"),
            "{\"schemaVersion\":1,\"catalog\":\"many\",\"code\":{\"namespace\":\"RunicTextResources.Examples.Localization\",\"className\":\"ManyText\"},\"defaultLocale\":\"en\",\"locales\":[{\"tag\":\"en\"}],\"layers\":[{\"name\":\"base\",\"priority\":0}]}",
            new UTF8Encoding(false));
        var response = new StringBuilder()
            .AppendLine("validate")
            .AppendLine("--catalog")
            .AppendLine(CultureInfo.InvariantCulture, $"\"{temporary.Resolve("manifest.json")}\"")
            .AppendLine("--documents");
        for (int index = 0; index < documentCount; index++)
        {
            string path = temporary.Resolve($"document-{index:D3}.json");
            File.WriteAllText(
                path,
                $"{{\"schemaVersion\":1,\"catalog\":\"many\",\"locale\":\"en\",\"layer\":\"base\",\"resources\":{{\"Key{index:D3}\":\"Value {index}\"}}}}",
                new UTF8Encoding(false));
            response.AppendLine(CultureInfo.InvariantCulture, $"\"{path}\"");
        }

        string responsePath = temporary.Resolve("many-documents.rsp");
        File.WriteAllText(responsePath, response.ToString(), new UTF8Encoding(false));
        ProcessResult result = TestFixture.RunTool(temporary, $"@{responsePath}");
        Assert.Equal(0, result.ExitCode, result.Combined);
        Assert.Contains($"{documentCount} document(s)", result.StandardOutput);
    }

    private static void LocaleExtrasStayDataOnly()
    {
        using TemporaryDirectory temporary = new();
        WriteExtraFixture(temporary, includeExtra: true);
        ProcessResult withExtra = TestFixture.RunTool(
            temporary,
            "generate",
            "--catalog",
            "manifest.json",
            "--documents",
            "en.json",
            "fr.json",
            "--output",
            "with-extra",
            "--emit-csharp");
        Assert.Equal(0, withExtra.ExitCode, withExtra.Combined);

        string data = File.ReadAllText(temporary.Resolve("with-extra", "ExtraText.CatalogData.g.cs"), Encoding.UTF8);
        int canonical = data.IndexOf("CompiledTextResourceDefinition(\"A\"", StringComparison.Ordinal);
        int extra = data.IndexOf("CompiledTextResourceDefinition(\"Extra.Z\"", StringComparison.Ordinal);
        Assert.True(canonical >= 0 && extra > canonical, "Canonical ID 0 was not followed by the data-only extra ID 1.");
        Assert.Contains("}, isCanonical: true)", data[canonical..extra]);
        Assert.Contains("}, isCanonical: false)", data[extra..]);
        string keys = File.ReadAllText(temporary.Resolve("with-extra", "ExtraText.Keys.g.cs"), Encoding.UTF8);
        string accessors = File.ReadAllText(temporary.Resolve("with-extra", "ExtraText.Accessors.g.cs"), Encoding.UTF8);
        Assert.False(keys.Contains("\"Extra.Z\"", StringComparison.Ordinal), "Locale-only key leaked into generated keys.");
        Assert.False(accessors.Contains("ExtraGroup", StringComparison.Ordinal), "Locale-only key leaked into generated accessors.");

        WriteExtraFixture(temporary, includeExtra: false);
        ProcessResult withoutExtra = TestFixture.RunTool(
            temporary,
            "generate",
            "--catalog",
            "manifest.json",
            "--documents",
            "en.json",
            "fr.json",
            "--output",
            "without-extra",
            "--emit-csharp");
        Assert.Equal(0, withoutExtra.ExitCode, withoutExtra.Combined);
        string firstRegistration = File.ReadAllText(temporary.Resolve("with-extra", "ExtraText.Registration.g.cs"), Encoding.UTF8);
        string secondRegistration = File.ReadAllText(temporary.Resolve("without-extra", "ExtraText.Registration.g.cs"), Encoding.UTF8);
        Assert.Equal(ReadFingerprint(firstRegistration), ReadFingerprint(secondRegistration), "Allowed locale extras changed the canonical fingerprint");
    }

    private static void WriteExtraFixture(TemporaryDirectory temporary, bool includeExtra)
    {
        const string manifest = """
            {"schemaVersion":1,"catalog":"extra","code":{"namespace":"RunicTextResources.Examples.Localization","className":"ExtraText"},"defaultLocale":"en","locales":[{"tag":"en"},{"tag":"fr","fallback":"en"}],"layers":[{"name":"base","priority":0}],"validation":{"translationCompleteness":"allow","extraLocaleKeys":"allow"}}
            """;
        string french = includeExtra
            ? "{\"schemaVersion\":1,\"catalog\":\"extra\",\"locale\":\"fr\",\"layer\":\"base\",\"resources\":{\"A\":\"Une\",\"Extra\":{\"Z\":\"Supplément\"}}}"
            : "{\"schemaVersion\":1,\"catalog\":\"extra\",\"locale\":\"fr\",\"layer\":\"base\",\"resources\":{\"A\":\"Une\"}}";
        File.WriteAllText(temporary.Resolve("manifest.json"), manifest, new UTF8Encoding(false));
        File.WriteAllText(temporary.Resolve("en.json"), "{\"schemaVersion\":1,\"catalog\":\"extra\",\"locale\":\"en\",\"layer\":\"base\",\"resources\":{\"A\":\"A\"}}", new UTF8Encoding(false));
        File.WriteAllText(temporary.Resolve("fr.json"), french, new UTF8Encoding(false));
    }

    private static string ReadFingerprint(string registration)
    {
        const string marker = "ContractFingerprint = \"";
        int start = registration.IndexOf(marker, StringComparison.Ordinal);
        Assert.True(start >= 0, "Generated registration omitted ContractFingerprint.");
        start += marker.Length;
        int end = registration.IndexOf('"', start);
        return registration[start..end];
    }

    private static TemporaryDirectory GeneratedFixture()
    {
        TemporaryDirectory temporary = new();
        TestFixture.CopyMinimal(temporary);
        ProcessResult result = TestFixture.Generate(temporary);
        if (result.ExitCode != 0)
        {
            temporary.Dispose();
            throw new InvalidOperationException(result.Combined);
        }

        return temporary;
    }

    private static ProcessResult Verify(TemporaryDirectory temporary) => TestFixture.RunTool(
        temporary,
        "verify",
        "--catalog",
        "manifest.json",
        "--documents",
        "en.json",
        "--output",
        "generated");
}
