<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <TextResourcesGenerateOnBuild>true</TextResourcesGenerateOnBuild>
    <TextResourcesEmitEsm>true</TextResourcesEmitEsm>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="RunicTextResources" Version="__PACKAGE_VERSION__" />
    <PackageReference Include="RunicTextResources.Build" Version="__PACKAGE_VERSION__" PrivateAssets="all" />
    <PackageReference Include="RunicTextResources.Generator"
                      Version="__PACKAGE_VERSION__"
                      PrivateAssets="all"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <TextResourceCatalog Include="Resources\__CATALOG__.catalog.json" />
    <TextResourceDocument Include="Resources\__CATALOG__.__DEFAULT_LOCALE__.json" />
  </ItemGroup>
</Project>
