<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <CentralPackageVersionOverrideEnabled>false</CentralPackageVersionOverrideEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Runic.Application" Version="1.0.0-preview.1" />
    <PackageVersion Include="Runic.Application.Bridge" Version="1.0.0-preview.1" />
    <PackageVersion Include="Runic.Application.Desktop" Version="1.0.0-preview.1" />
    <PackageVersion Include="Runic.Application.Hosting" Version="1.0.0-preview.1" />
    <PackageVersion Include="Runic.CommandLine" Version="1.0.0-preview.1" />
    <PackageVersion Include="Runic.Translations" Version="1.0.0-preview.1" />
    <PackageVersion Include="Runic.Translations.Tooling" Version="1.0.0-preview.1" />
    <PackageVersion Include="Runic.Translations.Build" Version="1.0.0-preview.1" />
    <PackageVersion Include="Runic.Assets" Version="1.0.0-preview.1" />
    <PackageVersion Include="Runic.Assets.AspNetCore" Version="1.0.0-preview.1" />
    <PackageVersion Include="Runic.Assets.Desktop" Version="1.0.0-preview.1" />
  </ItemGroup>
</Project>
