[common]
cancel = 'Abbrechen'
save = 'Speichern'

[dashboard]
welcome = '''
.input {$name :string}
Willkommen zurück, {$name}
'''

[files]
selected = '''
.input {$count :integer select=plural}
.match $count
one {{Eine Datei ausgewählt}}
* {{{$count} Dateien ausgewählt}}
'''
