[common]
cancel = 'Cancel'
save = 'Save'

[dashboard]
welcome = '''
.input {$name :string}
Welcome back, {$name}
'''

[files]
selected = '''
.input {$count :integer select=plural}
.match $count
one {{One file selected}}
* {{{$count} files selected}}
'''
