common_cancel = "Annuler\n"
common_save = "Enregistrer\n"
dashboard_welcome = ".input {$name :string}\nBon retour, {$name}\n"
files_selected = ".input {$count :integer select=plural}\n.match $count\none {{Un fichier sélectionné}}\n* {{{$count} fichiers sélectionnés}}\n"
