// <auto-generated />
import definition from "./application.bridge.js";
import { materializeApplicationBridgeContract } from "@runic-artifex/application-bridge";

export const applicationBridge = materializeApplicationBridgeContract(definition, "e91f67a360e65065044415abd3f0484a8a430dab3d33cdea97afc8e696532528");
export default applicationBridge;
