using System;
using System.Collections.Generic;
using System.Text;

namespace WebUIToolkit.TextResources.Compiler.Generation;

internal static class EdgeOutputRenderer
{
    internal static TextResourceGeneratedOutput RenderLocale(CompiledTextCatalog catalog, string localeTag)
    {
        CompiledTextLocale? locale = null;
        for (int i = 0; i < catalog.Locales.Count; i++)
        {
            if (string.Equals(catalog.Locales[i].Tag, localeTag, StringComparison.Ordinal))
            {
                locale = catalog.Locales[i];
                break;
            }
        }
        if (locale is null)
            throw new ArgumentException("Locale '" + localeTag + "' is not a declared canonical locale of catalog '" + catalog.Id + "'.", nameof(localeTag));

        var json = new StringBuilder();
        json.Append("{\"artifactVersion\":").Append(TextResourceOutputRenderer.LocaleArtifactVersion)
            .Append(",\"messageGrammarVersion\":").Append(catalog.MessageGrammarVersion)
            .Append(",\"catalog\":").Append(GenerationSupport.JsonString(catalog.Id))
            .Append(",\"locale\":").Append(GenerationSupport.JsonString(locale.Tag))
            .Append(",\"contractFingerprint\":").Append(GenerationSupport.JsonString(catalog.Fingerprint))
            .Append(",\"messages\":{");
        IReadOnlyList<CompiledTextResource> resources = GenerationSupport.OrderedResources(locale.ResolvedResources);
        for (int i = 0; i < resources.Count; i++)
        {
            if (i > 0) json.Append(',');
            CompiledTextResource resource = resources[i];
            json.Append(GenerationSupport.JsonString(resource.Key)).Append(":{\"pattern\":")
                .Append(GenerationSupport.JsonString(resource.Pattern)).Append(",\"arguments\":");
            WriteJsonArguments(json, resource.Placeholders);
            json.Append('}');
        }
        json.Append("}}");
        return new TextResourceGeneratedOutput(
            TextResourceGeneratedOutputKind.LocaleJson,
            catalog.Id + "." + locale.Tag + ".locale-v1.json",
            "application/json",
            json.ToString());
    }

    internal static TextResourceGeneratedOutput RenderTemplateManifest(CompiledTextCatalog catalog)
    {
        var json = new StringBuilder();
        json.Append("{\"manifestVersion\":").Append(TextResourceOutputRenderer.TemplateManifestVersion)
            .Append(",\"messageGrammarVersion\":").Append(catalog.MessageGrammarVersion)
            .Append(",\"catalog\":").Append(GenerationSupport.JsonString(catalog.Id))
            .Append(",\"contractFingerprint\":").Append(GenerationSupport.JsonString(catalog.Fingerprint))
            .Append(",\"messages\":{");
        IReadOnlyList<CompiledTextResource> resources = GenerationSupport.OrderedResources(catalog.CanonicalResources);
        for (int i = 0; i < resources.Count; i++)
        {
            if (i > 0) json.Append(',');
            CompiledTextResource resource = resources[i];
            json.Append(GenerationSupport.JsonString(resource.Key)).Append(":{\"description\":")
                .Append(resource.Description is null ? "null" : GenerationSupport.JsonString(resource.Description))
                .Append(",\"since\":").Append(resource.Since is null ? "null" : GenerationSupport.JsonString(resource.Since))
                .Append(",\"deprecated\":").Append(resource.DeprecatedReason is null ? "null" : GenerationSupport.JsonString(resource.DeprecatedReason))
                .Append(",\"tags\":");
            WriteJsonStrings(json, resource.Tags);
            json.Append(",\"arguments\":");
            WriteJsonArguments(json, resource.Placeholders);
            json.Append('}');
        }
        json.Append("}}");
        return new TextResourceGeneratedOutput(
            TextResourceGeneratedOutputKind.TemplateManifestJson,
            catalog.Id + ".template-manifest-v1.json",
            "application/json",
            json.ToString());
    }

    internal static TextResourceGeneratedOutput RenderTypeScriptContract(CompiledTextCatalog catalog)
    {
        var writer = new GenerationWriter();
        IReadOnlyList<CompiledTextResource> resources = GenerationSupport.OrderedResources(catalog.CanonicalResources);
        string keyType = catalog.ClassName + "Key";
        string argumentsType = catalog.ClassName + "Arguments";
        string keyConstant = LowercaseFirst(catalog.ClassName) + "Keys";
        writer.Line("// <auto-generated />");
        writer.Line("// Text Resources TypeScript edge contract version " + TextResourceOutputRenderer.TypeScriptContractVersion + ".");
        writer.Blank();
        writer.Line("export declare const textResourceContractVersion: " + TextResourceOutputRenderer.TypeScriptContractVersion + ";");
        writer.Line("export declare const textResourceCatalog: " + GenerationSupport.JsonString(catalog.Id) + ";");
        writer.Line("export declare const textResourceContractFingerprint: " + GenerationSupport.JsonString(catalog.Fingerprint) + ";");
        writer.Blank();
        writer.Line("export type " + keyType + " =");
        writer.Indent();
        for (int i = 0; i < resources.Count; i++)
            writer.Line("| " + GenerationSupport.JsonString(resources[i].Key) + (i + 1 == resources.Count ? ";" : string.Empty));
        if (resources.Count == 0) writer.Line("never;");
        writer.Unindent();
        writer.Blank();
        writer.Line("export declare const " + keyConstant + ": {");
        writer.Indent();
        WriteTypeScriptMembers(writer, GenerationSupport.BuildTree(catalog), string.Empty);
        writer.Unindent();
        writer.Line("};");
        writer.Blank();
        writer.Line("export interface " + argumentsType + " {");
        writer.Indent();
        for (int i = 0; i < resources.Count; i++)
        {
            CompiledTextResource resource = resources[i];
            WriteTypeScriptDocumentation(writer, resource);
            IReadOnlyList<CompiledTextPlaceholder> placeholders = GenerationSupport.OrderedPlaceholders(resource.Placeholders);
            if (placeholders.Count == 0)
            {
                writer.Line(GenerationSupport.JsonString(resource.Key) + ": Readonly<Record<never, never>>;");
                continue;
            }
            writer.Line(GenerationSupport.JsonString(resource.Key) + ": Readonly<{");
            writer.Indent();
            for (int placeholderIndex = 0; placeholderIndex < placeholders.Count; placeholderIndex++)
            {
                CompiledTextPlaceholder placeholder = placeholders[placeholderIndex];
                writer.Line(GenerationSupport.JsonString(placeholder.Name) + ": " + GenerationSupport.TypeScriptType(placeholder.Type) + ";");
            }
            writer.Unindent();
            writer.Line("}>;");
        }
        writer.Unindent();
        writer.Line("}");
        writer.Blank();
        writer.Line("export type TextResourceArguments<K extends " + keyType + "> = " + argumentsType + "[K];");
        return new TextResourceGeneratedOutput(
            TextResourceGeneratedOutputKind.TypeScriptContract,
            catalog.Id + ".text-resources-v1.d.ts",
            "text/typescript",
            writer.ToString());
    }

    private static void WriteJsonArguments(StringBuilder json, IReadOnlyList<CompiledTextPlaceholder> placeholders)
    {
        IReadOnlyList<CompiledTextPlaceholder> ordered = GenerationSupport.OrderedPlaceholders(placeholders);
        json.Append('[');
        for (int i = 0; i < ordered.Count; i++)
        {
            if (i > 0) json.Append(',');
            CompiledTextPlaceholder placeholder = ordered[i];
            json.Append("{\"name\":").Append(GenerationSupport.JsonString(placeholder.Name))
                .Append(",\"type\":").Append(GenerationSupport.JsonString(GenerationSupport.JsonArgumentType(placeholder.Type)))
                .Append(",\"format\":").Append(GenerationSupport.JsonString(placeholder.Format)).Append('}');
        }
        json.Append(']');
    }

    private static void WriteJsonStrings(StringBuilder json, IReadOnlyList<string> values)
    {
        var ordered = new List<string>(values.Count);
        for (int i = 0; i < values.Count; i++) ordered.Add(values[i]);
        ordered.Sort(StringComparer.Ordinal);
        json.Append('[');
        for (int i = 0; i < ordered.Count; i++)
        {
            if (i > 0) json.Append(',');
            json.Append(GenerationSupport.JsonString(ordered[i]));
        }
        json.Append(']');
    }

    private static void WriteTypeScriptMembers(GenerationWriter writer, ResourceTreeNode node, string dottedPrefix)
    {
        foreach (KeyValuePair<string, ResourceTreeNode> child in node.Children)
        {
            string dotted = dottedPrefix.Length == 0 ? child.Key : dottedPrefix + "." + child.Key;
            if (child.Value.Resource is not null)
                writer.Line("readonly " + GenerationSupport.JsonString(child.Key) + ": " + GenerationSupport.JsonString(dotted) + ";");
            else
            {
                writer.Line("readonly " + GenerationSupport.JsonString(child.Key) + ": {");
                writer.Indent();
                WriteTypeScriptMembers(writer, child.Value, dotted);
                writer.Unindent();
                writer.Line("};");
            }
        }
    }

    private static void WriteTypeScriptDocumentation(GenerationWriter writer, CompiledTextResource resource)
    {
        if (resource.Description is null && resource.DeprecatedReason is null) return;
        writer.Line("/**");
        if (resource.Description is not null) writer.Line(" * " + SafeTypeScriptDocumentation(resource.Description));
        if (resource.DeprecatedReason is not null) writer.Line(" * @deprecated " + SafeTypeScriptDocumentation(resource.DeprecatedReason));
        writer.Line(" */");
    }

    private static string SafeTypeScriptDocumentation(string value)
    {
        string normalized = value.Replace("\r\n", " ").Replace('\r', ' ').Replace('\n', ' ').Replace("*/", "* /");
        var result = new StringBuilder(normalized.Length);
        for (int i = 0; i < normalized.Length; i++)
        {
            char character = normalized[i];
            bool unpairedHigh = char.IsHighSurrogate(character) &&
                (i + 1 >= normalized.Length || !char.IsLowSurrogate(normalized[i + 1]));
            bool unpairedLow = char.IsLowSurrogate(character) &&
                (i == 0 || !char.IsHighSurrogate(normalized[i - 1]));
            if ((character < ' ' && character != '\t') || unpairedHigh || unpairedLow)
                result.Append(character < ' ' ? ' ' : '\uFFFD');
            else
                result.Append(character);
        }
        return result.ToString();
    }

    private static string LowercaseFirst(string value)
    {
        if (value.Length == 0 || (value[0] < 'A' || value[0] > 'Z')) return value;
        return char.ToLowerInvariant(value[0]) + value.Substring(1);
    }
}
