// <auto-generated by eng/generate-cldr.mjs from CLDR 48.2 />
#nullable enable
namespace Runic.Translations;

internal sealed record GeneratedPluralLocale(string Language, string CardinalRule, string OrdinalRule);
internal sealed record GeneratedRelativeTimeUnit(string Name, string One, string Other);
internal sealed record GeneratedRelativeTimeLocale(string Language, string[] AutoDay, string Past, string Future, GeneratedRelativeTimeUnit[] Units);

internal static class GeneratedLocaleData
{
    internal const string CldrVersion = "48.2";
    internal static readonly GeneratedPluralLocale[] PluralLocales =
    [
        new("da", "danish", "other"),
        new("de", "integer-one", "other"),
        new("en", "integer-one", "english"),
        new("es", "one-and-million", "other"),
        new("fr", "french", "one"),
        new("it", "one-and-million", "italian"),
        new("nl", "integer-one", "other"),
        new("no", "one", "other"),
        new("sv", "integer-one", "swedish"),
    ];
    internal static readonly GeneratedRelativeTimeLocale[] RelativeTimeLocales =
    [
        new("de", ["gestern", "heute", "morgen"], "vor {0} {unit}", "in {0} {unit}", [new("second", "Sekunde", "Sekunden"), new("minute", "Minute", "Minuten"), new("hour", "Stunde", "Stunden"), new("day", "Tag", "Tagen"), new("week", "Woche", "Wochen"), new("month", "Monat", "Monaten"), new("year", "Jahr", "Jahren")]),
        new("en", ["yesterday", "today", "tomorrow"], "{0} {unit} ago", "in {0} {unit}", [new("second", "second", "seconds"), new("minute", "minute", "minutes"), new("hour", "hour", "hours"), new("day", "day", "days"), new("week", "week", "weeks"), new("month", "month", "months"), new("year", "year", "years")]),
        new("es", ["ayer", "hoy", "mañana"], "hace {0} {unit}", "dentro de {0} {unit}", [new("second", "segundo", "segundos"), new("minute", "minuto", "minutos"), new("hour", "hora", "horas"), new("day", "día", "días"), new("week", "semana", "semanas"), new("month", "mes", "meses"), new("year", "año", "años")]),
        new("fr", ["hier", "aujourd’hui", "demain"], "il y a {0} {unit}", "dans {0} {unit}", [new("second", "seconde", "secondes"), new("minute", "minute", "minutes"), new("hour", "heure", "heures"), new("day", "jour", "jours"), new("week", "semaine", "semaines"), new("month", "mois", "mois"), new("year", "an", "ans")]),
        new("it", ["ieri", "oggi", "domani"], "{0} {unit} fa", "tra {0} {unit}", [new("second", "secondo", "secondi"), new("minute", "minuto", "minuti"), new("hour", "ora", "ore"), new("day", "giorno", "giorni"), new("week", "settimana", "settimane"), new("month", "mese", "mesi"), new("year", "anno", "anni")]),
    ];

    internal static GeneratedPluralLocale? FindPlural(string language)
    {
        for (int index = 0; index < PluralLocales.Length; index++)
            if (PluralLocales[index].Language == language) return PluralLocales[index];
        return null;
    }

    internal static GeneratedRelativeTimeLocale? FindRelativeTime(string language)
    {
        for (int index = 0; index < RelativeTimeLocales.Length; index++)
            if (RelativeTimeLocales[index].Language == language) return RelativeTimeLocales[index];
        return null;
    }
}
