<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../eng/build/translations.props" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Runic.Translations.Authoring.Tests</AssemblyName>
    <RootNamespace>Runic.Translations.Authoring.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\packages\dotnet\Runic.Translations.Authoring\Runic.Translations.Authoring.csproj" />
  </ItemGroup>
  <Import Project="../../../eng/build/translations.targets" />
</Project>
